In [112]:
import warnings
warnings.filterwarnings('ignore')

In [113]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt

In [114]:
pvi_18 = pd.read_csv('data/pres_results/2008-16_pres_2018_dists.csv')
pvi_20 = pd.read_csv('data/pres_results/2008-20_pres_2020_dists.csv')
pvi_22 = pd.read_csv('data/pres_results/2020_pres_2022_dists.csv')
pvi_24 = pd.read_csv('data/pres_results/2020-24_pres_2024_dists.csv')
pvi_24.head()

,Calculated by The Downballot,Unnamed: 1,Unnamed: 2,Subscribe to our newsletter,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Follow @the-downballot.com on Bluesky,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,District,Incumbent,Party,2024,NaN,NaN,NaN,NaN,NaN,NaN,2020,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,Harris,Trump,Total,Harris %,Trump %,Margin,NaN,Biden,Trump,Total,Biden %,Trump %,Margin
2,AK-AL,Nick Begich,(R),"140,026","184,458","338,177",41.41%,54.54%,-13.14%,NaN,"153,778","189,951","357,569",43.01%,53.12%,-10.12%
3,AL-01,Barry Moore,(R),"73,003","257,060","332,700",21.94%,77.26%,-55.32%,NaN,"79,112","243,258","325,715",24.29%,74.68%,-50.40%
4,AL-02,Shomari Figures,(D),"155,603","131,721","290,033",53.65%,45.42%,8.23%,NaN,"174,051","135,333","312,225",55.75%,43.34%,12.40%

In [115]:
pd.set_option('display.max_columns', 100)

In [116]:
# Source: Wikipedia, FEC
# Links:
# https://en.wikipedia.org/wiki/2024_United_States_presidential_election#Electoral_results
# https://www.fec.gov/resources/cms-content/documents/federalelections2020.pdf
# https://www.fec.gov/resources/cms-content/documents/federalelections2016.pdf#page=10
# https://www.fec.gov/resources/cms-content/documents/federalelections2012.pdf#page=11
dem_2pv_24 = 75017613 / (75017613 + 77302580) * 100
dem_2pv_20 = 81283501 / (81283501 + 74223975) * 100
dem_2pv_16 = 65853514 / (65853514 + 62984828) * 100
dem_2pv_12 = 65915795 / (65915795 + 60933504) * 100
dem_2pv_12, dem_2pv_16, dem_2pv_20, dem_2pv_24

(51.96386225200976, 51.113288930712876, 52.26983492420647, 49.24994613156773)

In [117]:
# 2024 districts wrangling
pvi_24 = pvi_24.iloc[2:]
pvi_24 = pvi_24.set_axis(['district', 'incumbent', 'party', 'dem_24', 'rep_24', 'tot_24', 'dem_pct_24', 'rep_pct_24',
                         'margin_24', 'na1', 'dem_20', 'rep_20', 'tot_20', 'dem_pct_20', 'rep_pct_20', 'margin_20'], axis=1)
pvi_24 = pvi_24.drop(['na1', 'margin_24', 'margin_20'], axis=1)
for col in ['dem_pct_24', 'rep_pct_24', 'dem_pct_20', 'rep_pct_20']:
    pvi_24[col] = pvi_24[col].str.rstrip('%').astype(float)
for col in ['dem_24', 'rep_24', 'tot_24', 'dem_20', 'rep_20', 'tot_20']:
    pvi_24[col] = pvi_24[col].str.replace(',', '').astype(int)
pvi_24['2p_tot_24'] = pvi_24['dem_24'] + pvi_24['rep_24']
pvi_24['dem_2p_24'] = pvi_24['dem_24'] / pvi_24['2p_tot_24'] * 100
pvi_24['rep_2p_24'] = pvi_24['rep_24'] / pvi_24['2p_tot_24'] * 100
pvi_24['2p_tot_20'] = pvi_24['dem_20'] + pvi_24['rep_20']
pvi_24['dem_2p_20'] = pvi_24['dem_20'] / pvi_24['2p_tot_20'] * 100
pvi_24['rep_2p_20'] = pvi_24['rep_20'] / pvi_24['2p_tot_20'] * 100
pvi_24.head()

,district,incumbent,party,dem_24,rep_24,tot_24,dem_pct_24,rep_pct_24,dem_20,rep_20,tot_20,dem_pct_20,rep_pct_20,2p_tot_24,dem_2p_24,rep_2p_24,2p_tot_20,dem_2p_20,rep_2p_20
2,AK-AL,Nick Begich,(R),140026,184458,338177,41.41,54.54,153778,189951,357569,43.01,53.12,324484,43.153437,56.846563,343729,44.738151,55.261849
3,AL-01,Barry Moore,(R),73003,257060,332700,21.94,77.26,79112,243258,325715,24.29,74.68,330063,22.117899,77.882101,322370,24.540745,75.459255
4,AL-02,Shomari Figures,(D),155603,131721,290033,53.65,45.42,174051,135333,312225,55.75,43.34,287324,54.155935,45.844065,309384,56.257273,43.742727
5,AL-03,Mike Rogers,(R),82654,229676,314869,26.25,72.94,93357,225360,322031,28.99,69.98,312330,26.463676,73.536324,318717,29.291503,70.708497
6,AL-04,Robert Aderholt,(R),53098,267953,323449,16.42,82.84,60121,262473,325713,18.46,80.58,321051,16.538805,83.461195,322594,18.636738,81.363262

In [118]:
# Get 2012 presidential results by district for Florida (unavailable in Daily Kos/Downballot dataset)
fl18 = pd.read_csv('data/dra/FL_2018-2020_district_data.csv')

In [119]:
fl18 = fl18[1:]
fl18 = fl18.rename({'E_12_PRES_Dem': 'dem_12', 'E_12_PRES_Rep': 'rep_12', 'E_12_PRES_Total': 'tot_12'}, axis=1)
fl18['district'] = 'FL-' + fl18['Label'].astype(int).map(lambda x: '0' if x < 10 else '') + fl18['Label'].astype(str)
fl18.head(10)

,ID,Label,T_20_CENS_Total,T_20_CENS_White,T_20_CENS_Hispanic,T_20_CENS_Black,T_20_CENS_Asian,T_20_CENS_Native,T_20_CENS_Pacific,V_20_VAP_Total,V_20_VAP_White,V_20_VAP_Hispanic,V_20_VAP_Black,V_20_VAP_Asian,V_20_VAP_Native,V_20_VAP_Pacific,tot_12,dem_12,rep_12,E_16_PRES_Total,E_16_PRES_Dem,E_16_PRES_Rep,E_16-20_COMP_Total,E_16-20_COMP_Dem,E_16-20_COMP_Rep,E_20-24_COMP_Total,E_20-24_COMP_Dem,E_20-24_COMP_Rep,district
1,1,1,807881,565520,61715,119614,35838,26649,3614,636380,462630,41999,84205,26058,20252,2348,349275,106528,242747,0,0,0,361546,106502,245815,376763,107092,265079,FL-01
2,2,2,727856,537827,55005,96863,19323,18882,1680,588566,446456,39333,73084,14061,14572,1101,325069,110727,214342,0,0,0,331097,105030,219713,351029,101211,246787,FL-02
3,3,3,766133,490232,86459,138327,37514,17176,1903,609560,407610,62753,98121,28893,13013,1316,323907,137649,186258,0,0,0,336731,139317,190509,336662,131147,201998,FL-03
4,4,4,871884,612147,86345,98991,57740,17412,2540,691279,502634,61114,71642,41601,13063,1778,371717,123377,248340,0,0,0,416259,146255,261630,451985,158810,288452,FL-04
5,5,5,748910,276549,74491,367467,26769,13892,1824,580527,233591,53084,268194,20547,10706,1286,310953,199964,110989,0,0,0,298765,184042,109283,275219,159089,112996,FL-05
6,6,6,796254,559426,110333,92485,20361,17039,1419,658454,484011,79497,66626,15599,13258,1019,336956,158711,178245,0,0,0,368623,149143,212018,399693,146798,249436,FL-06
7,7,7,788518,421207,207693,104611,53513,15367,2059,634763,356239,156479,77385,40736,11771,1481,329102,164738,164364,0,0,0,349123,181502,159170,341707,172173,165567,FL-07
8,8,8,783753,558427,93322,88802,27720,16848,1983,645163,481232,66755,62431,20758,13057,1404,358897,153020,205877,0,0,0,391293,152531,229797,408402,152188,252114,FL-08
9,9,9,955602,356187,418271,147178,41180,19334,2525,737088,297589,306139,105117,30659,14717,1851,268315,153222,115093,0,0,0,341422,180531,153774,356967,168486,184708,FL-09
10,10,10,873804,291981,262666,248533,57067,14767,2588,669945,241146,193924,178864,43560,11344,1948,268847,165230,103617,0,0,0,305546,185785,113814,299882,169778,126899,FL-10

In [120]:
# 2020 districts wrangling
pvi_20 = pvi_20.iloc[1:]
pvi_20 = pvi_20.set_axis(['district', 'incumbent', 'party', 'na0', 'dem_20', 'rep_20', 'tot_20', 'dem_pct_20', 'rep_pct_20',
                        'na1', 'dem_16', 'rep_16', 'tot_16', 'dem_pct_16', 'rep_pct_16', 'na2', 
                         'dem_12', 'rep_12', 'tot_12', 'dem_pct_12', 'rep_pct_12', 'na3',
                        'dem_08', 'rep_08', 'tot_08', 'dem_pct_08', 'rep_pct_08'], axis=1)
pvi_20 = pvi_20.drop(['na0', 'na1', 'na2', 'na3'], axis=1)
## Florida 2012 nonsense
pvi_20_fl = pvi_20[pvi_20['tot_12'].isna()]
pvi_20_notfl = pvi_20[~pvi_20['tot_12'].isna()]
def get_fl_res_12(district, party):
    # party is 'dem_12', 'rep_12', or 'tot_12'
    df = fl18[fl18['district'] == district]
    return df[party].values[0]
pvi_20_fl['dem_12'] = pvi_20_fl.apply(lambda x: get_fl_res_12(x['district'], 'dem_12'), axis=1)
pvi_20_fl['rep_12'] = pvi_20_fl.apply(lambda x: get_fl_res_12(x['district'], 'rep_12'), axis=1)
pvi_20_fl['tot_12'] = pvi_20_fl.apply(lambda x: get_fl_res_12(x['district'], 'tot_12'), axis=1)
pvi_20 = pd.concat([pvi_20_fl, pvi_20_notfl], axis=0).sort_values(by=['district'])

for yr in ['08']:
    pvi_20 = pvi_20.drop([f'dem_{yr}', f'rep_{yr}', f'tot_{yr}', f'dem_pct_{yr}', f'rep_pct_{yr}'], axis=1)
for col in ['dem_pct_20', 'rep_pct_20', 'dem_pct_16', 'rep_pct_16', 'dem_pct_12', 'rep_pct_12']:
    pvi_20[col] = pvi_20[col].str.rstrip('%').astype(float)
for col in ['dem_20', 'rep_20', 'tot_20', 'dem_16', 'rep_16', 'tot_16', 'dem_12', 'rep_12', 'tot_12']:
    pvi_20[col] = pvi_20[col].astype(str).str.replace(',', '').astype(int)
pvi_20['2p_tot_20'] = pvi_20['dem_20'] + pvi_20['rep_20']
pvi_20['dem_2p_20'] = pvi_20['dem_20'] / pvi_20['2p_tot_20'] * 100
pvi_20['rep_2p_20'] = pvi_20['rep_20'] / pvi_20['2p_tot_20'] * 100
pvi_20['2p_tot_16'] = pvi_20['dem_16'] + pvi_20['rep_16']
pvi_20['dem_2p_16'] = pvi_20['dem_16'] / pvi_20['2p_tot_16'] * 100
pvi_20['rep_2p_16'] = pvi_20['rep_16'] / pvi_20['2p_tot_16'] * 100
pvi_20['2p_tot_12'] = pvi_20['dem_12'] + pvi_20['rep_12']
pvi_20['dem_2p_12'] = pvi_20['dem_12'] / pvi_20['2p_tot_12'] * 100
pvi_20['rep_2p_12'] = pvi_20['rep_12'] / pvi_20['2p_tot_12'] * 100

pvi_20['lean_16'] = pvi_20['dem_2p_16'] - dem_2pv_16
pvi_20['lean_20'] = pvi_20['dem_2p_20'] - dem_2pv_20
pvi_20['lean_12'] = pvi_20['dem_2p_12'] - dem_2pv_12

pvi_20.head()

,district,incumbent,party,dem_20,rep_20,tot_20,dem_pct_20,rep_pct_20,dem_16,rep_16,tot_16,dem_pct_16,rep_pct_16,dem_12,rep_12,tot_12,dem_pct_12,rep_pct_12,2p_tot_20,dem_2p_20,rep_2p_20,2p_tot_16,dem_2p_16,rep_2p_16,2p_tot_12,dem_2p_12,rep_2p_12,lean_16,lean_20,lean_12
1,AK-AL,Mary Peltola,(R),153778,189951,357569,43.0,53.1,116454,163387,309407,37.6,52.8,122640,164676,297625,41.2,55.3,343729,44.738151,55.261849,279841,41.614345,58.385655,287316,42.684710,57.315290,-9.498944,-7.531684,-9.279153
2,AL-01,Jerry Carl,(R),117136,211370,331886,35.3,63.7,103364,192634,303478,34.1,63.5,111735,184786,298837,37.4,61.8,328506,35.657187,64.342813,295998,34.920506,65.079494,296521,37.681985,62.318015,-16.192783,-16.612648,-14.281877
3,AL-02,Barry Moore,(R),107776,195953,306714,35.1,63.9,94299,185505,285664,33.0,64.9,105572,182287,289864,36.4,62.9,303729,35.484264,64.515736,279804,33.701806,66.298194,287859,36.674900,63.325100,-17.411483,-16.785571,-15.288962
4,AL-03,Mike Rogers,(R),109495,212012,324741,33.7,65.3,93300,188477,288776,32.3,65.3,103089,174465,280128,36.8,62.3,321507,34.056801,65.943199,281777,33.111290,66.888710,277554,37.141962,62.858038,-18.001999,-18.213034,-14.821901
5,AL-04,Robert Aderholt,(R),57133,260535,320725,17.8,81.2,50722,233661,290726,17.4,80.4,65818,205423,274505,24.0,74.8,317668,17.985129,82.014871,284383,17.835806,82.164194,271241,24.265506,75.734494,-33.277483,-34.284706,-27.698357

In [121]:
# 2018 districts wrangling
pvi_18 = pvi_18.iloc[1:]
pvi_18 = pvi_18.set_axis(['district', 'incumbent', 'party', 'na0', 'dem_20', 'rep_20', 'tot_20', 'dem_pct_20', 'rep_pct_20',
                        'na1', 'dem_16', 'rep_16', 'tot_16', 'dem_pct_16', 'rep_pct_16', 'na2', 
                         'dem_12', 'rep_12', 'tot_12', 'dem_pct_12', 'rep_pct_12', 'na3',
                        'dem_08', 'rep_08', 'tot_08', 'dem_pct_08', 'rep_pct_08'], axis=1)
pvi_18 = pvi_18.drop(['na0', 'na1', 'na2', 'na3'], axis=1)

## Florida 2012 nonsense
pvi_18_fl = pvi_18[pvi_18['tot_12'].isna()]
pvi_18_notfl = pvi_18[~pvi_18['tot_12'].isna()]
def get_fl_res_12(district, party):
    # party is 'dem_12', 'rep_12', or 'tot_12'
    df = fl18[fl18['district'] == district]
    return df[party].values[0]
pvi_18_fl['dem_12'] = pvi_18_fl.apply(lambda x: get_fl_res_12(x['district'], 'dem_12'), axis=1)
pvi_18_fl['rep_12'] = pvi_18_fl.apply(lambda x: get_fl_res_12(x['district'], 'rep_12'), axis=1)
pvi_18_fl['tot_12'] = pvi_18_fl.apply(lambda x: get_fl_res_12(x['district'], 'tot_12'), axis=1)
pvi_18 = pd.concat([pvi_18_fl, pvi_18_notfl], axis=0).sort_values(by=['district'])

for yr in ['08', '20']:
    pvi_18 = pvi_18.drop([f'dem_{yr}', f'rep_{yr}', f'tot_{yr}', f'dem_pct_{yr}', f'rep_pct_{yr}'], axis=1)
for col in ['dem_pct_12', 'rep_pct_12', 'dem_pct_16', 'rep_pct_16']:
    pvi_18[col] = pvi_18[col].str.rstrip('%').astype(float)
for col in ['dem_12', 'rep_12', 'tot_12', 'dem_16', 'rep_16', 'tot_16']:
    pvi_18[col] = pvi_18[col].astype(str).str.replace(',', '').astype(int)
pvi_18['2p_tot_12'] = pvi_18['dem_12'] + pvi_18['rep_12']
pvi_18['dem_2p_12'] = pvi_18['dem_12'] / pvi_18['2p_tot_12'] * 100
pvi_18['rep_2p_12'] = pvi_18['rep_12'] / pvi_18['2p_tot_12'] * 100
pvi_18['2p_tot_16'] = pvi_18['dem_16'] + pvi_18['rep_16']
pvi_18['dem_2p_16'] = pvi_18['dem_16'] / pvi_18['2p_tot_16'] * 100
pvi_18['rep_2p_16'] = pvi_18['rep_16'] / pvi_18['2p_tot_16'] * 100

pvi_18['lean_16'] = pvi_18['dem_2p_16'] - dem_2pv_16
pvi_18['lean_12'] = pvi_18['dem_2p_12'] - dem_2pv_12

pvi_18.head()

,district,incumbent,party,dem_16,rep_16,tot_16,dem_pct_16,rep_pct_16,dem_12,rep_12,tot_12,dem_pct_12,rep_pct_12,2p_tot_12,dem_2p_12,rep_2p_12,2p_tot_16,dem_2p_16,rep_2p_16,lean_16,lean_12
1,AK-AL,"Young, Don",(R),116454,163387,309407,37.6,52.8,122640,164676,297625,41.2,55.3,287316,42.684710,57.315290,279841,41.614345,58.385655,-9.498944,-9.279153
2,AL-01,"Byrne, Bradley",(R),103364,192634,303478,34.1,63.5,111735,184786,298837,37.4,61.8,296521,37.681985,62.318015,295998,34.920506,65.079494,-16.192783,-14.281877
3,AL-02,"Roby, Martha",(R),94299,185505,285664,33.0,64.9,105572,182287,289864,36.4,62.9,287859,36.674900,63.325100,279804,33.701806,66.298194,-17.411483,-15.288962
4,AL-03,"Rogers, Mike",(R),93300,188477,288776,32.3,65.3,103089,174465,280128,36.8,62.3,277554,37.141962,62.858038,281777,33.111290,66.888710,-18.001999,-14.821901
5,AL-04,"Aderholt, Rob",(R),50722,233661,290726,17.4,80.4,65818,205423,274505,24.0,74.8,271241,24.265506,75.734494,284383,17.835806,82.164194,-33.277483,-27.698357

In [122]:
state_abbrevs = [
    # https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States#States.
    "AK", "AL", "AR", "AZ", "CA", "CO", "CT", "DE", "FL", "GA", "HI", "IA",
    "ID", "IL", "IN", "KS", "KY", "LA", "MA", "MD", "ME", "MI", "MN", "MO",
    "MS", "MT", "NC", "ND", "NE", "NH", "NJ", "NM", "NV", "NY", "OH", "OK",
    "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VA", "VT", "WA", "WI",
    "WV", "WY"

    # All hail Jeff Paine for this code snippet: https://gist.github.com/JeffPaine/3083347
]

In [123]:
res_16_dists_22 = pd.DataFrame()

for st in state_abbrevs:
    if st in ['DE', 'AK', 'ND', 'SD', 'WY', 'VT']:
        continue
    df = pd.read_csv(f'data/dra/{st}_2022_district_data.csv')
    df = df[1:].rename({'E_16_PRES_Dem': 'dem_16', 'E_16_PRES_Rep': 'rep_16', 'E_16_PRES_Total': 'tot_16'}, axis=1)
    df['district'] = st + '-' + df['Label'].astype(int).map(lambda x: '0' if x < 10 else '') + df['Label'].astype(str)

    df = df[['district', 'dem_16', 'rep_16', 'tot_16']]

    res_16_dists_22 = pd.concat([res_16_dists_22, df], axis=0)

In [124]:
res_16_dists_22.head()

  district  dem_16  rep_16  tot_16
1    AL-01  101839  189526  301237
2    AL-02   96668  193978  299195
3    AL-03   88876  187604  285575
4    AL-04   53761  235439  298177
5    AL-05   91722  189922  297866

In [125]:
# 2022 districts wrangling
pvi_22 = pvi_22.set_axis(['district', 'incumbent', 'party', 'dem_20', 'rep_20', 'tot_20', 'dem_pct_20', 'rep_pct_20'], axis=1)

def get_16(district, party):
    # party is 'dem_16', 'rep_16', or 'tot_16'
    if district[:2] in ['DE', 'AK', 'ND', 'SD', 'WY', 'VT']:
        df = pvi_20[pvi_20['district'] == district]
        return df[party].values[0]
    
    df = res_16_dists_22[res_16_dists_22['district'] == district]
    return df[party].values[0]

for col in ['dem_16', 'rep_16', 'tot_16']:
    pvi_22[col] = pvi_22.apply(lambda x: get_16(x['district'], col), axis=1)

for col in ['dem_pct_20', 'rep_pct_20']:
    pvi_22[col] = pvi_22[col].str.rstrip('%').astype(float)
for col in ['dem_20', 'rep_20', 'tot_20', 'dem_16', 'rep_16', 'tot_16']:
    pvi_22[col] = pvi_22[col].astype(str).str.replace(',', '').astype(int)

for yr in ['16', '20']:
    pvi_22[f'2p_tot_{yr}'] = pvi_22[f'dem_{yr}'] + pvi_22[f'rep_{yr}']
    pvi_22[f'dem_2p_{yr}'] = pvi_22[f'dem_{yr}'] / pvi_22[f'2p_tot_{yr}'] * 100
    pvi_22[f'rep_2p_{yr}'] = pvi_22[f'rep_{yr}'] / pvi_22[f'2p_tot_{yr}'] * 100

    baseline = dem_2pv_16 if yr == '16' else dem_2pv_20
    pvi_22[f'lean_{yr}'] = pvi_22[f'dem_2p_{yr}'] - baseline
pvi_22.head()

,district,incumbent,party,dem_20,rep_20,tot_20,dem_pct_20,rep_pct_20,dem_16,rep_16,tot_16,2p_tot_16,dem_2p_16,rep_2p_16,lean_16,2p_tot_20,dem_2p_20,rep_2p_20,lean_20
0,AK-AL,Mary Peltola,(D),153778,189951,357569,43.0,53.1,116454,163387,309407,279841,41.614345,58.385655,-9.498944,343729,44.738151,55.261849,-7.531684
1,AL-01,Jerry Carl,(R),115566,208116,327039,35.3,63.6,101839,189526,301237,291365,34.952379,65.047621,-16.160910,323682,35.703561,64.296439,-16.566274
2,AL-02,Barry Moore,(R),111264,205435,319817,34.8,64.2,96668,193978,299195,290646,33.259704,66.740296,-17.853585,316699,35.132413,64.867587,-17.137422
3,AL-03,Mike Rogers,(R),102772,210797,316695,32.5,66.6,88876,187604,285575,276480,32.145544,67.854456,-18.967745,313569,32.774924,67.225076,-19.494911
4,AL-04,Robert Aderholt,(R),60733,262359,326261,18.6,80.4,53761,235439,298177,289200,18.589557,81.410443,-32.523732,323092,18.797432,81.202568,-33.472403

In [126]:
res_16_dists_24 = pd.DataFrame()

for st in state_abbrevs:
    if st in ['DE', 'AK', 'ND', 'SD', 'WY', 'VT']:
        continue
    if st in ['NY', 'GA', 'NC', 'LA', 'AL']:
        df = pd.read_csv(f'data/dra/{st}_2024_district_data.csv')
    else:
        df = pd.read_csv(f'data/dra/{st}_2022_district_data.csv')
    df = df[1:].rename({'E_16_PRES_Dem': 'dem_16', 'E_16_PRES_Rep': 'rep_16', 'E_16_PRES_Total': 'tot_16'}, axis=1)
    df['district'] = st + '-' + df['Label'].astype(int).map(lambda x: '0' if x < 10 else '') + df['Label'].astype(str)

    df = df[['district', 'dem_16', 'rep_16', 'tot_16']]

    res_16_dists_24 = pd.concat([res_16_dists_24, df], axis=0)

In [127]:
res_16_dists_24.head()

  district  dem_16  rep_16  tot_16
1    AL-01   64080  220085  293420
2    AL-02  163388  131758  303364
3    AL-03   79538  200498  289677
4    AL-04   51956  236405  297488
5    AL-05   92178  189897  298086

In [128]:
def get_16(district, party):
    # party is 'dem_16', 'rep_16', or 'tot_16'
    if district[:2] in ['DE', 'AK', 'ND', 'SD', 'WY', 'VT']:
        df = pvi_20[pvi_20['district'] == district]
        return df[party].values[0]
    
    df = res_16_dists_24[res_16_dists_24['district'] == district]
    return df[party].values[0]

for col in ['dem_16', 'rep_16', 'tot_16']:
    pvi_24[col] = pvi_24.apply(lambda x: get_16(x['district'], col), axis=1)

for yr in ['16', '20', '24']:
    pvi_24[f'2p_tot_{yr}'] = pvi_24[f'dem_{yr}'] + pvi_24[f'rep_{yr}']
    pvi_24[f'dem_2p_{yr}'] = pvi_24[f'dem_{yr}'] / pvi_24[f'2p_tot_{yr}'] * 100
    pvi_24[f'rep_2p_{yr}'] = pvi_24[f'rep_{yr}'] / pvi_24[f'2p_tot_{yr}'] * 100

    baseline = dem_2pv_16 if yr == '16' else (dem_2pv_20 if yr == '20' else dem_2pv_24)
    pvi_24[f'lean_{yr}'] = pvi_24[f'dem_2p_{yr}'] - baseline
pvi_24.head()

,district,incumbent,party,dem_24,rep_24,tot_24,dem_pct_24,rep_pct_24,dem_20,rep_20,tot_20,dem_pct_20,rep_pct_20,2p_tot_24,dem_2p_24,rep_2p_24,2p_tot_20,dem_2p_20,rep_2p_20,dem_16,rep_16,tot_16,2p_tot_16,dem_2p_16,rep_2p_16,lean_16,lean_20,lean_24
2,AK-AL,Nick Begich,(R),140026,184458,338177,41.41,54.54,153778,189951,357569,43.01,53.12,324484,43.153437,56.846563,343729,44.738151,55.261849,116454,163387,309407,279841,41.614345,58.385655,-9.498944,-7.531684,-6.096509
3,AL-01,Barry Moore,(R),73003,257060,332700,21.94,77.26,79112,243258,325715,24.29,74.68,330063,22.117899,77.882101,322370,24.540745,75.459255,64080,220085,293420,284165,22.550279,77.449721,-28.563010,-27.729090,-27.132047
4,AL-02,Shomari Figures,(D),155603,131721,290033,53.65,45.42,174051,135333,312225,55.75,43.34,287324,54.155935,45.844065,309384,56.257273,43.742727,163388,131758,303364,295146,55.358365,44.641635,4.245076,3.987438,4.905989
5,AL-03,Mike Rogers,(R),82654,229676,314869,26.25,72.94,93357,225360,322031,28.99,69.98,312330,26.463676,73.536324,318717,29.291503,70.708497,79538,200498,289677,280036,28.402777,71.597223,-22.710512,-22.978332,-22.786270
6,AL-04,Robert Aderholt,(R),53098,267953,323449,16.42,82.84,60121,262473,325713,18.46,80.58,321051,16.538805,83.461195,322594,18.636738,81.363262,51956,236405,297488,288361,18.017693,81.982307,-33.095596,-33.633096,-32.711141

In [129]:
pvi_24.to_csv('transformed/pvi/past_pres_results_by24dist.csv')
pvi_22.to_csv('transformed/pvi/past_pres_results_by22dist.csv')
pvi_20.to_csv('transformed/pvi/past_pres_results_by20dist.csv')
pvi_18.to_csv('transformed/pvi/past_pres_results_by18dist.csv')