In [44]:
import warnings
warnings.filterwarnings('ignore')

In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ast

In [46]:
data = pd.read_csv('transformed/past_house_results.csv')
data.head()

,year,state,state_po,special,district,dem,rep,totalvotes,dem_cand,rep_cand,...,dem_funds,rep_funds,2party_votes,dem_pct_2p,rep_pct_2p,dem_tot_funds,rep_tot_funds,tot_funds,dem_funds_2p_pct,rep_funds_2p_pct
0,2018,Alabama,AL,False,1,89226.0,153228.0,242617,Robert Kennedy Jr,Bradley Byrne,...,39095.21,343761.59,242454.0,36.801208,63.198792,39095.21,343761.59,382856.80,10.211445,89.788555
1,2018,Alabama,AL,False,2,86931.0,138879.0,226230,Tabitha Isner,Martha Roby,...,501490.57,799289.56,225810.0,38.497409,61.502591,501490.57,799289.56,1300780.13,38.553062,61.446938
2,2018,Alabama,AL,False,3,83996.0,147770.0,231915,Mallory Hagan,Mike Rogers,...,409309.26,530372.0,231766.0,36.241727,63.758273,409309.26,530372.00,939681.26,43.558308,56.441692
3,2018,Alabama,AL,False,4,46492.0,184255.0,230969,Lee Auman,Robert Aderholt,...,61160.87,468336.48,230747.0,20.148474,79.851526,61160.87,468336.48,529497.35,11.550741,88.449259
4,2018,Alabama,AL,False,5,101388.0,159063.0,260673,Peter Joffrion,Mo Brooks,...,553386.53,1216500.38,260451.0,38.927860,61.072140,553386.53,1216500.38,1769886.91,31.266773,68.733227

In [47]:
data.columns

Index(['year', 'state', 'state_po', 'special', 'district', 'dem', 'rep',
       'totalvotes', 'dem_cand', 'rep_cand', 'dem_inc', 'rep_inc', 'dem_funds',
       'rep_funds', '2party_votes', 'dem_pct_2p', 'rep_pct_2p',
       'dem_tot_funds', 'rep_tot_funds', 'tot_funds', 'dem_funds_2p_pct',
       'rep_funds_2p_pct'],
      dtype='object')

In [69]:
demo22_cols = ['district_name', 'district', 'white_pct', 'black_pct', 'hisp_pct', 'asn_pct',
                           'natam_pct', 'pi_pct', 'vap_white_pct', 'vap_black_pct', 'vap_hisp_pct', 'vap_asn_pct',
                           'vap_natam_pct', 'vap_pi_pct', 'cit_white_pct', 'cit_black_pct', 'cit_hisp_pct', 'cit_asn_pct',
                           'cit_natam_pct', 'cit_pi_pct', 'cvap_white_pct', 'cvap_black_pct', 'cvap_hisp_pct', 'cvap_asn_pct',
                           'cvap_natam_pct', 'cvap_pi_pct', 'tot_population', 'white_pop', 'black_pop', 'hisp_pop',
                           'asn_pop', 'natam_pop', 'pi_pop', 'vap_pop', 'white_vap_pop', 'black_vap_pop', 'hisp_vap_pop', 'asn_vap_pop',
                           'natam_vap_pop', 'pi_vap_pop', 'cit_pop', 'white_cit_pop', 'black_cit_pop', 'hisp_cit_pop', 'asn_cit_pop',
                           'natam_cit_pop', 'pi_cit_pop', 'cvap_pop', 'white_cvap_pop', 'black_cvap_pop', 'hisp_cvap_pop', 'asn_cvap_pop',
                           'natam_cvap_pop', 'pi_cvap_pop']

demo_cols = ['district_name', 'district', 'white_pct', 'black_pct', 'hisp_pct', 'asn_pct',
                           'natam_pct', 'other_pct', 'vap_white_pct', 'vap_black_pct', 'vap_hisp_pct', 'vap_asn_pct',
                           'vap_natam_pct', 'vap_other_pct', 'cit_white_pct', 'cit_black_pct', 'cit_hisp_pct', 'cit_asn_pct',
                           'cit_natam_pct', 'cit_other_pct', 'cvap_white_pct', 'cvap_black_pct', 'cvap_hisp_pct', 'cvap_asn_pct',
                           'cvap_natam_pct', 'cvap_other_pct', 'tot_population', 'white_pop', 'black_pop', 'hisp_pop',
                           'asn_pop', 'natam_pop', 'other_pop', 'vap_pop', 'white_vap_pop', 'black_vap_pop', 'hisp_vap_pop', 'asn_vap_pop',
                           'natam_vap_pop', 'other_vap_pop', 'cit_pop', 'white_cit_pop', 'black_cit_pop', 'hisp_cit_pop', 'asn_cit_pop',
                           'natam_cit_pop', 'other_cit_pop', 'cvap_pop', 'white_cvap_pop', 'black_cvap_pop', 'hisp_cvap_pop', 'asn_cvap_pop',
                           'natam_cvap_pop', 'other_cvap_pop']

In [75]:
demo_18 = pd.read_csv('data/demo/2018_116_acs_demo.csv')
demo_18 = demo_18.iloc[2:]
demo_18 = demo_18.set_axis(demo_cols, axis=1)
demo_18.head()

,district_name,district,white_pct,black_pct,hisp_pct,asn_pct,natam_pct,other_pct,vap_white_pct,vap_black_pct,vap_hisp_pct,vap_asn_pct,vap_natam_pct,vap_other_pct,cit_white_pct,cit_black_pct,cit_hisp_pct,cit_asn_pct,cit_natam_pct,cit_other_pct,cvap_white_pct,cvap_black_pct,cvap_hisp_pct,cvap_asn_pct,cvap_natam_pct,cvap_other_pct,tot_population,white_pop,black_pop,hisp_pop,asn_pop,natam_pop,other_pop,vap_pop,white_vap_pop,black_vap_pop,hisp_vap_pop,asn_vap_pop,natam_vap_pop,other_vap_pop,cit_pop,white_cit_pop,black_cit_pop,hisp_cit_pop,asn_cit_pop,natam_cit_pop,other_cit_pop,cvap_pop,white_cvap_pop,black_cvap_pop,hisp_cvap_pop,asn_cvap_pop,natam_cvap_pop,other_cvap_pop
2,Alabama's 1st,AL-01,65.2,27.6,3.2,1.5,1.0,1.4,67.6,26.0,2.7,1.5,1.1,1.1,65.9,27.9,2.6,1.1,1.0,1.5,68.3,26.4,2.1,1.1,1.1,1.1,"706,505","460,835","194,675","22,650","10,860","7,285","10,190","543,485","367,235","141,425","14,770","8,250","5,870","5,935","695,990","458,390","194,055","18,370","7,770","7,255","10,150","534,355","365,070","140,815","11,025","5,710","5,840","5,895"
3,Alabama's 2nd,AL-02,61.9,31.2,3.6,1.2,0.4,1.9,64.3,30.1,2.8,1.2,0.4,1.3,62.7,31.6,2.8,0.7,0.4,1.9,65.3,30.5,1.9,0.6,0.4,1.3,"680,575","421,195","212,025","24,165","7,895","2,545","12,745","526,245","338,595","158,165","14,675","6,160","2,050","6,585","669,095","419,285","211,235","18,815","4,610","2,540","12,605","516,040","336,825","157,445","9,980","3,250","2,045","6,495"
4,Alabama's 3rd,AL-03,67.8,25.4,3.1,1.8,0.3,1.6,69.5,24.9,2.5,1.8,0.3,1.0,68.8,25.7,2.5,1.0,0.3,1.7,70.7,25.3,1.8,0.8,0.3,1.0,"706,705","478,860","179,360","21,890","12,975","1,975","11,645","550,515","382,745","136,810","13,890","9,775","1,610","5,685","693,050","476,675","178,450","17,410","6,935","1,975","11,610","538,125","380,720","135,955","9,705","4,490","1,610","5,640"
5,Alabama's 4th,AL-04,83.7,6.9,6.5,0.6,0.7,1.6,85.9,6.9,4.7,0.6,0.7,1.2,85.8,7.0,4.4,0.4,0.7,1.7,88.5,7.0,2.2,0.4,0.7,1.2,"683,390","571,665","47,305","44,355","4,070","4,775","11,215","527,385","453,225","36,190","24,705","3,180","3,815","6,265","665,230","570,500","46,645","29,310","2,795","4,775","11,210","511,065","452,155","35,585","11,105","2,135","3,815","6,260"
6,Alabama's 5th,AL-05,72.8,17.4,5.1,1.7,0.6,2.4,74.8,17.0,4.0,1.8,0.6,1.8,74.3,17.6,3.8,1.3,0.6,2.4,76.6,17.3,2.4,1.2,0.7,1.8,"714,145","519,710","124,365","36,380","12,345","4,345","17,000","556,545","416,155","94,800","22,070","9,880","3,520","10,120","696,775","517,560","122,865","26,480","8,890","4,345","16,635","540,510","414,195","93,455","12,955","6,615","3,520","9,770"

In [76]:
demo_20 = pd.read_csv('data/demo/2019_117_acs_demo.csv')
demo_20 = demo_20.iloc[2:]
demo_20 = demo_20.set_axis(demo_cols, axis=1)
demo_20.head()

,district_name,district,white_pct,black_pct,hisp_pct,asn_pct,natam_pct,other_pct,vap_white_pct,vap_black_pct,vap_hisp_pct,vap_asn_pct,vap_natam_pct,vap_other_pct,cit_white_pct,cit_black_pct,cit_hisp_pct,cit_asn_pct,cit_natam_pct,cit_other_pct,cvap_white_pct,cvap_black_pct,cvap_hisp_pct,cvap_asn_pct,cvap_natam_pct,cvap_other_pct,tot_population,white_pop,black_pop,hisp_pop,asn_pop,natam_pop,other_pop,vap_pop,white_vap_pop,black_vap_pop,hisp_vap_pop,asn_vap_pop,natam_vap_pop,other_vap_pop,cit_pop,white_cit_pop,black_cit_pop,hisp_cit_pop,asn_cit_pop,natam_cit_pop,other_cit_pop,cvap_pop,white_cvap_pop,black_cvap_pop,hisp_cvap_pop,asn_cvap_pop,natam_cvap_pop,other_cvap_pop
2,Alabama's 1st,AL-01,65.2,27.5,3.2,1.5,1.1,1.5,67.5,26.0,2.7,1.5,1.1,1.2,65.8,27.8,2.6,1.2,1.1,1.5,68.3,26.3,2.0,1.1,1.1,1.2,"710,130","463,195","195,190","22,915","10,620","7,600","10,610","547,330","369,585","142,505","15,005","8,080","5,820","6,335","699,980","460,860","194,485","18,325","8,140","7,600","10,570","538,420","367,555","141,810","10,985","5,950","5,820","6,300"
3,Alabama's 2nd,AL-02,61.5,31.2,3.7,1.2,0.4,1.9,64.0,30.2,2.9,1.3,0.4,1.2,62.3,31.7,3.0,0.7,0.4,1.9,64.9,30.7,2.0,0.7,0.4,1.3,"679,690","418,085","212,365","25,465","8,315","2,430","13,030","525,975","336,430","159,020","15,370","6,585","2,020","6,550","668,240","416,260","211,880","19,940","4,830","2,425","12,905","516,005","334,800","158,600","10,565","3,560","2,015","6,465"
4,Alabama's 3rd,AL-03,67.6,25.5,3.1,1.9,0.3,1.6,69.3,25.0,2.5,1.8,0.3,1.1,68.7,25.9,2.5,1.0,0.3,1.7,70.6,25.4,1.8,0.8,0.3,1.1,"708,885","479,110","180,820","22,160","13,215","1,930","11,650","553,255","383,495","138,250","13,900","9,840","1,545","6,225","695,135","477,250","179,775","17,535","7,085","1,930","11,560","540,935","381,805","137,270","9,705","4,475","1,545","6,135"
5,Alabama's 4th,AL-04,83.4,7.0,6.6,0.6,0.6,1.7,85.8,6.9,4.7,0.6,0.7,1.3,85.6,7.1,4.5,0.4,0.7,1.8,88.4,7.0,2.2,0.4,0.7,1.3,"684,745","571,390","47,905","45,280","4,075","4,360","11,735","528,730","453,760","36,505","25,100","3,110","3,600","6,655","665,990","569,765","47,170","30,155","2,820","4,360","11,720","511,775","452,235","35,895","11,320","2,085","3,600","6,640"
6,Alabama's 5th,AL-05,72.5,17.6,5.2,1.8,0.6,2.3,74.5,17.3,4.0,1.8,0.6,1.8,73.9,17.8,3.9,1.4,0.6,2.3,76.3,17.5,2.5,1.3,0.6,1.8,"720,360","522,225","126,790","37,585","13,005","4,215","16,540","562,515","419,050","97,060","22,725","10,250","3,455","9,975","703,210","519,995","125,365","27,645","9,810","4,185","16,210","546,480","417,040","95,765","13,420","7,185","3,430","9,640"

In [77]:
demo_22 = pd.read_csv('data/demo/2022_118_acs_demo.csv')
demo_22 = demo_22.iloc[2:]
demo_22 = demo_22.set_axis(demo22_cols, axis=1)
demo_22.head()

,district_name,district,white_pct,black_pct,hisp_pct,asn_pct,natam_pct,pi_pct,vap_white_pct,vap_black_pct,vap_hisp_pct,vap_asn_pct,vap_natam_pct,vap_pi_pct,cit_white_pct,cit_black_pct,cit_hisp_pct,cit_asn_pct,cit_natam_pct,cit_pi_pct,cvap_white_pct,cvap_black_pct,cvap_hisp_pct,cvap_asn_pct,cvap_natam_pct,cvap_pi_pct,tot_population,white_pop,black_pop,hisp_pop,asn_pop,natam_pop,pi_pop,vap_pop,white_vap_pop,black_vap_pop,hisp_vap_pop,asn_vap_pop,natam_vap_pop,pi_vap_pop,cit_pop,white_cit_pop,black_cit_pop,hisp_cit_pop,asn_cit_pop,natam_cit_pop,pi_cit_pop,cvap_pop,white_cvap_pop,black_cvap_pop,hisp_cvap_pop,asn_cvap_pop,natam_cvap_pop,pi_cvap_pop
2,Alabama's 1st,AL-01,65.3,27.4,3.5,1.9,1.6,0.0,67.5,25.8,3.0,1.7,1.7,0.0,65.9,27.7,2.9,1.6,1.6,0.0,68.3,26.1,2.3,1.4,1.7,0.0,"718,905","469,210","197,250","25,020","13,465","11,655",155,"557,645","376,560","143,960","16,665","9,685","9,390",150,"708,535","466,810","196,025","20,710","11,105","11,655",105,"548,455","374,540","143,035","12,720","7,450","9,390",95
3,Alabama's 2nd,AL-02,60.6,32.0,4.1,2.1,1.0,0.0,63.2,30.5,3.2,2.0,1.1,0.0,61.6,32.6,3.3,1.4,1.0,0.0,64.3,31.1,2.2,1.3,1.1,0.0,"714,525","433,330","228,870","29,085","15,005","7,140",70,"552,575","349,085","168,585","17,450","11,230","5,860",55,"700,735","431,385","228,090","22,905","10,125","7,130",65,"540,250","347,310","168,065","11,665","6,995","5,850",50
4,Alabama's 3rd,AL-03,68.2,25.6,3.4,1.7,0.8,0.1,69.8,24.7,2.8,1.6,0.8,0.1,69.0,25.9,2.8,1.1,0.8,0.1,70.8,25.0,2.1,0.9,0.9,0.1,"717,660","489,385","183,825","24,335","12,220","5,670",400,"566,410","395,290","140,010","15,715","9,220","4,745",295,"706,170","487,600","182,945","20,075","7,730","5,665",400,"556,010","393,565","139,185","11,895","5,220","4,745",295
5,Alabama's 4th,AL-04,82.5,8.1,6.9,0.8,1.6,0.0,84.8,7.6,5.0,0.7,1.6,0.0,84.4,8.2,5.0,0.6,1.6,0.0,87.1,7.8,2.7,0.6,1.7,0.0,"717,745","592,155","57,870","49,845","5,600","11,380",300,"556,165","471,765","42,390","28,085","4,095","9,150",240,"700,025","590,650","57,400","35,240","4,480","11,380",280,"540,005","470,370","42,035","14,785","3,000","9,150",220
6,Alabama's 5th,AL-05,71.3,18.9,5.7,2.3,1.6,0.0,73.3,18.2,4.4,2.2,1.7,0.0,72.8,19.2,4.4,1.8,1.6,0.0,75.1,18.6,2.9,1.7,1.7,0.0,"720,870","514,120","136,050","40,745","16,660","11,175",330,"565,775","414,805","103,030","25,100","12,580","9,345",225,"702,965","511,560","134,870","30,670","12,765","11,135",305,"549,440","412,430","102,010","15,835","9,070","9,305",210

In [101]:
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "Virgin Islands, U.S.": "VI",
} # https://gist.github.com/rogerallen/1583593

In [99]:
demo_24 = pd.read_csv('data/demo/2024_119_acs_demo_census.csv')
demo_24 = pd.pivot_table(demo_24, columns=['lntitle'], index=['geoname', 'geoid'], values='cvap_est', aggfunc='first')
demo_24 = demo_24.reset_index()
extr_tokens = demo_24['geoname'].str.extract(r"Congressional District (\(at Large\)|\d+) \(119th Congress\), ([A-za-z\s]+)")
demo_24 = pd.concat([demo_24, extr_tokens], axis=1)
demo_24 = demo_24.rename({0: 'seat_number', 1: 'state'}, axis=1)
demo_24 = demo[~demo_24['state'].isna()]
demo_24['district'] = demo_24['state'].astype(str).map(us_state_to_abbrev) + '-' + demo_24['seat_number'].map(lambda x: '')
demo_24.head(10)

,geoname,geoid,American Indian or Alaska Native Alone,American Indian or Alaska Native and Black or African American,American Indian or Alaska Native and White,Asian Alone,Asian and White,Black or African American Alone,Black or African American and White,Hispanic or Latino,Native Hawaiian or Other Pacific Islander Alone,Not Hispanic or Latino,Remainder of Two or More Race Responses,Total,White Alone,0,1
0,Congressional District (at Large) (119th Congr...,5001900US0200,68109,714,23514,28657,5162,16582,3946,32606,6266,506209,5913,538819,347344,(at Large),Alaska
1,Congressional District (at Large) (119th Congr...,5001900US1000,1133,2491,3484,22757,3153,161288,9000,52329,221,711784,2520,764114,505731,(at Large),Delaware
2,Congressional District (at Large) (119th Congr...,5001900US3800,21664,388,7822,4497,2076,12346,1982,19710,560,562026,1126,581736,509563,(at Large),North Dakota
3,Congressional District (at Large) (119th Congr...,5001900US4600,41203,389,11004,5995,2937,10007,2740,18081,245,651652,1221,669728,575918,(at Large),South Dakota
4,Congressional District (at Large) (119th Congr...,5001900US5000,634,153,5109,6478,2896,5264,2265,11586,32,510212,961,521797,486424,(at Large),Vermont
5,Congressional District (at Large) (119th Congr...,5001900US5600,6484,55,5898,2513,2114,3452,1242,34241,287,406052,1379,440292,382629,(at Large),Wyoming
6,"Congressional District 1 (119th Congress), Ala...",5001900US0101,2697,426,6326,5603,1813,87067,2461,17801,203,541630,1810,559435,433233,1,Alabama
7,"Congressional District 1 (119th Congress), Ari...",5001900US0401,7587,337,4158,19495,5141,20112,4543,79451,1173,541609,2150,621060,476907,1,Arizona
8,"Congressional District 1 (119th Congress), Ark...",5001900US0501,1366,673,8432,2310,940,90719,3468,13902,298,555095,825,568995,446068,1,Arkansas
9,"Congressional District 1 (119th Congress), Cal...",5001900US0601,6541,390,10754,27679,4218,10965,3402,94539,1363,454676,2210,549210,387157,1,California

In [96]:
demo_24['geoname'].values[:10]

array(['Congressional District (at Large) (119th Congress), Alaska',
       'Congressional District (at Large) (119th Congress), Delaware',
       'Congressional District (at Large) (119th Congress), North Dakota',
       'Congressional District (at Large) (119th Congress), South Dakota',
       'Congressional District (at Large) (119th Congress), Vermont',
       'Congressional District (at Large) (119th Congress), Wyoming',
       'Congressional District 1 (119th Congress), Alabama',
       'Congressional District 1 (119th Congress), Arizona',
       'Congressional District 1 (119th Congress), Arkansas',
       'Congressional District 1 (119th Congress), California'],
      dtype=object)

In [61]:
pd.set_option('display.max_columns', 100)

In [48]:
joined_dfs = []

for yr in np.unique(data['year']):
    pvi = pd.read_csv(f'transformed/pvi/past_pres_results_by{yr % 2000}dist.csv')
    prev_cyc = (yr % 2000) - ((yr % 2000) % 4)
    prev_2cyc = prev_cyc - 4
    pvi['district'] = pvi['district'].map(lambda x: x[:2] + '-00' if x[3:] == 'AL' else x)
    df = data[data['year'] == yr]
    df['district'] = df['state_po'] + '-' + df['district'].map(lambda x: f'0{x}' if x < 10 else f'{x}')
    pvi = pvi[['district', f'lean_{prev_cyc}', f'lean_{prev_2cyc}']]
    df = pd.merge(left=df, right=pvi, on='district', how='left')
    df = df.rename({
        f'lean_{prev_cyc}': 'prev_lean',
        f'lean_{prev_2cyc}': 'prev2_lean'
    }, axis='columns')


    hist_gb = pd.read_csv(f'../snoutcounter-backend/averages/historical/historical_generic_ballot_{yr}.csv')
    if yr in [2018, 2020]:
        hist_appr = pd.read_csv('../snoutcounter-backend/averages/historical/historical_presidential_approval_trump_firstterm.csv')
    else:
        hist_appr = pd.read_csv('../snoutcounter-backend/averages/historical/historical_presidential_approval_biden.csv')
    gb = hist_gb.iloc[-1]['net']
    match yr:
        case 2018:
            appr = hist_appr[pd.to_datetime(hist_appr['end_date']) == pd.to_datetime('2018-11-06')]['net'].values[0]
            inc_pres = -1 # -1 for Rep, +1 for Dem
        case 2020:
            appr = hist_appr[pd.to_datetime(hist_appr['end_date']) == pd.to_datetime('2020-11-03')]['net'].values[0]
            inc_pres = -1
        case 2022:
            appr = hist_appr[pd.to_datetime(hist_appr['end_date']) == pd.to_datetime('2022-11-08')]['net'].values[0]
            inc_pres = 1
        case 2024:
            appr = hist_appr[pd.to_datetime(hist_appr['end_date']) == pd.to_datetime('2024-11-05')]['net'].values[0]
            inc_pres = 1
        case _:
            raise ValueError('Invalid year')
    df['generic_ballot_avg'] = np.full(shape=(df.shape[0],), fill_value=gb)
    df['pres_approval_avg'] = np.full(shape=(df.shape[0],), fill_value=appr)
    df['incumbent_pres'] = np.full(shape=(df.shape[0],), fill_value=inc_pres)

    ics = pd.read_csv('data/tbmics.csv')
    ics_curr = ics[(ics['Month'] == 'November') & (ics['YYYY'] == yr)]['ICS_ALL'].values[0]
    df['ics'] = np.full(shape=(df.shape[0],), fill_value=ics_curr)

    # Best to use interaction terms for presidential approval and ICS - otherwise we won't have consistent effect
    # For instance high ICS is good for Dems if Dem president is incumbent but bad for Dems if Republican president is incumbent
    df['pres_approval_avg_x_incpres'] = df['pres_approval_avg'] * df['incumbent_pres']
    df['ics_x_incpres'] = df['ics'] * df['incumbent_pres']
    
            
    joined_dfs.append(df)

mdata = pd.concat(joined_dfs, axis=0)
mdata.head()

,year,state,state_po,special,district,dem,rep,totalvotes,dem_cand,rep_cand,...,dem_funds_2p_pct,rep_funds_2p_pct,prev_lean,prev2_lean,generic_ballot_avg,pres_approval_avg,incumbent_pres,ics,pres_approval_avg_x_incpres,ics_x_incpres
0,2018,Alabama,AL,False,AL-01,89226.0,153228.0,242617,Robert Kennedy Jr,Bradley Byrne,...,10.211445,89.788555,-16.192783,-14.281877,-7.921785,-10.073704,-1,97.5,10.073704,-97.5
1,2018,Alabama,AL,False,AL-02,86931.0,138879.0,226230,Tabitha Isner,Martha Roby,...,38.553062,61.446938,-17.411483,-15.288962,-7.921785,-10.073704,-1,97.5,10.073704,-97.5
2,2018,Alabama,AL,False,AL-03,83996.0,147770.0,231915,Mallory Hagan,Mike Rogers,...,43.558308,56.441692,-18.001999,-14.821901,-7.921785,-10.073704,-1,97.5,10.073704,-97.5
3,2018,Alabama,AL,False,AL-04,46492.0,184255.0,230969,Lee Auman,Robert Aderholt,...,11.550741,88.449259,-33.277483,-27.698357,-7.921785,-10.073704,-1,97.5,10.073704,-97.5
4,2018,Alabama,AL,False,AL-05,101388.0,159063.0,260673,Peter Joffrion,Mo Brooks,...,31.266773,68.733227,-18.480031,-16.661366,-7.921785,-10.073704,-1,97.5,10.073704,-97.5

In [49]:
mdata.columns.values

array(['year', 'state', 'state_po', 'special', 'district', 'dem', 'rep',
       'totalvotes', 'dem_cand', 'rep_cand', 'dem_inc', 'rep_inc',
       'dem_funds', 'rep_funds', '2party_votes', 'dem_pct_2p',
       'rep_pct_2p', 'dem_tot_funds', 'rep_tot_funds', 'tot_funds',
       'dem_funds_2p_pct', 'rep_funds_2p_pct', 'prev_lean', 'prev2_lean',
       'generic_ballot_avg', 'pres_approval_avg', 'incumbent_pres', 'ics',
       'pres_approval_avg_x_incpres', 'ics_x_incpres'], dtype=object)

In [50]:
mdata.shape

(1728, 30)

In [51]:
isinstance(3, int)

True

In [42]:
for party in ['dem', 'rep']:
    mdata[f'{party}_funds_2p_pct'] = mdata[f'{party}_funds_2p_pct'].fillna(0)

In [52]:
# Exclude uncontested races and races w/ all candidates from one party
mdata['no_dem_cand_flag'] = mdata['dem_cand'].map(lambda x: x == '[]')
mdata['no_rep_cand_flag'] = mdata['rep_cand'].map(lambda x: x == '[]')
uncontested = mdata[(mdata['no_dem_cand_flag']) | (mdata['no_rep_cand_flag'])]
mdata = mdata[~mdata['no_dem_cand_flag']]
mdata = mdata[~mdata['no_rep_cand_flag']]
mdata.head()

,year,state,state_po,special,district,dem,rep,totalvotes,dem_cand,rep_cand,...,prev_lean,prev2_lean,generic_ballot_avg,pres_approval_avg,incumbent_pres,ics,pres_approval_avg_x_incpres,ics_x_incpres,no_dem_cand_flag,no_rep_cand_flag
0,2018,Alabama,AL,False,AL-01,89226.0,153228.0,242617,Robert Kennedy Jr,Bradley Byrne,...,-16.192783,-14.281877,-7.921785,-10.073704,-1,97.5,10.073704,-97.5,False,False
1,2018,Alabama,AL,False,AL-02,86931.0,138879.0,226230,Tabitha Isner,Martha Roby,...,-17.411483,-15.288962,-7.921785,-10.073704,-1,97.5,10.073704,-97.5,False,False
2,2018,Alabama,AL,False,AL-03,83996.0,147770.0,231915,Mallory Hagan,Mike Rogers,...,-18.001999,-14.821901,-7.921785,-10.073704,-1,97.5,10.073704,-97.5,False,False
3,2018,Alabama,AL,False,AL-04,46492.0,184255.0,230969,Lee Auman,Robert Aderholt,...,-33.277483,-27.698357,-7.921785,-10.073704,-1,97.5,10.073704,-97.5,False,False
4,2018,Alabama,AL,False,AL-05,101388.0,159063.0,260673,Peter Joffrion,Mo Brooks,...,-18.480031,-16.661366,-7.921785,-10.073704,-1,97.5,10.073704,-97.5,False,False

In [56]:
sum(uncontested[uncontested['year'] == 2024]['no_rep_cand_flag'])

18

In [57]:
uncontested[uncontested['year'] == 2024].shape

(38, 32)

In [27]:
for col in ['dem_inc', 'rep_inc']:
    mdata[col] = mdata[col].map(lambda x: ast.literal_eval(x))
mdata['dem_inc_any'] = mdata['dem_inc'].map(lambda x: x if not isinstance(x, list) else (True if True in x else False))
mdata['rep_inc_any'] = mdata['rep_inc'].map(lambda x: x if not isinstance(x, list) else (True if True in x else False))

In [28]:
mdata['dem_inc_dummy'] = mdata['dem_inc_any'].map(lambda x: 1 if x == True else 0)
mdata['rep_inc_dummy'] = mdata['rep_inc_any'].map(lambda x: 1 if x == True else 0)

In [29]:
mdata = mdata[mdata['state_po'] != 'DC']

In [30]:
mdata['pvi'] = mdata['prev_lean'] * 0.75 + mdata['prev2_lean'] * 0.25
mdata.head()

,year,state,state_po,special,district,dem,rep,totalvotes,dem_cand,rep_cand,...,ics,pres_approval_avg_x_incpres,ics_x_incpres,no_dem_cand_flag,no_rep_cand_flag,dem_inc_any,rep_inc_any,dem_inc_dummy,rep_inc_dummy,pvi
0,2018,Alabama,AL,False,AL-01,89226.0,153228.0,242617,Robert Kennedy Jr,Bradley Byrne,...,97.5,10.073704,-97.5,False,False,False,True,0,1,-15.715056
1,2018,Alabama,AL,False,AL-02,86931.0,138879.0,226230,Tabitha Isner,Martha Roby,...,97.5,10.073704,-97.5,False,False,False,True,0,1,-16.880853
2,2018,Alabama,AL,False,AL-03,83996.0,147770.0,231915,Mallory Hagan,Mike Rogers,...,97.5,10.073704,-97.5,False,False,False,True,0,1,-17.206974
3,2018,Alabama,AL,False,AL-04,46492.0,184255.0,230969,Lee Auman,Robert Aderholt,...,97.5,10.073704,-97.5,False,False,False,True,0,1,-31.882701
4,2018,Alabama,AL,False,AL-05,101388.0,159063.0,260673,Peter Joffrion,Mo Brooks,...,97.5,10.073704,-97.5,False,False,False,True,0,1,-18.025364

In [31]:
mdata.shape

(1545, 37)

In [32]:
data[data['state_po'] == 'ND']

,year,state,state_po,special,district,dem,rep,totalvotes,dem_cand,rep_cand,...,dem_funds,rep_funds,2party_votes,dem_pct_2p,rep_pct_2p,dem_tot_funds,rep_tot_funds,tot_funds,dem_funds_2p_pct,rep_funds_2p_pct
292,2018,North Dakota,ND,False,0,114377.0,193568.0,321532,Mac Schneider,Kelly Armstrong,...,635380.72,984322.13,307945.0,37.142022,62.857978,635380.72,984322.13,1619702.85,39.228228,60.771772
725,2020,North Dakota,ND,False,0,97970.0,245229.0,355598,Zach Raknerud,Kelly Armstrong,...,23980.09,441057.19,343199.0,28.546120,71.453880,23980.09,441057.19,465037.28,5.156595,94.843405
1154,2022,North Dakota,ND,False,0,89644.0,148399.0,238586,Cara Mund,Kelly Armstrong,...,172945.23,757821.79,238043.0,37.658742,62.341258,172945.23,757821.79,930767.02,18.580937,81.419063
1590,2024,North Dakota,ND,False,0,109231.0,249101.0,359787,Trygve Hammer,Julie Fedorchak,...,1161589.67,1331059.57,358332.0,30.483183,69.516817,1161589.67,1331059.57,2492649.24,46.600607,53.399393

In [33]:
mdata.to_csv('transformed/all_2p_house_races_trainset.csv')