In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
import geopandas as gpd
import maup

In [6]:
urb = pd.read_csv('../../2026_data/urban_rural_demo/DECENNIALDHC2020.P2-Data.csv')
urb.columns = urb.iloc[0]
urb = urb.iloc[1:]
urb.head()

,Geography,Geographic Area Name,!!Total:,!!Total:!!Urban,!!Total:!!Rural,!!Total:!!Not defined for this file,NaN
1,1000000US010010201001000,"Block 1000, Block Group 1, Census Tract 201, A...",21,21,0,0,NaN
2,1000000US010010201001001,"Block 1001, Block Group 1, Census Tract 201, A...",34,34,0,0,NaN
3,1000000US010010201001002,"Block 1002, Block Group 1, Census Tract 201, A...",29,0,29,0,NaN
4,1000000US010010201001003,"Block 1003, Block Group 1, Census Tract 201, A...",17,0,17,0,NaN
5,1000000US010010201001004,"Block 1004, Block Group 1, Census Tract 201, A...",0,0,0,0,NaN

In [14]:
assn_sheet = pd.DataFrame()

for st in ['AL', 'CA', 'FL', 'LA', 'MO', 'NC', 'OH', 'TN', 'TX', 'UT']:
    cong = pd.read_csv(f'../../2026_data/cong_block_assgns/{st}-2026-Congressional-block-assignments.csv')
    cong['state_po'] = np.full(cong.shape[0], st)
    cong = cong.rename({'District': 'seat_number'}, axis=1)
    cong['district'] = cong['state_po'] + '-' + cong['seat_number'].map(lambda x: f'0{x}' if x < 10 else str(x))
    assn_sheet = pd.concat([assn_sheet, cong], axis=0)

assn_sheet.head()

          GEOID20  seat_number state_po district
0  10010210001000            6       AL    AL-06
1  10010210001001            6       AL    AL-06
2  10010210001002            6       AL    AL-06
3  10010210001003            6       AL    AL-06
4  10010210001004            6       AL    AL-06

In [9]:
blocks.shape

(2925018, 18)