In [66]:
import warnings
warnings.filterwarnings('ignore')

In [67]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from rapidfuzz import fuzz, process

In [68]:
url = "https://www.nytimes.com/newsgraphics/polls/house.csv"
polls = pd.read_csv(url)
polls.to_csv('../../2026_data/polls/house.csv')
polls = polls[
    (polls['state'] != 'US') &
    (polls['stage'] == 'general')
]
polls.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,methodology,transparency_score,state,start_date,end_date,sponsor_candidate_id,sponsor_candidate,sponsor_candidate_party,question_id,sample_size,population,subpopulation,population_full,tracking,created_at,notes,url,url_article,url_topline,url_crosstab,source,internal,partisan,cycle,office_type,seat_name,seat_number,election_date,stage,party,pct,answer,candidate_name,candidate_id,race_id,ranked_choice_round,ranked_choice_reallocated,ranked_choice_final,nationwide_match,hypothetical
0,77a55ff9-7bef-44ba-8c0b-04c4835acaa9,9b245451-0334-4f8c-909e-b48d602feb76,Public Policy Polling,20c85a44-ad67-4d54-82bd-b78cdcaf9ad8,House Majority PAC,Public Policy Polling,263.0,Public Policy Polling,NaN,NaN,NaN,NaN,FL,10/21/26,10/22/26,NaN,NaN,NaN,1b89c662-4963-4fa4-af04-1c77d3fec7e2,592.0,lv,NaN,lv,NaN,10/22/26 15:36,NaN,https://x.com/cjwarnke/status/2113306495571894...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Twenty-fifth Congressional District,25.0,2026-11-03,general,REP,42.0,Singer,Scott Singer,6046a5c2-7f29-4a94-b9e3-a8da5f2fc488,5363fdfe-9699-4e1a-aa3d-61394471f296,NaN,False,False,NaN,NaN
1,77a55ff9-7bef-44ba-8c0b-04c4835acaa9,9b245451-0334-4f8c-909e-b48d602feb76,Public Policy Polling,20c85a44-ad67-4d54-82bd-b78cdcaf9ad8,House Majority PAC,Public Policy Polling,263.0,Public Policy Polling,NaN,NaN,NaN,NaN,FL,10/21/26,10/22/26,NaN,NaN,NaN,1b89c662-4963-4fa4-af04-1c77d3fec7e2,592.0,lv,NaN,lv,NaN,10/22/26 15:36,NaN,https://x.com/cjwarnke/status/2113306495571894...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Twenty-fifth Congressional District,25.0,2026-11-03,general,DEM,47.0,Moskowitz,Jared Moskowitz,cea39724-96ed-455b-b7bf-7cefab22a48b,5363fdfe-9699-4e1a-aa3d-61394471f296,NaN,False,False,NaN,NaN
2,99f1022c-3721-4de0-bd2b-95c577810cf4,515110ac-affe-4b0c-a37c-3fb9aad38004,Global Strategy Group,NaN,NaN,Global Strategy Group,118.0,Global Strategy Group,NaN,NaN,NaN,NaN,CO,10/14/26,10/18/26,NaN,Jessica Killin,DEM,d6987225-dcda-4322-bb62-ef6358209c90,500.0,lv,NaN,lv,NaN,10/22/26 12:28,NaN,https://coloradosun.com/2026/10/22/jessica-kil...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Fifth Congressional District,5.0,2026-11-03,general,REP,44.0,Republican,Generic Republican,97a3a951-7de9-49d7-b305-e6f1797d0217,7465714e-dca1-4566-b075-3196f87d733b,NaN,False,False,NaN,NaN
3,99f1022c-3721-4de0-bd2b-95c577810cf4,515110ac-affe-4b0c-a37c-3fb9aad38004,Global Strategy Group,NaN,NaN,Global Strategy Group,118.0,Global Strategy Group,NaN,NaN,NaN,NaN,CO,10/14/26,10/18/26,NaN,Jessica Killin,DEM,d6987225-dcda-4322-bb62-ef6358209c90,500.0,lv,NaN,lv,NaN,10/22/26 12:28,NaN,https://coloradosun.com/2026/10/22/jessica-kil...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Fifth Congressional District,5.0,2026-11-03,general,DEM,44.0,Democrat,Generic Democrat,d73e9669-a0c1-41c3-b768-9e0355cf5fec,7465714e-dca1-4566-b075-3196f87d733b,NaN,False,False,NaN,NaN
4,99f1022c-3721-4de0-bd2b-95c577810cf4,515110ac-affe-4b0c-a37c-3fb9aad38004,Global Strategy Group,NaN,NaN,Global Strategy Group,118.0,Global Strategy Group,NaN,NaN,NaN,NaN,CO,10/14/26,10/18/26,NaN,Jessica Killin,DEM,4a308b92-0f2e-4594-a67d-66104962ea1a,500.0,lv,NaN,lv,NaN,10/22/26 12:28,NaN,https://coloradosun.com/2026/10/22/jessica-kil...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Fifth Congressional District,5.0,2026-11-03,general,LIB,3.0,Elworth,Mark G. Elworth,805d342f-4b76-4339-ac5a-9fdcf7bceff6,7465714e-dca1-4566-b075-3196f87d733b,NaN,False,False,NaN,NaN

In [69]:
pd.set_option('display.max_columns', None)

In [70]:
polls = polls[~((polls['state'] == 'MO') & (pd.to_datetime(polls['start_date']) < pd.to_datetime("2026-09-03")))]

In [71]:
polls_pivot = pd.pivot_table(data=polls, values='pct', index=['poll_id', 'question_id', 'state', 'seat_number'], columns='candidate_name', aggfunc='first')
polls_pivot = polls_pivot.reset_index()
polls_pivot.head()

candidate_name,poll_id,question_id,state,seat_number,Aaron Flint,Aaron Gies,Adam Ortiz,Adonis Hooslyn,Alex Kelloff,Alex Mealer,Amanda Green,Amish Shah,Ammar Campa-Najjar,Andy Harris,Andy Ogles,Angela Gonzales-Torres,Ann Wagner,Anna Paulina Luna,Anthony Constantino,Anthony DiLorenzo,Ashley Bell,Austin Ahlman,Ayden Scott,Bajun Mavalwalla,Bale Dalton,Becca Balint,Belinda Keiser,Ben Cline,Ben McAdams,Beth Macy,Bill Hill,Bill Huizenga,Bill Reeside,Blake Gendebien,Blake Moore,Bob Brooks,Bob Harvie,Bobby Pulido,Brad Finstad,Brad Smith,Brandon Herrera,Brendan Gomez,Brennan Barrington,Brent Taylor,Brian Fitzpatrick,Brian Jack,Brian Mast,Brian Miller,Brian Poindexter,Brice Barnes,Bridget Brink,Brinker Harding,Bryan Steil,Cait Conley,Caitlin Rourk,Carlos De La Cruz,Carlton Bowen,Carmela Conroy,Casey Askar,Cassie Easley,Celeste Maloy,Charlie Hatcher,Chaz Molder,Chellie Pingree,Cherlynn Stevenson,Chris Backemeyer,Chris Gallant,Chris Getty,Chris Gober,Chris Harden,Chris Jones,Chris Royal,Chris Schmidt,Christina Bohannan,Christina Hines,Christopher Mitchell,Clay Strickland,Connie Chan,Cooke Harvey,Cory Mills,Curtis Goodwin,Dan Green,Dan Schwartz,Daniel Cottam,Darrell Issa,Darren Soto,David Flippo,David G. Valadao,David Gedert,David Rouzer,David Womack,Denise Powell,Derek Merrin,Derrick Van Orden,Don Davis,Don Leonard,Don't know,Don't know/Someone else,Don't know/Would not vote,Doris Matsui,Douglas Mangeris,Dwayne Romero,Ed Hershey,Eddie Espinoza,Eileen Laubacher,Elaine G. Luria,Eli Crane,Elias Montgomery,Eliott Rodriguez,Eric Chung,Eric Conroy,Eric Flores,Eric Hafner,Eric Michael Foreman,Eric Pratt,Esther Kim-Varet,Fred Wellman,French Hill,Gabe Amo,Gabe Evans,Gabriel Vasquez,Generic Candidate,Generic Democrat,Generic Libertarian,Generic Republican,George Moraitis,Gerald Malloy,Gina Swoboda,Glenn Grothman,Greg Cunningham,Greg Landsman,Greg Murphy,Henry Cuellar,J.D. Ford,Jackie Auringer,Jake Johnson,James Johnson,James Martin,James Pericola,Jamie Ager,Janelle Stelson,Jared Golden,Jared Moskowitz,Jay Bowman,Jay Feely,Jeff Crank,Jeff Hurd,Jeff Van Drew,Jen Kiggans,Jena Nelson,Jennifer Balkcom,Jennifer Jenkins,Jennifer Konfrst,Jenny Costa Honeycutt,Jesse West,Jessica Killin,Jim C. McDermott,Jim Desmond,Jimmy Gomez,JoAnna Mendoza,Joe Baldacci,Joe Mitchell,Joe Strada,John Braun,John Cavanaugh,John Cowan,John McGuire,John Vincent,John Williams,Johnny Garcia,Jonathan Nez,Jonny Larsen,Jordan Wood,Juan Ciscomani,Justin Pearson,Kaela Berg,Kathy Castor,Katy Padilla Stout,Kaylee Peterson,Keith Gross,Kellie Keenan,Kelly Kirschner,Ken Calvert,Kent Udell,Kevin Kiley,Kevin Steele,Kimberly Hardy,Kristina Knickerbocker,LaKesha Womack,Lauren Boebert,Laurie Buckhout,Leela Gray,Leticia Gutierrez,Lily Tang Williams,Lindsay James,Lupe Castillo,Lynn Chapman,Maad Abu-Ghazalah,Mac Deford,Maggie Goodlander,Mai Vang,Manny Rutinel,Marcy Kaptur,Margo Ellis,Mariannette Miller-Meeks,Marie Gluesenkamp Perez,Mark Coester,Mark G. Elworth,Mark Smith,Marlon Duran,Marni von Wilpert,Martin Ruben Zamora,Marty Jackley,Mary Peltola,María Elvira Salazar,Matt Cavanaugh,Matt Dunlap,Matt Klein,Matt Little,Matt Maasdam,Matt Rains,Matt Schultz,Maura Keller,Max Miller,Melanie Ann Stansbury,Michael Baumgartner,Michael Bridgford,Michael Eisenhauer,Michael Stoddard,Michael Thurow,Micheál O'Leary,Mike Beltran,Mike Bouchard,Mike Carey,Mike Flood,Mike Haridopolos,Mike Kennedy,Mike Lawler,Mike Turner,Mitchell Berman,Monica De La Cruz,Nancy Lacore,Nancy Pelosi,Nate Powell,Nathan Weise,Ndidiamaka Okpareke,Neither,Nicholas J. LaLota,Nicholas Zateslo,Nick Begich,Nick Langworthy,Nick Sheedy,Nikki Gronli,None/other,Oliver Larkin,Other named candidates,Paige Cognetti,Pat Harrigan,Pat Ryan,Patrick McCracken,Patty Garcia,Paul LePage,Pedro DeSouza,Pete Lynch,Peter Crosby,Phoenix Altair,Pia Dandiya,Ralph Alvarado,Randy Villegas,Raymond Smith Jr.,Rebecca Bennett,Rebecca Cooke,Rhett Marques,Rich McCormick,Richard Hudson,Richard Ojeda,Richard Pan,Riley Owen,Rob Bresnahan Jr.,Robbie Mahrou,Robert Moesinger,Robert Wittman,Ronald Russell,Russ Fulcher,Russell Fry,Ryan Busse,Ryan Dotson,Ryan E. Mackenzie,Ryan Elijah,Ryan Walton,Ryan Zinke,Saikat Chakrabarti,Sam Forstag,Sarah Trone Garriott,Sarah Zabel,Scott Perry,Scott Singer,Scott Wiener,Seamus O'Toole,Sean McCann,Seth M. Magaziner,Shannon Taylor,Shaun Finnie,Shomari Figures,Someone else,Stefany Shaheen,Stephanie Bice,Steve Toth,Steven Burt,Suzanne Seymour,Sydney Gruters,Tano Tijerina,Taylor Wright,Teresa Benitez-Thompson,Teresa Leger Fernandez,Thomas Aaron Bailey,Thomas H. Kean Jr.,Thomas McMasters,Tim Greimel,Tim Moore,Tim Sheehy,Tina Shah,Tom Barrett,Tom Perriello,Tony D’Arrigo,Tony Kozycki,Troy Downing,Vicente Gonzalez,Victor Mellor,Victoria Spartz,William Lawrence,Would not vote,Yen Bailey,Young Kim,Zach Dembo,Zach Nunn
0,003fc85c-bf21-4fad-8364-0b8617e82a84,4399594d-e5e0-4802-94ff-4a55dd92bd5b,MT,1.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,016369fb-4a26-42ad-a583-39067289cab2,65c0d75b-5121-4107-b61a-95b2534fab6e,WI,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0208a971-f1c8-4f04-aae8-2acbc265a583,5ab93d8c-0f9c-42c9-963c-a23e40a5e9b4,NH,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,020ba7d5-94fe-4ecd-afb3-e73e1dcc28c5,819e8638-6f1a-419f-a796-0c2541db60f9,MN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0245de88-747f-4893-9c92-fd35eb70f977,73e8c905-d20f-4d20-85d2-8150cf0e2551,MT,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
polls_pivot.shape

(429, 336)

In [73]:
candinfo_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQZC7cVru6ltLR2e8XN5jdJPfxfj42BAxUApe3Zq3_ENQjLtYntmAxD0pIHqEUJ4ZFLXlybKJdkLf2r/pub?output=csv'
candinfo = pd.read_csv(candinfo_url)

In [74]:
dem_uncont = candinfo[candinfo['rep_cand'] == 'Not Contested']
rep_uncont = candinfo[candinfo['dem_cand'] == 'Not Contested']
candinfo = candinfo[(candinfo['dem_cand'] != 'Not Contested') &
    (candinfo['rep_cand'] != 'Not Contested')]
candinfo['state_po'] = candinfo['cd'].map(lambda x: x[:2]).astype(str)
candinfo['district_number'] = candinfo['cd'].map(lambda x: 0 if x[3:] == 'AL' else int(x[3:]))
candinfo.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number
0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0
1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1
2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2
3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3
4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4

In [75]:
dem_uncont.shape, rep_uncont.shape

((16, 5), (1, 5))

In [76]:
polled_cands = polls_pivot.columns.values[4:]
running_dems = np.unique(candinfo['dem_cand'].astype(str))
running_reps = np.unique(candinfo['rep_cand'].astype(str))
all_running_cands = np.concatenate([running_dems, running_reps])

In [77]:
hypo_cands = []
for c in polled_cands:
    fuzzymatch = process.extractOne(c, all_running_cands, scorer=fuzz.token_sort_ratio, score_cutoff=80)
    if fuzzymatch is None:
        hypo_cands.append(c)

In [78]:
for h in hypo_cands:
    if h in ['Nicholas J. LaLota', 'Robert J. Wittman', 'Thomas H. Kean',
 'Thomas H. Kean Jr.', "Don't know",
 "Don't know/Someone else",
 "Don't know/Would not vote", 'Someone else', 'Would not vote']:
        continue
    # print(h, polls_pivot["Christina Bohannan"].isna().all())
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

for h in ['John Williams']: # names that weren't caught in hypo_cands but should've been
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

In [79]:
polls_pivot.columns.values

array(['poll_id', 'question_id', 'state', 'seat_number', 'Aaron Flint',
       'Aaron Gies', 'Alex Mealer', 'Amanda Green', 'Amish Shah',
       'Andy Harris', 'Ann Wagner', 'Anna Paulina Luna',
       'Anthony Constantino', 'Anthony DiLorenzo', 'Ashley Bell',
       'Bale Dalton', 'Becca Balint', 'Ben Cline', 'Ben McAdams',
       'Beth Macy', 'Bill Hill', 'Bill Huizenga', 'Blake Gendebien',
       'Blake Moore', 'Bob Brooks', 'Bob Harvie', 'Bobby Pulido',
       'Brad Finstad', 'Brad Smith', 'Brandon Herrera', 'Brent Taylor',
       'Brian Fitzpatrick', 'Brian Jack', 'Brian Mast', 'Brian Miller',
       'Brian Poindexter', 'Brinker Harding', 'Bryan Steil',
       'Cait Conley', 'Caitlin Rourk', 'Carlos De La Cruz',
       'Carmela Conroy', 'Casey Askar', 'Celeste Maloy',
       'Charlie Hatcher', 'Chaz Molder', 'Chellie Pingree',
       'Chris Backemeyer', 'Chris Gallant', 'Chris Gober', 'Chris Harden',
       'Chris Jones', 'Chris Schmidt', 'Christina Bohannan',
       'Christina Hines', 'Dan Green', 'Dan Schwartz', 'Darren Soto',
       'David Flippo', 'David G. Valadao', 'David Rouzer',
       'Denise Powell', 'Derek Merrin', 'Derrick Van Orden', 'Don Davis',
       'Don Leonard', "Don't know", "Don't know/Someone else",
       "Don't know/Would not vote", 'Dwayne Romero', 'Eileen Laubacher',
       'Elaine G. Luria', 'Eli Crane', 'Eliott Rodriguez', 'Eric Chung',
       'Eric Conroy', 'Eric Flores', 'Eric Pratt', 'Fred Wellman',
       'French Hill', 'Gabe Amo', 'Gabe Evans', 'Gabriel Vasquez',
       'Glenn Grothman', 'Greg Cunningham', 'Greg Landsman',
       'Greg Murphy', 'Henry Cuellar', 'J.D. Ford', 'Jackie Auringer',
       'Jake Johnson', 'James Johnson', 'James Martin', 'James Pericola',
       'Jamie Ager', 'Janelle Stelson', 'Jared Moskowitz', 'Jay Feely',
       'Jeff Crank', 'Jeff Hurd', 'Jeff Van Drew', 'Jen Kiggans',
       'Jena Nelson', 'Jennifer Balkcom', 'Jennifer Jenkins',
       'Jenny Costa Honeycutt', 'Jessica Killin', 'Jim Desmond',
       'JoAnna Mendoza', 'Joe Mitchell', 'Joe Strada', 'John Braun',
       'John Cowan', 'John McGuire', 'John Vincent', 'Johnny Garcia',
       'Jonathan Nez', 'Jonny Larsen', 'Juan Ciscomani', 'Justin Pearson',
       'Kathy Castor', 'Katy Padilla Stout', 'Kaylee Peterson',
       'Kellie Keenan', 'Kelly Kirschner', 'Kent Udell', 'Kevin Kiley',
       'Kimberly Hardy', 'Kristina Knickerbocker', 'LaKesha Womack',
       'Lauren Boebert', 'Laurie Buckhout', 'Leela Gray',
       'Leticia Gutierrez', 'Lily Tang Williams', 'Lindsay James',
       'Lupe Castillo', 'Maggie Goodlander', 'Manny Rutinel',
       'Marcy Kaptur', 'Mariannette Miller-Meeks',
       'Marie Gluesenkamp Perez', 'Mark Coester', 'Marni von Wilpert',
       'Martin Ruben Zamora', 'Marty Jackley', 'María Elvira Salazar',
       'Matt Dunlap', 'Matt Little', 'Maura Keller', 'Max Miller',
       'Melanie Ann Stansbury', 'Michael Baumgartner', 'Mike Beltran',
       'Mike Bouchard', 'Mike Carey', 'Mike Flood', 'Mike Haridopolos',
       'Mike Kennedy', 'Mike Lawler', 'Mike Turner', 'Mitchell Berman',
       'Monica De La Cruz', 'Nancy Lacore', 'Nicholas J. LaLota',
       'Nick Begich', 'Nick Langworthy', 'Nikki Gronli', 'Paige Cognetti',
       'Pat Harrigan', 'Pat Ryan', 'Patty Garcia', 'Paul LePage',
       'Peter Crosby', 'Pia Dandiya', 'Ralph Alvarado', 'Randy Villegas',
       'Raymond Smith Jr.', 'Rebecca Bennett', 'Rebecca Cooke',
       'Rhett Marques', 'Rich McCormick', 'Richard Hudson',
       'Richard Ojeda', 'Richard Pan', 'Riley Owen', 'Rob Bresnahan Jr.',
       'Robert Wittman', 'Ronald Russell', 'Russ Fulcher', 'Russell Fry',
       'Ryan E. Mackenzie', 'Ryan Elijah', 'Sam Forstag',
       'Sarah Trone Garriott', 'Scott Perry', 'Scott Singer',
       'Scott Wiener', 'Sean McCann', 'Seth M. Magaziner',
       'Shannon Taylor', 'Shaun Finnie', 'Shomari Figures',
       'Someone else', 'Stefany Shaheen', 'Stephanie Bice', 'Steve Toth',
       'Sydney Gruters', 'Tano Tijerina', 'Teresa Benitez-Thompson',
       'Teresa Leger Fernandez', 'Thomas H. Kean Jr.', 'Tim Moore',
       'Tom Barrett', 'Tom Perriello', 'Tony Kozycki', 'Troy Downing',
       'Vicente Gonzalez', 'Victor Mellor', 'Victoria Spartz',
       'William Lawrence', 'Would not vote', 'Zach Dembo', 'Zach Nunn'],
      dtype=object)

In [80]:
polls_pivot.shape

(229, 224)

In [81]:
rel_polls = polls[(polls['poll_id'].isin(np.unique(polls_pivot['poll_id']))) &
    (polls['question_id'].isin(np.unique(polls_pivot['question_id'])))]

In [82]:
np.unique(rel_polls['candidate_name'])

array(['Aaron Flint', 'Aaron Gies', 'Alex Mealer', 'Amish Shah',
       'Andy Harris', 'Ann Wagner', 'Anna Paulina Luna',
       'Anthony Constantino', 'Anthony DiLorenzo', 'Ashley Bell',
       'Bale Dalton', 'Ben Cline', 'Beth Macy', 'Bill Hill',
       'Bill Huizenga', 'Blake Gendebien', 'Bob Brooks', 'Bob Harvie',
       'Bobby Pulido', 'Brad Finstad', 'Brad Smith', 'Brandon Herrera',
       'Brent Taylor', 'Brian Fitzpatrick', 'Brian Jack', 'Brian Mast',
       'Brian Poindexter', 'Brinker Harding', 'Bryan Steil',
       'Cait Conley', 'Caitlin Rourk', 'Carlos De La Cruz',
       'Carmela Conroy', 'Casey Askar', 'Charlie Hatcher', 'Chaz Molder',
       'Chellie Pingree', 'Chris Backemeyer', 'Chris Gallant',
       'Chris Gober', 'Chris Harden', 'Chris Jones', 'Chris Schmidt',
       'Christina Bohannan', 'Christina Hines', 'Dan Green',
       'Dan Schwartz', 'Darren Soto', 'David Flippo', 'David G. Valadao',
       'David Rouzer', 'Denise Powell', 'Derek Merrin',
       'Derrick Van Orden', 'Don Davis', 'Don Leonard', "Don't know",
       "Don't know/Would not vote", 'Dwayne Romero', 'Elaine G. Luria',
       'Eli Crane', 'Eliott Rodriguez', 'Eric Chung', 'Eric Conroy',
       'Eric Flores', 'Eric Pratt', 'Fred Wellman', 'French Hill',
       'Gabe Evans', 'Gabriel Vasquez', 'Glenn Grothman',
       'Greg Cunningham', 'Greg Landsman', 'Greg Murphy', 'Henry Cuellar',
       'J.D. Ford', 'Jackie Auringer', 'Jake Johnson', 'James Martin',
       'James Pericola', 'Jamie Ager', 'Janelle Stelson',
       'Jared Moskowitz', 'Jay Feely', 'Jeff Crank', 'Jeff Hurd',
       'Jen Kiggans', 'Jena Nelson', 'Jennifer Balkcom',
       'Jennifer Jenkins', 'Jenny Costa Honeycutt', 'Jessica Killin',
       'Jim Desmond', 'JoAnna Mendoza', 'Joe Mitchell', 'Joe Strada',
       'John Braun', 'John Cowan', 'John McGuire', 'John Vincent',
       'Johnny Garcia', 'Jonathan Nez', 'Juan Ciscomani',
       'Justin Pearson', 'Kathy Castor', 'Katy Padilla Stout',
       'Kelly Kirschner', 'Kevin Kiley', 'Kimberly Hardy',
       'Kristina Knickerbocker', 'LaKesha Womack', 'Laurie Buckhout',
       'Leela Gray', 'Leticia Gutierrez', 'Lily Tang Williams',
       'Lindsay James', 'Maggie Goodlander', 'Manny Rutinel',
       'Marcy Kaptur', 'Mariannette Miller-Meeks',
       'Marie Gluesenkamp Perez', 'Marni von Wilpert',
       'Martin Ruben Zamora', 'Marty Jackley', 'María Elvira Salazar',
       'Matt Dunlap', 'Matt Little', 'Maura Keller', 'Max Miller',
       'Michael Baumgartner', 'Mike Beltran', 'Mike Bouchard',
       'Mike Carey', 'Mike Flood', 'Mike Haridopolos', 'Mike Lawler',
       'Mike Turner', 'Mitchell Berman', 'Monica De La Cruz',
       'Nancy Lacore', 'Nicholas J. LaLota', 'Nick Begich',
       'Nick Langworthy', 'Nikki Gronli', 'Paige Cognetti',
       'Pat Harrigan', 'Pat Ryan', 'Paul LePage', 'Pia Dandiya',
       'Ralph Alvarado', 'Randy Villegas', 'Raymond Smith Jr.',
       'Rebecca Bennett', 'Rebecca Cooke', 'Rhett Marques',
       'Rich McCormick', 'Richard Hudson', 'Richard Ojeda', 'Richard Pan',
       'Rob Bresnahan Jr.', 'Robert Wittman', 'Ronald Russell',
       'Russell Fry', 'Ryan E. Mackenzie', 'Ryan Elijah', 'Sam Forstag',
       'Sarah Trone Garriott', 'Scott Perry', 'Scott Singer',
       'Sean McCann', 'Seth M. Magaziner', 'Shannon Taylor',
       'Shaun Finnie', 'Shomari Figures', 'Someone else',
       'Stefany Shaheen', 'Stephanie Bice', 'Steve Toth',
       'Sydney Gruters', 'Tano Tijerina', 'Teresa Benitez-Thompson',
       'Teresa Leger Fernandez', 'Thomas H. Kean Jr.', 'Tim Moore',
       'Tom Barrett', 'Tom Perriello', 'Tony Kozycki', 'Vicente Gonzalez',
       'Victor Mellor', 'Victoria Spartz', 'William Lawrence',
       'Would not vote', 'Zach Dembo', 'Zach Nunn'], dtype=object)

In [83]:
rel_polls.shape

(604, 50)

In [84]:
rel_polls.to_csv('transformed/relevent_house_polls.csv')