In [222]:
import warnings
warnings.filterwarnings('ignore')

In [223]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from rapidfuzz import fuzz, process

In [224]:
url = "https://www.nytimes.com/newsgraphics/polls/house.csv"
polls = pd.read_csv(url)
polls.to_csv('../../2026_data/polls/house.csv')
polls = polls[
    (polls['state'] != 'US') &
    (polls['stage'] == 'general')
]
polls.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,methodology,transparency_score,state,start_date,end_date,sponsor_candidate_id,sponsor_candidate,sponsor_candidate_party,question_id,sample_size,population,subpopulation,population_full,tracking,created_at,notes,url,url_article,url_topline,url_crosstab,source,internal,partisan,cycle,office_type,seat_name,seat_number,election_date,stage,party,pct,answer,candidate_name,candidate_id,race_id,nationwide_match,ranked_choice_reallocated,hypothetical
10,3c5c743c-3463-46e1-9458-155142adf214,a64a876e-bc33-45b8-b3d1-86ae963bfa7d,GQR,NaN,NaN,GQR,126.0,GQR,NaN,NaN,Live Phone,NaN,NC,6/22/26,6/28/26,NaN,Don Davis,DEM,34c68db7-73e5-44e1-b40a-1a01a75d6d21,500.0,lv,NaN,lv,NaN,7/1/26 16:30,NaN,https://x.com/nicholaswu12/status/207238384100...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,First Congressional District,1.0,2026-11-03,general,NONE,8.0,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,814ce247-ec2e-47c3-8d53-de7470be442e,NaN,NaN,NaN
11,3c5c743c-3463-46e1-9458-155142adf214,a64a876e-bc33-45b8-b3d1-86ae963bfa7d,GQR,NaN,NaN,GQR,126.0,GQR,NaN,NaN,Live Phone,NaN,NC,6/22/26,6/28/26,NaN,Don Davis,DEM,34c68db7-73e5-44e1-b40a-1a01a75d6d21,500.0,lv,NaN,lv,NaN,7/1/26 16:30,NaN,https://x.com/nicholaswu12/status/207238384100...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,First Congressional District,1.0,2026-11-03,general,REP,41.0,Buckhout,Laurie Buckhout,8ac75369-3dc0-44b9-80ce-66f451e27d78,814ce247-ec2e-47c3-8d53-de7470be442e,NaN,NaN,NaN
12,3c5c743c-3463-46e1-9458-155142adf214,a64a876e-bc33-45b8-b3d1-86ae963bfa7d,GQR,NaN,NaN,GQR,126.0,GQR,NaN,NaN,Live Phone,NaN,NC,6/22/26,6/28/26,NaN,Don Davis,DEM,34c68db7-73e5-44e1-b40a-1a01a75d6d21,500.0,lv,NaN,lv,NaN,7/1/26 16:30,NaN,https://x.com/nicholaswu12/status/207238384100...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,First Congressional District,1.0,2026-11-03,general,DEM,45.0,Davis,Don Davis,5096a761-bd50-46fc-a0ca-624ace2b8faf,814ce247-ec2e-47c3-8d53-de7470be442e,NaN,NaN,NaN
13,85260468-cf88-4a08-926d-b0e7174754f9,4441d98f-cf28-4bb7-957a-5ff6dd310ef8,Pulse Decision Science,NaN,NaN,Pulse Decision Science,NaN,NaN,NaN,NaN,NaN,NaN,TX,6/21/26,6/23/26,NaN,Tano Tijerina,REP,fcd800b2-3a7f-40a5-b8af-ee5d599b8336,400.0,lv,NaN,lv,NaN,7/1/26 13:29,NaN,https://x.com/birenbomb/status/207235448964294...,NaN,NaN,NaN,NaN,NaN,REP,2026,U.S. House,Twenty-eighth Congressional District,28.0,2026-11-03,general,NONE,16.0,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,4cc4cc40-257f-4221-869e-57150dfd388d,NaN,NaN,NaN
14,85260468-cf88-4a08-926d-b0e7174754f9,4441d98f-cf28-4bb7-957a-5ff6dd310ef8,Pulse Decision Science,NaN,NaN,Pulse Decision Science,NaN,NaN,NaN,NaN,NaN,NaN,TX,6/21/26,6/23/26,NaN,Tano Tijerina,REP,fcd800b2-3a7f-40a5-b8af-ee5d599b8336,400.0,lv,NaN,lv,NaN,7/1/26 13:29,NaN,https://x.com/birenbomb/status/207235448964294...,NaN,NaN,NaN,NaN,NaN,REP,2026,U.S. House,Twenty-eighth Congressional District,28.0,2026-11-03,general,NONE,9.0,Other candidates,Other named candidates,0dffd971-ad4a-46a9-bc54-c7711ef0cf33,4cc4cc40-257f-4221-869e-57150dfd388d,NaN,NaN,NaN

In [225]:
pd.set_option('display.max_columns', None)

In [226]:
polls_pivot = pd.pivot_table(data=polls, values='pct', index=['poll_id', 'question_id', 'state', 'seat_number'], columns='candidate_name', aggfunc='first')
polls_pivot = polls_pivot.reset_index()
polls_pivot.head()

candidate_name,poll_id,question_id,state,seat_number,Aaron Flint,Adam Ortiz,Alex Kelloff,Alexander Fornino,Ammar Campa-Najjar,Andy Ogles,Ann Wagner,Anna Paulina Luna,Anthony Constantino,Ashley Bell,Austin Ahlman,Bajun Mavalwalla,Bale Dalton,Becca Balint,Bill Hill,Bill Huizenga,Blake Gendebien,Bob Harvie,Bobby Pulido,Brad Finstad,Brad Smith,Brandon Herrera,Brian Fitzpatrick,Brian Poindexter,Bridget Brink,Bryan Steil,Carlos A. Gimenez,Carmela Conroy,Chaz Molder,Cherlynn Stevenson,Chris Backemeyer,Chris Gallant,Christina Bohannan,Christina Hines,Cory Mills,Curtis Goodwin,Daniella Levine Cava,Darrell Issa,David G. Valadao,David Gedert,David Womack,Denise Powell,Derek Merrin,Derrick Van Orden,Don Davis,Don't know,Don't know/Someone else,Don't know/Would not vote,Eli Crane,Eliott Rodriguez,Eric Chung,Eric Flores,Esther Kim-Varet,Fred Wellman,Gabe Vasquez,Generic Democrat,Generic Republican,Gerald Malloy,Gina Swoboda,Glenn Grothman,Greg Cunningham,Hector Mujica,Heidi Hall,Henry Cuellar,Jake Johnson,Janelle Stelson,Jared Forrest Golden,Jasmeet Bains,Jeff Crank,Jeff Hurd,Jeff Van Drew,Jennifer Konfrst,Jessica Killin,JoAnna Mendoza,Joe Baldacci,Joe Mitchell,John Braun,John Cavanaugh,John Williams,Jonathan Nez,Jordan Wood,Juan Ciscomani,Katy Padilla Stout,Ken Calvert,Kevin Kiley,LaKesha Womack,Laurie Buckhout,Leela Gray,Lily Tang Williams,Lindsay James,Mac Deford,Maggie Goodlander,Marcy Kaptur,Mariannette Miller-Meeks,Marie Gluesenkamp Perez,Mark Coester,Mark Smith,Mary S. Peltola,María Elvira Salazar,Matt Cavanaugh,Matt Dunlap,Matt Maasdam,Matt Rains,Matt Schultz,Max Miller,Michael Baumgartner,Michael Thurow,Mike Bouchard,Mike Davey,Mike Flood,Mitchell Berman,Monica De La Cruz,Nancy Pelosi,Nate Powell,Neither,Nicholas J. LaLota,Nick Begich,Other named candidates,Paige Cognetti,Pat Harrigan,Paul R. LePage,Ralph Alvarado,Rebecca Bennett,Rebecca Cooke,Richard Lamondin,Rob Bresnahan Jr.,Robert J. Wittman,Robin Peguero,Ryan Busse,Ryan Dotson,Ryan K. Zinke,Saikat Chakrabarti,Sam Forstag,Sarah Trone Garriott,Scott Perry,Sean McCann,Shannon Taylor,Someone else,Tano Tijerina,Thomas (Jay) Feely,Thomas Aaron Bailey,Thomas H. Kean,Thomas H. Kean Jr.,Tim Greimel,Tim Moore,Tim Sheehy,Tina Shah,Tom Barrett,Vicente Gonzalez,Would not vote,Young Kim,Zach Dembo,Zach Nunn
0,0208a971-f1c8-4f04-aae8-2acbc265a583,5ab93d8c-0f9c-42c9-963c-a23e40a5e9b4,NH,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0245de88-747f-4893-9c92-fd35eb70f977,73e8c905-d20f-4d20-85d2-8150cf0e2551,MT,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0245de88-747f-4893-9c92-fd35eb70f977,957f3c8e-b3ac-4427-8c46-d0bf1e0df13b,MT,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,06bcf2dd-2622-4984-9d26-992e75d54d69,167a1161-87dc-4101-8558-334cce646f2e,NM,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,06bcf2dd-2622-4984-9d26-992e75d54d69,da8a7298-eab0-4dd5-b659-f7d3d7cd9b83,NM,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [227]:
polls_pivot.shape

(156, 157)

In [228]:
candinfo_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQZC7cVru6ltLR2e8XN5jdJPfxfj42BAxUApe3Zq3_ENQjLtYntmAxD0pIHqEUJ4ZFLXlybKJdkLf2r/pub?output=csv'
candinfo = pd.read_csv(candinfo_url)

In [229]:
candinfo = candinfo[(candinfo['dem_cand'] != 'Not Contested') &
    (candinfo['rep_cand'] != 'Not Contested')]
candinfo['state_po'] = candinfo['cd'].map(lambda x: x[:2]).astype(str)
candinfo['district_number'] = candinfo['cd'].map(lambda x: 0 if x[3:] == 'AL' else int(x[3:]))
candinfo.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number
0,AK-AL,NaN,Nick Begich,False,True,AK,0
1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1
2,AL-02,Shomari Figures,Hampton Harris,True,False,AL,2
3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3
4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4

In [230]:
polled_cands = polls_pivot.columns.values[4:]
running_dems = np.unique(candinfo['dem_cand'].astype(str))
running_reps = np.unique(candinfo['rep_cand'].astype(str))
all_running_cands = np.concatenate([running_dems, running_reps])

In [231]:
hypo_cands = []
for c in polled_cands:
    fuzzymatch = process.extractOne(c, all_running_cands, scorer=fuzz.token_sort_ratio, score_cutoff=80)
    if fuzzymatch is None:
        hypo_cands.append(c)

In [232]:
for h in hypo_cands:
    if h in ['Nicholas J. LaLota', 'Robert J. Wittman', 'Thomas H. Kean',
 'Thomas H. Kean Jr.', "Don't know",
 "Don't know/Someone else",
 "Don't know/Would not vote", 'Someone else', 'Would not vote']:
        continue
    # print(h, polls_pivot["Christina Bohannan"].isna().all())
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

for h in ['John Williams', 'Mike Davey']: # names that weren't caught in hypo_cands but should've been
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

In [233]:
polls_pivot.shape

(43, 90)

In [234]:
rel_polls = polls[(polls['poll_id'].isin(np.unique(polls_pivot['poll_id']))) &
    (polls['question_id'].isin(np.unique(polls_pivot['question_id'])))]

In [235]:
np.unique(rel_polls['candidate_name'])

array(['Aaron Flint', 'Anthony Constantino', 'Ashley Bell',
       'Blake Gendebien', 'Bob Harvie', 'Bobby Pulido', 'Brad Finstad',
       'Brandon Herrera', 'Brian Fitzpatrick', 'Brian Poindexter',
       'Chris Backemeyer', 'Chris Gallant', 'Christina Bohannan',
       'Derrick Van Orden', 'Don Davis', "Don't know",
       "Don't know/Would not vote", 'Eric Flores', 'Gabe Vasquez',
       'Greg Cunningham', 'Henry Cuellar', 'Jake Johnson',
       'Janelle Stelson', 'JoAnna Mendoza', 'Joe Mitchell',
       'Juan Ciscomani', 'Katy Padilla Stout', 'LaKesha Womack',
       'Laurie Buckhout', 'Lily Tang Williams', 'Lindsay James',
       'Maggie Goodlander', 'Mariannette Miller-Meeks', 'Matt Dunlap',
       'Max Miller', 'Mike Flood', 'Monica De La Cruz',
       'Nicholas J. LaLota', 'Paige Cognetti', 'Pat Harrigan',
       'Paul R. LePage', 'Ralph Alvarado', 'Rebecca Bennett',
       'Rebecca Cooke', 'Rob Bresnahan Jr.', 'Sam Forstag',
       'Sarah Trone Garriott', 'Scott Perry', 'Someone else',
       'Tano Tijerina', 'Thomas H. Kean Jr.', 'Tim Moore',
       'Vicente Gonzalez', 'Zach Dembo', 'Zach Nunn'], dtype=object)

In [236]:
rel_polls.shape

(123, 48)

In [237]:
rel_polls.to_csv('transformed/relevent_house_polls.csv')