In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from rapidfuzz import fuzz, process

In [3]:
url = "https://www.nytimes.com/newsgraphics/polls/house.csv"
polls = pd.read_csv(url)
polls.to_csv('../../2026_data/polls/house.csv')
polls = polls[
    (polls['state'] != 'US') &
    (polls['stage'] == 'general')
]
polls.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,...,pct,answer,candidate_name,candidate_id,race_id,ranked_choice_round,ranked_choice_reallocated,ranked_choice_final,nationwide_match,hypothetical
41,bb94417f-3a6e-4bd8-9e2d-29ba8c451b23,8c016954-3c5a-4142-a87a-14bf33fc469c,SurveyUSA,aeecd4a2-1ce8-49f7-87b2-d9aea2ad648b,"Grant Forbes, LLC",SurveyUSA,325.0,SurveyUSA,NaN,NaN,...,9.0,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,4f7e53a6-1e78-4ae8-ad13-c676356569fb,NaN,False,False,NaN,NaN
42,bb94417f-3a6e-4bd8-9e2d-29ba8c451b23,8c016954-3c5a-4142-a87a-14bf33fc469c,SurveyUSA,aeecd4a2-1ce8-49f7-87b2-d9aea2ad648b,"Grant Forbes, LLC",SurveyUSA,325.0,SurveyUSA,NaN,NaN,...,4.0,Someone else,Someone else,d23503df-ca4b-41e0-807f-67f2629609ac,4f7e53a6-1e78-4ae8-ad13-c676356569fb,NaN,False,False,NaN,NaN
43,bb94417f-3a6e-4bd8-9e2d-29ba8c451b23,8c016954-3c5a-4142-a87a-14bf33fc469c,SurveyUSA,aeecd4a2-1ce8-49f7-87b2-d9aea2ad648b,"Grant Forbes, LLC",SurveyUSA,325.0,SurveyUSA,NaN,NaN,...,46.0,Powell,Denise Powell,5e12a989-e28f-4f72-9558-bcd48c3c6f98,4f7e53a6-1e78-4ae8-ad13-c676356569fb,NaN,False,False,NaN,NaN
44,bb94417f-3a6e-4bd8-9e2d-29ba8c451b23,8c016954-3c5a-4142-a87a-14bf33fc469c,SurveyUSA,aeecd4a2-1ce8-49f7-87b2-d9aea2ad648b,"Grant Forbes, LLC",SurveyUSA,325.0,SurveyUSA,NaN,NaN,...,42.0,Harding,Brinker Harding,e6fe54f6-a30d-4935-9738-ba2b43b16c63,4f7e53a6-1e78-4ae8-ad13-c676356569fb,NaN,False,False,NaN,NaN
45,914f7531-147c-48a3-bfd4-d222a420a548,57076f70-6f0c-4473-8f80-0bec6494dcb5,StimSight Research,d7889f83-aaae-425e-852e-24d8e0f13f06,InsiderNJ,StimSight Research,NaN,NaN,NaN,NaN,...,10.0,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,4b0ae732-48b7-4572-a896-107b4fba126b,NaN,False,False,NaN,NaN

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
polls = polls[~((polls['state'] == 'MO') & (pd.to_datetime(polls['start_date']) < pd.to_datetime("2026-09-03")))]

In [6]:
polls_pivot = pd.pivot_table(data=polls, values='pct', index=['poll_id', 'question_id', 'state', 'seat_number'], columns='candidate_name', aggfunc='first')
polls_pivot = polls_pivot.reset_index()
polls_pivot.head()

candidate_name,poll_id,question_id,state,seat_number,Aaron Flint,Adam Ortiz,Alex Kelloff,Alexander Fornino,Amanda Green,Ammar Campa-Najjar,Andy Harris,Andy Ogles,Angela Gonzales-Torres,Anna Paulina Luna,Anthony Constantino,Ashley Bell,Austin Ahlman,Bajun Mavalwalla,Bale Dalton,Becca Balint,Belinda Keiser,Bill Hill,Bill Huizenga,Bill Reeside,Blake Gendebien,Bob Brooks,Bob Harvie,Bobby Pulido,Brad Finstad,Brad Smith,Brandon Herrera,Brendan Gomez,Brennan Barrington,Brent Taylor,Brian Fitzpatrick,Brian Poindexter,Brice Barnes,Bridget Brink,Brinker Harding,Bryan Steil,Cait Conley,Carlos De La Cruz,Carlos Gimenez,Carmela Conroy,Casey Askar,Charlie Hatcher,Chaz Molder,Cherlynn Stevenson,Chris Backemeyer,Chris Gallant,Chris Getty,Chris Jones,Chris Royal,Chris Schmidt,Christina Bohannan,Christina Hines,Clay Strickland,Connie Chan,Cory Mills,Curtis Goodwin,Dan Green,Dan Schwartz,Daniella Levine Cava,Darrell Issa,Darren Soto,David Flippo,David G. Valadao,David Gedert,David Rouzer,David Womack,Denise Powell,Derek Merrin,Derrick Van Orden,Don Davis,Don Leonard,Don't know,Don't know/Someone else,Don't know/Would not vote,Doris Matsui,Dwayne Romero,Ed Hershey,Eddie Espinoza,Elaine G. Luria,Eli Crane,Eliott Rodriguez,Eric Chung,Eric Conroy,Eric Flores,Eric Hafner,Eric Pratt,Esther Kim-Varet,French Hill,Gabe Vasquez,Generic Democrat,Generic Libertarian,Generic Republican,George Moraitis,Gerald Malloy,Gina Swoboda,Glenn Grothman,Greg Cunningham,Greg Landsman,Greg Murphy,Hector Mujica,Heidi Hall,Henry Cuellar,J.D. Ford,Jackie Auringer,Jake Johnson,James Johnson,James Pericola,Janelle Stelson,Jared Golden,Jasmeet Bains,Jay Feely,Jeff Crank,Jeff Hurd,Jeff Van Drew,Jen Kiggans,Jennifer Jenkins,Jennifer Konfrst,Jenny Costa Honeycutt,Jessica Killin,Jim Desmond,Jimmy Gomez,JoAnna Mendoza,Joe Baldacci,Joe Mitchell,Joe Strada,John Braun,John Cavanaugh,John McGuire,John Vincent,John Williams,Johnny Garcia,Jonathan Nez,Jordan Wood,Juan Ciscomani,Justin Pearson,Kaela Berg,Kathy Castor,Katy Padilla Stout,Kaylee Peterson,Keith Gross,Kelly Kirschner,Ken Calvert,Kevin Kiley,Kevin Steele,Kimberly Hardy,Kristina Knickerbocker,LaKesha Womack,Laurie Buckhout,Leela Gray,Lily Tang Williams,Lindsay James,Lupe Castillo,Lynn Chapman,Maad Abu-Ghazalah,Mac Deford,Maggie Goodlander,Mai Vang,Marcy Kaptur,Margo Ellis,Mariannette Miller-Meeks,Marie Gluesenkamp Perez,Mark Coester,Mark Smith,Marlon Duran,Marni von Wilpert,Mary Peltola,María Elvira Salazar,Matt Cavanaugh,Matt Dunlap,Matt Klein,Matt Little,Matt Maasdam,Matt Rains,Matt Schultz,Max Miller,Michael Baumgartner,Michael Bridgford,Michael Thurow,Micheál O'Leary,Mike Beltran,Mike Bouchard,Mike Carey,Mike Davey,Mike Flood,Mike Haridopolos,Mike Lawler,Mike Turner,Mitchell Berman,Monica De La Cruz,Nancy Lacore,Nancy Pelosi,Nate Powell,Neither,Nicholas J. LaLota,Nicholas Zateslo,Nick Begich,Nick Sheedy,Oliver Larkin,Other named candidates,Paige Cognetti,Pat Harrigan,Pat Ryan,Patty Garcia,Paul LePage,Pia Dandiya,Ralph Alvarado,Randy Villegas,Raymond Smith Jr.,Rebecca Bennett,Rebecca Cooke,Rhett Marques,Rich McCormick,Richard Lamondin,Richard Pan,Rob Bresnahan Jr.,Robert Wittman,Robin Peguero,Russ Fulcher,Russell Fry,Ryan Busse,Ryan Dotson,Ryan E. Mackenzie,Ryan Zinke,Saikat Chakrabarti,Sam Forstag,Sarah Trone Garriott,Sarah Zabel,Scott Perry,Scott Singer,Scott Wiener,Seamus O'Toole,Sean McCann,Shannon Taylor,Shomari Figures,Someone else,Sydney Gruters,Tano Tijerina,Teresa Benitez-Thompson,Thomas Aaron Bailey,Thomas H. Kean Jr.,Thomas McMasters,Tim Greimel,Tim Moore,Tim Sheehy,Tina Shah,Tom Barrett,Tom Perriello,Tony D’Arrigo,Tony Kozycki,Vicente Gonzalez,Victoria Spartz,William Lawrence,Would not vote,Yen Bailey,Young Kim,Zach Dembo,Zach Nunn
0,016369fb-4a26-42ad-a583-39067289cab2,65c0d75b-5121-4107-b61a-95b2534fab6e,WI,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0208a971-f1c8-4f04-aae8-2acbc265a583,5ab93d8c-0f9c-42c9-963c-a23e40a5e9b4,NH,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,NaN,NaN,NaN,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0245de88-747f-4893-9c92-fd35eb70f977,73e8c905-d20f-4d20-85d2-8150cf0e2551,MT,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0245de88-747f-4893-9c92-fd35eb70f977,957f3c8e-b3ac-4427-8c46-d0bf1e0df13b,MT,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,04cf125a-5732-4911-a512-85a61d32ceeb,68b640e7-53f5-48c7-8c5f-cd0749aadd32,PA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
polls_pivot.shape

(280, 261)

In [8]:
candinfo_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQZC7cVru6ltLR2e8XN5jdJPfxfj42BAxUApe3Zq3_ENQjLtYntmAxD0pIHqEUJ4ZFLXlybKJdkLf2r/pub?output=csv'
candinfo = pd.read_csv(candinfo_url)

In [9]:
dem_uncont = candinfo[candinfo['rep_cand'] == 'Not Contested']
rep_uncont = candinfo[candinfo['dem_cand'] == 'Not Contested']
candinfo = candinfo[(candinfo['dem_cand'] != 'Not Contested') &
    (candinfo['rep_cand'] != 'Not Contested')]
candinfo['state_po'] = candinfo['cd'].map(lambda x: x[:2]).astype(str)
candinfo['district_number'] = candinfo['cd'].map(lambda x: 0 if x[3:] == 'AL' else int(x[3:]))
candinfo.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number
0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0
1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1
2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2
3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3
4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4

In [10]:
dem_uncont.shape, rep_uncont.shape

((16, 5), (1, 5))

In [11]:
polled_cands = polls_pivot.columns.values[4:]
running_dems = np.unique(candinfo['dem_cand'].astype(str))
running_reps = np.unique(candinfo['rep_cand'].astype(str))
all_running_cands = np.concatenate([running_dems, running_reps])

In [12]:
hypo_cands = []
for c in polled_cands:
    fuzzymatch = process.extractOne(c, all_running_cands, scorer=fuzz.token_sort_ratio, score_cutoff=80)
    if fuzzymatch is None:
        hypo_cands.append(c)

In [13]:
for h in hypo_cands:
    if h in ['Nicholas J. LaLota', 'Robert J. Wittman', 'Thomas H. Kean',
 'Thomas H. Kean Jr.', "Don't know",
 "Don't know/Someone else",
 "Don't know/Would not vote", 'Someone else', 'Would not vote']:
        continue
    # print(h, polls_pivot["Christina Bohannan"].isna().all())
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

for h in ['John Williams', 'Mike Davey']: # names that weren't caught in hypo_cands but should've been
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

In [14]:
polls_pivot.shape

(127, 171)

In [15]:
rel_polls = polls[(polls['poll_id'].isin(np.unique(polls_pivot['poll_id']))) &
    (polls['question_id'].isin(np.unique(polls_pivot['question_id'])))]

In [16]:
np.unique(rel_polls['candidate_name'])

array(['Aaron Flint', 'Andy Harris', 'Anna Paulina Luna',
       'Anthony Constantino', 'Ashley Bell', 'Bill Hill', 'Bill Huizenga',
       'Blake Gendebien', 'Bob Brooks', 'Bob Harvie', 'Bobby Pulido',
       'Brad Finstad', 'Brad Smith', 'Brandon Herrera', 'Brent Taylor',
       'Brian Fitzpatrick', 'Brian Poindexter', 'Brinker Harding',
       'Bryan Steil', 'Cait Conley', 'Carlos De La Cruz',
       'Carmela Conroy', 'Casey Askar', 'Chris Backemeyer',
       'Chris Gallant', 'Chris Jones', 'Chris Schmidt',
       'Christina Bohannan', 'Christina Hines', 'Dan Green',
       'Dan Schwartz', 'Darren Soto', 'David Flippo', 'David G. Valadao',
       'David Rouzer', 'Denise Powell', 'Derrick Van Orden', 'Don Davis',
       "Don't know", "Don't know/Would not vote", 'Dwayne Romero',
       'Elaine G. Luria', 'Eli Crane', 'Eliott Rodriguez', 'Eric Chung',
       'Eric Conroy', 'Eric Flores', 'Eric Pratt', 'French Hill',
       'Gabe Vasquez', 'Glenn Grothman', 'Greg Cunningham',
       'Greg Landsman', 'Greg Murphy', 'Henry Cuellar', 'J.D. Ford',
       'Jackie Auringer', 'Jake Johnson', 'James Pericola',
       'Janelle Stelson', 'Jeff Crank', 'Jeff Hurd', 'Jen Kiggans',
       'Jennifer Jenkins', 'Jenny Costa Honeycutt', 'Jessica Killin',
       'Jim Desmond', 'JoAnna Mendoza', 'Joe Mitchell', 'Joe Strada',
       'John Braun', 'John McGuire', 'John Vincent', 'Johnny Garcia',
       'Jonathan Nez', 'Juan Ciscomani', 'Justin Pearson', 'Kathy Castor',
       'Katy Padilla Stout', 'Kelly Kirschner', 'Kevin Kiley',
       'Kimberly Hardy', 'Kristina Knickerbocker', 'LaKesha Womack',
       'Laurie Buckhout', 'Leela Gray', 'Lily Tang Williams',
       'Lindsay James', 'Maggie Goodlander', 'Mariannette Miller-Meeks',
       'Marie Gluesenkamp Perez', 'Marni von Wilpert',
       'María Elvira Salazar', 'Matt Dunlap', 'Matt Little', 'Max Miller',
       'Michael Baumgartner', 'Mike Beltran', 'Mike Bouchard',
       'Mike Flood', 'Mike Haridopolos', 'Mike Lawler', 'Mike Turner',
       'Mitchell Berman', 'Monica De La Cruz', 'Nancy Lacore',
       'Nicholas J. LaLota', 'Nick Begich', 'Paige Cognetti',
       'Pat Harrigan', 'Pat Ryan', 'Paul LePage', 'Pia Dandiya',
       'Ralph Alvarado', 'Randy Villegas', 'Raymond Smith Jr.',
       'Rebecca Bennett', 'Rebecca Cooke', 'Rhett Marques',
       'Rich McCormick', 'Richard Pan', 'Rob Bresnahan Jr.',
       'Robert Wittman', 'Russell Fry', 'Ryan E. Mackenzie',
       'Sam Forstag', 'Sarah Trone Garriott', 'Scott Perry',
       'Sean McCann', 'Shannon Taylor', 'Shomari Figures', 'Someone else',
       'Sydney Gruters', 'Tano Tijerina', 'Teresa Benitez-Thompson',
       'Thomas H. Kean Jr.', 'Tim Moore', 'Tom Barrett', 'Tom Perriello',
       'Tony Kozycki', 'Vicente Gonzalez', 'Victoria Spartz',
       'William Lawrence', 'Would not vote', 'Zach Dembo', 'Zach Nunn'],
      dtype=object)

In [17]:
rel_polls.shape

(343, 50)

In [18]:
rel_polls.to_csv('transformed/relevent_house_polls.csv')