In [20]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from rapidfuzz import fuzz, process

In [22]:
url = "https://www.nytimes.com/newsgraphics/polls/house.csv"
polls = pd.read_csv(url)
polls.to_csv('../../2026_data/polls/house.csv')
polls = polls[
    (polls['state'] != 'US') &
    (polls['stage'] == 'general')
]
polls.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,methodology,transparency_score,state,start_date,end_date,sponsor_candidate_id,sponsor_candidate,sponsor_candidate_party,question_id,sample_size,population,subpopulation,population_full,tracking,created_at,notes,url,url_article,url_topline,url_crosstab,source,internal,partisan,cycle,office_type,seat_name,seat_number,election_date,stage,party,pct,answer,candidate_name,candidate_id,race_id,nationwide_match,ranked_choice_reallocated,hypothetical
0,984d2838-96aa-429d-a8c2-4c68f08c4041,92c013f6-4061-47d8-a6c6-b19fa6d1f875,"Keating Research, Inc.",NaN,NaN,"Keating Research, Inc.",161.0,Keating Research,NaN,NaN,Live Phone/Text-to-Web,NaN,CO,7/21/26,7/23/26,NaN,Dwayne Romero,DEM,3a890572-a4ec-4c86-8e1b-69d940acb668,500.0,lv,NaN,lv,NaN,7/30/26 13:10,NaN,https://x.com/RomeroForCO/status/2082843915510...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Third Congressional District,3.0,2026-11-03,general,NONE,9.0,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,6a947c92-e683-47ef-ba80-71e56a333bcb,NaN,NaN,NaN
1,984d2838-96aa-429d-a8c2-4c68f08c4041,92c013f6-4061-47d8-a6c6-b19fa6d1f875,"Keating Research, Inc.",NaN,NaN,"Keating Research, Inc.",161.0,Keating Research,NaN,NaN,Live Phone/Text-to-Web,NaN,CO,7/21/26,7/23/26,NaN,Dwayne Romero,DEM,3a890572-a4ec-4c86-8e1b-69d940acb668,500.0,lv,NaN,lv,NaN,7/30/26 13:10,NaN,https://x.com/RomeroForCO/status/2082843915510...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Third Congressional District,3.0,2026-11-03,general,NONE,1.0,Someone else,Someone else,d23503df-ca4b-41e0-807f-67f2629609ac,6a947c92-e683-47ef-ba80-71e56a333bcb,NaN,NaN,NaN
2,984d2838-96aa-429d-a8c2-4c68f08c4041,92c013f6-4061-47d8-a6c6-b19fa6d1f875,"Keating Research, Inc.",NaN,NaN,"Keating Research, Inc.",161.0,Keating Research,NaN,NaN,Live Phone/Text-to-Web,NaN,CO,7/21/26,7/23/26,NaN,Dwayne Romero,DEM,3a890572-a4ec-4c86-8e1b-69d940acb668,500.0,lv,NaN,lv,NaN,7/30/26 13:10,NaN,https://x.com/RomeroForCO/status/2082843915510...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Third Congressional District,3.0,2026-11-03,general,REP,46.0,Hurd (Jeff),Jeff Hurd,c58658f2-c242-46d3-8310-3135de04bd5d,6a947c92-e683-47ef-ba80-71e56a333bcb,NaN,NaN,NaN
3,984d2838-96aa-429d-a8c2-4c68f08c4041,92c013f6-4061-47d8-a6c6-b19fa6d1f875,"Keating Research, Inc.",NaN,NaN,"Keating Research, Inc.",161.0,Keating Research,NaN,NaN,Live Phone/Text-to-Web,NaN,CO,7/21/26,7/23/26,NaN,Dwayne Romero,DEM,3a890572-a4ec-4c86-8e1b-69d940acb668,500.0,lv,NaN,lv,NaN,7/30/26 13:10,NaN,https://x.com/RomeroForCO/status/2082843915510...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Third Congressional District,3.0,2026-11-03,general,DEM,45.0,Romero (Dwayne),Dwayne Romero,45b3d645-5617-4322-a01e-dbab370e7a04,6a947c92-e683-47ef-ba80-71e56a333bcb,NaN,NaN,NaN
7,21e952f7-3e33-46e3-b6e3-d897ba6d1959,9b245451-0334-4f8c-909e-b48d602feb76,Public Policy Polling,NaN,NaN,Public Policy Polling,263.0,Public Policy Polling,NaN,NaN,Live Phone/Text,NaN,FL,7/17/26,7/18/26,NaN,Jennifer Jenkins,DEM,11bc2df5-d34e-4e99-8908-74f55941ce1f,633.0,rv,NaN,rv,NaN,7/29/26 14:30,NaN,https://floridapolitics.com/archives/810254-je...,NaN,NaN,NaN,NaN,NaN,DEM,2026,U.S. House,Eighth Congressional District,8.0,2026-11-03,general,NONE,21.0,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,c1d7d361-0944-4437-8ed0-7e05287aa568,NaN,NaN,NaN

In [23]:
pd.set_option('display.max_columns', None)

In [24]:
polls_pivot = pd.pivot_table(data=polls, values='pct', index=['poll_id', 'question_id', 'state', 'seat_number'], columns='candidate_name', aggfunc='first')
polls_pivot = polls_pivot.reset_index()
polls_pivot.head()

candidate_name,poll_id,question_id,state,seat_number,Aaron Flint,Adam Ortiz,Alex Kelloff,Alexander Fornino,Amanda Edwards,Ammar Campa-Najjar,Andy Ogles,Ann Wagner,Anna Paulina Luna,Anthony Constantino,Ashley Bell,Austin Ahlman,Bajun Mavalwalla,Bale Dalton,Becca Balint,Bill Hill,Bill Huizenga,Blake Gendebien,Bob Brooks,Bob Harvie,Bobby Pulido,Brad Finstad,Brad Smith,Brandon Herrera,Brian Fitzpatrick,Brian Poindexter,Bridget Brink,Bryan Steil,Cait Conley,Carlos A. Gimenez,Carmela Conroy,Carmen Maria Montiel,Carter Page,Chaz Molder,Cherlynn Stevenson,Chris Backemeyer,Chris Gallant,Christian Menefee,Christina Bohannan,Christina Hines,Cory Mills,Curtis Goodwin,Daniella Levine Cava,Darrell Issa,David Flippo,David G. Valadao,David Gedert,David Womack,Denise Powell,Derek Merrin,Derrick Van Orden,Don Davis,Don't know,Don't know/Someone else,Don't know/Would not vote,Dwayne Romero,Elaine G. Luria,Eli Crane,Eliott Rodriguez,Eric Chung,Eric Flores,Eric Pratt,Esther Kim-Varet,Fred Wellman,Gabe Vasquez,Generic Democrat,Generic Republican,George Foreman IV,George Moraitis,Gerald Malloy,Gina Swoboda,Glenn Grothman,Greg Cunningham,Hector Mujica,Heidi Hall,Henry Cuellar,Isaiah Martin,Jake Johnson,Janelle Stelson,Jared Forrest Golden,Jared Moskowitz,Jasmeet Bains,Jeff Crank,Jeff Hurd,Jeff Van Drew,Jen A. Kiggans,Jennifer Jenkins,Jennifer Konfrst,Jessica Killin,Jim Desmond,JoAnna Mendoza,Joe Baldacci,Joe Mitchell,John Braun,John Cavanaugh,John Williams,Jolanda Jones,Jonathan Nez,Jordan Wood,Juan Ciscomani,Kaela Berg,Kathy Castor,Katy Padilla Stout,Kaylee Peterson,Ken Calvert,Kevin Kiley,Kevin Steele,Kristina Knickerbocker,LaKesha Womack,Laurie Buckhout,Leela Gray,Lily Tang Williams,Lindsay James,Mac Deford,Maggie Goodlander,Marcy Kaptur,Mariannette Miller-Meeks,Marie Gluesenkamp Perez,Mark Coester,Mark Smith,Marni von Wilpert,Mary S. Peltola,María Elvira Salazar,Matt Cavanaugh,Matt Dunlap,Matt Klein,Matt Little,Matt Maasdam,Matt Rains,Matt Schultz,Max Miller,Michael Baumgartner,Michael Bridgford,Michael Thurow,Mike Beltran,Mike Bouchard,Mike Davey,Mike Flood,Mike Haridopolos,Mike Lawler,Mike Turner,Mitchell Berman,Monica De La Cruz,Nancy Pelosi,Nate Powell,Neither,Nicholas J. LaLota,Nick Begich,Oliver Larkin,Other named candidates,Paige Cognetti,Pat Harrigan,Paul R. LePage,Ralph Alvarado,Randy Villegas,Rebecca Bennett,Rebecca Cooke,Rhett Marques,Richard Lamondin,Richard Pan,Rob Bresnahan Jr.,Robert J. Wittman,Robin Peguero,Ronald Whitfield,Russ Fulcher,Ryan Busse,Ryan Dotson,Ryan E. Mackenzie,Ryan K. Zinke,Saikat Chakrabarti,Sam Forstag,Sarah Trone Garriott,Sarah Zabel,Scott Perry,Scott Singer,Sean McCann,Shannon Taylor,Shomari Figures,Someone else,Tano Tijerina,Teresa Benitez-Thompson,Theodis Daniel,Thomas (Jay) Feely,Thomas Aaron Bailey,Thomas H. Kean,Thomas H. Kean Jr.,Tim Greimel,Tim Moore,Tim Sheehy,Tina Shah,Tom Barrett,Vicente Gonzalez,William Lawrence,Would not vote,Young Kim,Zach Dembo,Zach Nunn
0,016369fb-4a26-42ad-a583-39067289cab2,65c0d75b-5121-4107-b61a-95b2534fab6e,WI,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0208a971-f1c8-4f04-aae8-2acbc265a583,5ab93d8c-0f9c-42c9-963c-a23e40a5e9b4,NH,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.0,NaN,NaN,40.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0245de88-747f-4893-9c92-fd35eb70f977,73e8c905-d20f-4d20-85d2-8150cf0e2551,MT,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,38.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0245de88-747f-4893-9c92-fd35eb70f977,957f3c8e-b3ac-4427-8c46-d0bf1e0df13b,MT,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,06bcf2dd-2622-4984-9d26-992e75d54d69,167a1161-87dc-4101-8558-334cce646f2e,NM,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
polls_pivot.shape

(201, 201)

In [26]:
candinfo_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vQZC7cVru6ltLR2e8XN5jdJPfxfj42BAxUApe3Zq3_ENQjLtYntmAxD0pIHqEUJ4ZFLXlybKJdkLf2r/pub?output=csv'
candinfo = pd.read_csv(candinfo_url)

In [27]:
dem_uncont = candinfo[candinfo['rep_cand'] == 'Not Contested']
rep_uncont = candinfo[candinfo['dem_cand'] == 'Not Contested']
candinfo = candinfo[(candinfo['dem_cand'] != 'Not Contested') &
    (candinfo['rep_cand'] != 'Not Contested')]
candinfo['state_po'] = candinfo['cd'].map(lambda x: x[:2]).astype(str)
candinfo['district_number'] = candinfo['cd'].map(lambda x: 0 if x[3:] == 'AL' else int(x[3:]))
candinfo.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number
0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0
1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1
2,AL-02,Shomari Figures,Hampton Harris,True,False,AL,2
3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3
4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4

In [28]:
dem_uncont.shape, rep_uncont.shape

((11, 5), (1, 5))

In [29]:
polled_cands = polls_pivot.columns.values[4:]
running_dems = np.unique(candinfo['dem_cand'].astype(str))
running_reps = np.unique(candinfo['rep_cand'].astype(str))
all_running_cands = np.concatenate([running_dems, running_reps])

In [30]:
hypo_cands = []
for c in polled_cands:
    fuzzymatch = process.extractOne(c, all_running_cands, scorer=fuzz.token_sort_ratio, score_cutoff=80)
    if fuzzymatch is None:
        hypo_cands.append(c)

In [31]:
for h in hypo_cands:
    if h in ['Nicholas J. LaLota', 'Robert J. Wittman', 'Thomas H. Kean',
 'Thomas H. Kean Jr.', "Don't know",
 "Don't know/Someone else",
 "Don't know/Would not vote", 'Someone else', 'Would not vote']:
        continue
    # print(h, polls_pivot["Christina Bohannan"].isna().all())
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

for h in ['John Williams', 'Mike Davey']: # names that weren't caught in hypo_cands but should've been
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

In [32]:
polls_pivot.shape

(60, 112)

In [33]:
rel_polls = polls[(polls['poll_id'].isin(np.unique(polls_pivot['poll_id']))) &
    (polls['question_id'].isin(np.unique(polls_pivot['question_id'])))]

In [34]:
np.unique(rel_polls['candidate_name'])

array(['Aaron Flint', 'Anthony Constantino', 'Ashley Bell', 'Bill Hill',
       'Blake Gendebien', 'Bob Brooks', 'Bob Harvie', 'Bobby Pulido',
       'Brad Finstad', 'Brandon Herrera', 'Brian Fitzpatrick',
       'Brian Poindexter', 'Cait Conley', 'Chris Backemeyer',
       'Chris Gallant', 'Christina Bohannan', 'David G. Valadao',
       'Derrick Van Orden', 'Don Davis', "Don't know",
       "Don't know/Would not vote", 'Dwayne Romero', 'Eric Flores',
       'Gabe Vasquez', 'Greg Cunningham', 'Henry Cuellar', 'Jake Johnson',
       'Janelle Stelson', 'Jeff Crank', 'Jeff Hurd', 'Jessica Killin',
       'Jim Desmond', 'JoAnna Mendoza', 'Joe Mitchell', 'Juan Ciscomani',
       'Katy Padilla Stout', 'Kevin Kiley', 'Kristina Knickerbocker',
       'LaKesha Womack', 'Laurie Buckhout', 'Lily Tang Williams',
       'Lindsay James', 'Maggie Goodlander', 'Mariannette Miller-Meeks',
       'Marni von Wilpert', 'Matt Dunlap', 'Max Miller', 'Mike Flood',
       'Mike Lawler', 'Mike Turner', 'Monica De La Cruz',
       'Nicholas J. LaLota', 'Nick Begich', 'Paige Cognetti',
       'Pat Harrigan', 'Paul R. LePage', 'Ralph Alvarado',
       'Randy Villegas', 'Rebecca Bennett', 'Rebecca Cooke',
       'Richard Pan', 'Rob Bresnahan Jr.', 'Ryan E. Mackenzie',
       'Sam Forstag', 'Sarah Trone Garriott', 'Scott Perry',
       'Someone else', 'Tano Tijerina', 'Thomas H. Kean Jr.', 'Tim Moore',
       'Vicente Gonzalez', 'Would not vote', 'Zach Dembo', 'Zach Nunn'],
      dtype=object)

In [35]:
rel_polls.shape

(168, 48)

In [36]:
rel_polls.to_csv('transformed/relevent_house_polls.csv')