In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import pyreadr
import joblib

import matplotlib.pyplot as plt
import plotly.express as px

from tqdm import tqdm

In [3]:
dem_uncont = pd.read_csv('transformed/dem_uncontested_seats.csv')
rep_uncont = pd.read_csv('transformed/rep_uncontested_seats.csv')

In [4]:
seat_sims = pyreadr.read_r('model_output/tot_seats_sims.RDS')[None]
seat_sims = seat_sims.rename({None: 'seats'}, axis=1)
seat_sims['seats'] = seat_sims['seats'].map(lambda x: x + dem_uncont.shape[0])
seat_sims['winner'] = seat_sims['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims

       seats       winner
0        245    Democrats
1        211  Republicans
2        236    Democrats
3        229    Democrats
4        220    Democrats
...      ...          ...
19995    227    Democrats
19996    231    Democrats
19997    231    Democrats
19998    236    Democrats
19999    223    Democrats

[20000 rows x 2 columns]

In [5]:
sim_counts = seat_sims.groupby(['seats']).count().reset_index().rename({'winner': 'count'}, axis=1)
n_sims = seat_sims.shape[0]
sim_counts['pct'] = sim_counts['count'] / n_sims * 100
sim_counts['winner'] = sim_counts['seats'].map(lambda x: 'Democrats' if x >= 218 else 'Republicans')
seat_sims = pd.merge(left=seat_sims.drop(['winner'], axis=1), right=sim_counts, on='seats', how='left')
def get_desc(winner, pct, seats):
    return f'{winner} wins {seats if seats >= 218 else (435-seats)} seats in {pct:.2f}% of simulations'
#seat_sims['desc'] = seat_sims[['winner', 'pct', 'seats']].apply(lambda x: get_desc(x['winner'], x['pct'], x['seats']), axis=1)
sim_counts.head()

   seats  count    pct       winner
0    150      1  0.005  Republicans
1    151      1  0.005  Republicans
2    152      1  0.005  Republicans
3    158      1  0.005  Republicans
4    160      1  0.005  Republicans

In [6]:
np.unique(seat_sims['seats']).shape[0]

189

In [7]:
sims_hist = px.histogram(seat_sims, x='seats', nbins=np.unique(seat_sims['seats']).shape[0]*2, color='winner', 
                         labels={'seats':'Seats won by Democrats', 'winner': 'Winner'})
sims_hist.update_traces(showlegend=False)
sims_hist.add_vline(x=217.5, line_width=1, line_color='black', annotation_text='218 seats required for majority', 
                    annotation_position='top right')
sims_hist

In [8]:
# posterior prediction
post = pyreadr.read_r('model_output/labeled_posterior.RDS')[None]
post_untransp = post.copy()

In [9]:
post = post.T
post.head()

,0,1,2,3,4,5,6,7,8,9,...,19990,19991,19992,19993,19994,19995,19996,19997,19998,19999
AK-AL,-0.672030,-7.356339,-1.556502,-5.773482,-3.094042,-4.370689,-3.891815,-4.858048,-4.784829,-5.323414,...,-6.056714,-1.352019,-5.398098,-6.733619,1.878966,-0.610678,-4.619789,-4.223371,-0.965773,-8.415116
AL-01,-11.956209,-19.090787,-13.330512,-14.614943,-13.116367,-14.078057,-18.586117,-14.900296,-13.095541,-14.961726,...,-16.933476,-8.623670,-14.795062,-18.906752,-13.025948,-13.660733,-17.249143,-12.148882,-12.524740,-13.036306
AL-02,-0.952971,-0.571435,-3.922085,-0.249561,-4.881245,3.515090,-4.950622,-1.576918,0.331831,-4.360302,...,-1.602959,-4.742302,-3.688976,-1.051786,0.763939,0.235478,-1.000408,-0.157234,-2.103721,-0.704788
AL-03,-16.818753,-22.376560,-20.369983,-18.761976,-21.237839,-19.697612,-22.403069,-20.740820,-21.000019,-23.739417,...,-22.102721,-18.289500,-21.622420,-27.401168,-17.629657,-21.377413,-22.033724,-21.460617,-20.656274,-23.865702
AL-04,-26.901761,-33.197737,-26.300172,-28.311586,-31.386670,-28.846433,-30.225058,-29.236476,-28.476340,-32.724453,...,-32.365796,-33.404360,-30.566601,-34.903561,-22.486811,-33.475146,-32.478524,-30.486639,-24.818887,-30.351981

In [28]:
sim_corr = post_untransp.corr()

In [29]:
sim_corr

,AK-AL,AL-01,AL-02,AL-03,AL-04,AL-05,AL-06,AL-07,AR-01,AR-02,AR-03,AR-04,AZ-01,AZ-02,AZ-03,AZ-04,AZ-05,AZ-06,AZ-07,AZ-08,AZ-09,CA-01,CA-02,CA-03,CA-05,CA-06,CA-08,CA-09,CA-10,CA-13,CA-15,CA-16,CA-17,CA-18,CA-19,CA-20,CA-21,CA-22,CA-23,CA-24,CA-25,CA-26,CA-27,CA-28,CA-30,CA-31,CA-32,CA-33,CA-35,CA-36,CA-38,CA-39,CA-41,CA-42,CA-43,CA-44,CA-45,CA-46,CA-47,CA-48,CA-49,CA-50,CA-51,CA-52,CO-01,CO-02,CO-03,CO-04,CO-05,CO-06,CO-07,CO-08,CT-01,CT-02,CT-03,CT-04,CT-05,DE-AL,FL-01,FL-02,FL-03,FL-04,FL-05,FL-06,FL-07,FL-08,FL-09,FL-11,FL-12,FL-13,FL-14,FL-15,FL-16,FL-17,FL-18,FL-19,FL-20,FL-21,FL-22,FL-23,FL-24,FL-25,FL-26,FL-27,FL-28,GA-01,GA-02,GA-03,GA-04,GA-05,GA-06,GA-07,GA-08,GA-09,GA-10,GA-11,GA-12,GA-13,GA-14,HI-01,HI-02,IA-01,IA-02,IA-03,IA-04,ID-01,ID-02,IL-01,IL-02,IL-03,IL-04,IL-05,IL-06,IL-07,IL-08,IL-09,IL-10,IL-11,IL-12,IL-13,IL-14,IL-15,IL-16,IL-17,IN-01,IN-02,IN-03,IN-04,IN-05,IN-06,IN-07,IN-08,IN-09,KS-01,KS-02,KS-03,KS-04,KY-01,KY-02,KY-03,KY-04,KY-05,KY-06,LA-01,LA-02,LA-03,LA-04,LA-05,LA-06,MA-01,MA-02,MA-03,MA-04,MA-05,MA-06,MA-07,MA-08,MA-09,MD-01,MD-02,MD-03,MD-04,MD-05,MD-06,MD-07,MD-08,ME-01,ME-02,MI-01,MI-02,MI-03,MI-04,MI-05,MI-06,MI-07,MI-08,MI-09,MI-10,MI-11,MI-12,MI-13,MN-01,MN-02,MN-03,MN-04,MN-05,MN-06,MN-07,MN-08,MO-01,MO-02,MO-03,MO-04,MO-05,MO-06,MO-07,MO-08,MS-01,MS-02,MS-03,MS-04,MT-01,MT-02,NC-01,NC-02,NC-03,NC-04,NC-05,NC-06,NC-07,NC-08,NC-09,NC-10,NC-11,NC-12,NC-13,NC-14,ND-AL,NE-01,NE-02,NE-03,NH-01,NH-02,NJ-01,NJ-02,NJ-03,NJ-04,NJ-05,NJ-06,NJ-07,NJ-09,NJ-10,NJ-11,NJ-12,NM-01,NM-02,NM-03,NV-01,NV-02,NV-03,NV-04,NY-01,NY-02,NY-03,NY-04,NY-05,NY-06,NY-07,NY-08,NY-09,NY-10,NY-11,NY-12,NY-13,NY-14,NY-15,NY-16,NY-17,NY-18,NY-19,NY-20,NY-21,NY-22,NY-23,NY-24,NY-25,NY-26,OH-01,OH-02,OH-03,OH-04,OH-05,OH-06,OH-07,OH-08,OH-09,OH-10,OH-11,OH-12,OH-13,OH-14,OH-15,OK-01,OK-02,OK-03,OK-04,OK-05,OR-01,OR-02,OR-03,OR-04,OR-05,OR-06,PA-01,PA-02,PA-04,PA-05,PA-06,PA-07,PA-08,PA-09,PA-10,PA-11,PA-12,PA-13,PA-14,PA-15,PA-16,PA-17,RI-01,RI-02,SC-01,SC-02,SC-03,SC-04,SC-05,SC-06,SC-07,SD-AL,TN-01,TN-02,TN-03,TN-04,TN-05,TN-06,TN-07,TN-08,TN-09,TX-01,TX-02,TX-03,TX-04,TX-05,TX-06,TX-07,TX-08,TX-09,TX-10,TX-11,TX-12,TX-13,TX-14,TX-15,TX-16,TX-17,TX-18,TX-19,TX-20,TX-21,TX-22,TX-23,TX-24,TX-25,TX-26,TX-27,TX-28,TX-29,TX-30,TX-31,TX-32,TX-33,TX-34,TX-35,TX-36,TX-37,TX-38,UT-01,UT-02,UT-03,UT-04,VA-01,VA-02,VA-03,VA-04,VA-05,VA-06,VA-07,VA-08,VA-09,VA-10,VA-11,VT-AL,WA-01,WA-02,WA-03,WA-04,WA-05,WA-06,WA-07,WA-08,WA-09,WA-10,WI-01,WI-03,WI-04,WI-05,WI-06,WI-07,WI-08,WV-01,WV-02,WY-AL
AK-AL,1.000000,0.720137,0.504067,0.740507,0.734318,0.723277,0.741214,0.501666,0.739769,0.746811,0.738595,0.743270,0.500329,0.498403,0.503204,0.525595,0.707677,0.724860,0.725031,0.726053,0.744558,0.708238,0.522989,0.526498,0.746198,0.734975,0.583058,0.518386,0.529541,0.526290,0.504175,0.706249,0.581891,0.521484,0.520260,0.710614,0.523060,0.746406,0.734242,0.531602,0.530246,0.710937,0.499724,0.523193,0.500120,0.533349,0.568198,0.527531,0.571324,0.530249,0.712430,0.520463,0.518171,0.506615,0.527880,0.511592,0.495697,0.561385,0.499425,0.710955,0.521035,0.531244,0.516936,0.517708,0.708487,0.520531,0.725702,0.738110,0.725254,0.523012,0.511726,0.724066,0.708193,0.525513,0.523464,0.552485,0.523989,0.491648,0.505474,0.707804,0.740903,0.576201,0.745078,0.710529,0.706849,0.726651,0.521016,0.710481,0.739643,0.743971,0.520184,0.734276,0.705892,0.740781,0.736904,0.707039,0.526843,0.743528,0.707065,0.525135,0.708780,0.510517,0.741079,0.739606,0.562650,0.708051,0.526141,0.556665,0.522107,0.522379,0.519828,0.735000,0.740913,0.740320,0.705346,0.708781,0.740005,0.736042,0.502135,0.515035,0.510181,0.564960,0.710869,0.733772,0.706809,0.561070,0.743738,0.507852,0.710689,0.515971,0.726567,0.574257,0.563472,0.732694,0.712963,0.728583,0.528721,0.527782,0.744323,0.506535,0.525318,0.735980,0.738273,0.508969,0.516565,0.730441,0.732777,0.741822,0.736503,0.515968,0.525761,0.724423,0.733536,0.736264,0.724475,0.517616,0.739396,0.742432,0.734669,0.512212,0.707818,0.736083,0.709497,0.747249,0.505003,0.745450,0.733306,0.705373,0.707302,0.499367,0.504262,0.511199,0.500753,0.504169,0.709409,0.500988,0.509854,0.522162,0.744845,0.508261,0.504159,0.548249,0.727742,0.503052,0.561852,0.553891,0.538529,0.707523,0.549971,0.741576,0.516013,0.749268,0.745149,0.558477,0.733792,0.500650,0.736994,0.707624,0.707987,0.553073,0.705202,0.733259,0.709765,0.496062,0.522823,0.520695,0.745560,0.736251,0.738077,0.501605,0.745581,0.558629,0.733788,0.517152,0.711658,0.557017,0.738613,0.738780,0.547768,0.740188,0.729417,0.711004,0.722604,0.558573,0.515421,0.730345,0.516487,0.560776,0.707757,0.745295,0.736443,0.533255,0.734229,0.710579,0.528029,0.724632,0.727169,0.531236,0.726843,0.709420,0.742452,0.710640,0.492573,0.528775,0.736320,0.501549,0.744207,0.523931,0.528181,0.743581,0.504413,0.547461,0.707212,0.707909,0.509132,0.502384,0.516448,0.518582,0.708202,0.510965,0.524071,0.731640,0.734336,0.557766,0.507964,0.495166,0.518965,0.710125,0.516762,0.518189,0.707600,0.737706,0.706462,0.710815,0.520124,0.560724,0.498115,0.739425,0.511021,0.509234,0.533100,0.709105,0.503811,0.732639,0.745524,0.705350,0.498205,0.514703,0.727264,0.529342,0.740534,0.747214,0.721318,0.730586,0.584985,0.533960,0.744251,0.515078,0.556305,0.512142,0.744130,0.735863,0.707575,0.549400,0.731512,0.737796,0.739948,0.529572,0.736751,0.505113,0.552089,0.497937,0.507164,0.741630,0.521126,0.521167,0.524198,0.523615,0.732521,0.731073,0.737435,0.557630,0.746018,0.553793,0.553205,0.738694,0.747624,0.742732,0.508622,0.498217,0.503176,0.706980,0.747912,0.718524,0.735654,0.709281,0.527540,0.732864,0.709209,0.734412,0.735425,0.743318,0.556725,0.707966,0.705533,0.711636,0.742159,0.709310,0.723676,0.706089,0.724848,0.739269,0.743611,0.725322,0.525828,0.496149,0.705874,0.707287,0.708816,0.732334,0.731016,0.748083,0.723981,0.520352,0.746781,0.707214,0.709335,0.510579,0.508645,0.502023,0.708560,0.738006,0.740376,0.724115,0.554989,0.516134,0.524792,0.710503,0.740085,0.705529,0.548233,0.520637,0.708161,0.538799,0.514339,0.499736,0.510102,0.735048,0.722996,0.730484,0.745469,0.559592,0.525846,0.500581,0.723603,0.734343,0.503030,0.526211,0.741600,0.497812,0.706167,0.535479,0.525304,0.525214,0.507165,0.707557,0.550110,0.496473,0.522335,0.522652,0.577973,0.508056,0.741952,0.562434,0.580005,0.738686,0.745675,0.707122,0.722520,0.736939,0.716035,0.706652
AL-01,0.720137,1.000000,0.502827,0.747610,0.739537,0.721090,0.742903,0.509272,0.744557,0.748964,0.740476,0.749223,0.502232,0.503966,0.504942,0.521584,0.714304,0.722353,0.730333,0.725653,0.748484,0.706632,0.525367,0.532245,0.745894,0.740175,0.580555,0.520859,0.530002,0.527529,0.505200,0.707657,0.581750,0.523269,0.522995,0.715921,0.525612,0.746239,0.739919,0.531836,0.532648,0.709977,0.508149,0.526696,0.495708,0.532554,0.566470,0.529633,0.574606,0.530636,0.710850,0.520434,0.524794,0.508943,0.529656,0.510119,0.511032,0.560773,0.500596,0.713563,0.519936,0.531629,0.517442,0.525121,0.707521,0.526344,0.727174,0.738475,0.721697,0.525976,0.516771,0.727419,0.707248,0.528868,0.529795,0.558798,0.523441,0.492185,0.509555,0.711479,0.739489,0.574557,0.743164,0.712699,0.712578,0.723244,0.522525,0.715887,0.736415,0.741419,0.520471,0.739587,0.710497,0.748388,0.738109,0.713224,0.524277,0.744446,0.710435,0.528940,0.706298,0.516495,0.745545,0.738034,0.555236,0.711189,0.527330,0.558836,0.525572,0.522301,0.518621,0.740192,0.745019,0.740884,0.711153,0.717138,0.743754,0.735892,0.506454,0.514877,0.513463,0.566070,0.713329,0.730610,0.716330,0.567965,0.747189,0.511443,0.711800,0.511483,0.727027,0.574846,0.563200,0.730048,0.712015,0.728787,0.530737,0.528882,0.751001,0.510596,0.526712,0.734961,0.738543,0.515546,0.521181,0.732463,0.735240,0.747357,0.734748,0.516266,0.524566,0.725085,0.734410,0.736591,0.719683,0.520677,0.736726,0.747403,0.737841,0.516314,0.712175,0.743141,0.715629,0.747098,0.506044,0.746169,0.737416,0.711300,0.711696,0.503994,0.515758,0.515524,0.501538,0.507940,0.714413,0.504714,0.514389,0.528934,0.741657,0.510525,0.501868,0.546447,0.730493,0.508692,0.561867,0.548853,0.542752,0.714297,0.552780,0.750472,0.521290,0.750797,0.748689,0.561840,0.736741,0.508106,0.739256,0.714393,0.712266,0.555241,0.707880,0.735394,0.713419,0.494355,0.525457,0.520891,0.752106,0.739412,0.741318,0.502132,0.748520,0.557101,0.732452,0.518824,0.714692,0.558863,0.742368,0.742201,0.548674,0.739023,0.732727,0.715308,0.724605,0.566536,0.516626,0.735068,0.515552,0.563212,0.710614,0.750023,0.731204,0.529095,0.734424,0.712424,0.531514,0.725882,0.727410,0.531292,0.729489,0.710936,0.744782,0.715049,0.496125,0.529745,0.739965,0.502248,0.746702,0.526299,0.533123,0.742059,0.517142,0.549665,0.708837,0.707215,0.511813,0.508770,0.519383,0.522127,0.713532,0.519099,0.527819,0.731050,0.733984,0.561891,0.511084,0.500329,0.521260,0.708445,0.517401,0.517061,0.710011,0.741506,0.704966,0.710630,0.520469,0.555110,0.495824,0.734680,0.513125,0.513286,0.530208,0.709514,0.505704,0.736057,0.750167,0.710181,0.501181,0.523614,0.729892,0.527607,0.744204,0.753057,0.724080,0.727150,0.589874,0.537744,0.744533,0.517816,0.559544,0.517806,0.746072,0.735242,0.712380,0.550672,0.737470,0.738604,0.741322,0.531830,0.735385,0.509178,0.556973,0.500911,0.507023,0.746602,0.523812,0.526040,0.524944,0.524639,0.728033,0.733033,0.740453,0.555702,0.749942,0.555704,0.549937,0.739858,0.750333,0.743035,0.510215,0.504034,0.507734,0.708268,0.751170,0.724012,0.738425,0.713819,0.525690,0.729701,0.711221,0.740933,0.739925,0.749089,0.562426,0.712595,0.711178,0.714020,0.748661,0.713793,0.721545,0.712387,0.729644,0.738909,0.743341,0.727198,0.527820,0.506141,0.711699,0.714089,0.710782,0.731747,0.731457,0.752571,0.729281,0.520130,0.752754,0.707268,0.713910,0.519587,0.512351,0.505380,0.712123,0.742181,0.745767,0.725635,0.559878,0.520309,0.525695,0.706680,0.742904,0.712730,0.549413,0.526804,0.712176,0.543209,0.514710,0.507757,0.510494,0.734510,0.726559,0.727392,0.749894,0.557208,0.523629,0.503136,0.726826,0.739264,0.501253,0.527147,0.746267,0.497999,0.709376,0.529084,0.528557,0.524905,0.508817,0.715383,0.548987,0.498264,0.516759,0.522575,0.577814,0.503717,0.740322,0.561653,0.579871,0.740036,0.746992,0.711133,0.722420,0.741719,0.723800,0.713301
AL-02,0.504067,0.502827,1.000000,0.517943,0.515095,0.502154,0.518851,0.705369,0.516577,0.522272,0.513516,0.519585,0.684997,0.682994,0.682389,0.696427,0.651836,0.505007,0.509021,0.496941,0.514939,0.648092,0.707117,0.715803,0.519593,0.516417,0.590709,0.710247,0.716474,0.537801,0.678898,0.653204,0.596415,0.705831,0.707219,0.655183,0.710997,0.514556,0.510066,0.712073,0.714793,0.654027,0.685367,0.710642,0.681617,0.546276,0.573974,0.715628,0.587371,0.714163,0.651804,0.705934,0.701702,0.693317,0.713710,0.694591,0.686871,0.572778,0.684025,0.652242,0.703980,0.716788,0.689765,0.710138,0.642206,0.708699,0.512182,0.507809,0.502174,0.708471,0.691522,0.505314,0.649281,0.708388,0.709324,0.564025,0.696578,0.670239,0.690527,0.651986,0.510611,0.585519,0.524309,0.652383,0.652173,0.503978,0.709759,0.653354,0.514358,0.516905,0.703193,0.516131,0.653309,0.513362,0.512212,0.655221,0.710005,0.520744,0.649029,0.705295,0.648758,0.701711,0.511978,0.512137,0.574421,0.656051,0.711905,0.567450,0.713055,0.704186,0.703585,0.511749,0.516308,0.517537,0.653501,0.652433,0.511611,0.513024,0.682848,0.702351,0.688299,0.574835,0.653470,0.502723,0.650919,0.569721,0.516504,0.694314,0.647694,0.697604,0.511822,0.587369,0.571603,0.509833,0.653884,0.514383,0.713559,0.717165,0.523706,0.695275,0.709623,0.510646,0.515677,0.697197,0.704379,0.509051,0.505751,0.519860,0.519703,0.523465,0.705162,0.507823,0.516201,0.512992,0.494806,0.705371,0.511191,0.514752,0.517096,0.694697,0.650330,0.505781,0.652960,0.524013,0.686770,0.519200,0.513593,0.651952,0.652344,0.680154,0.693708,0.689962,0.680762,0.695791,0.652811,0.672847,0.695549,0.716820,0.522125,0.686279,0.680883,0.566964,0.505134,0.683404,0.585925,0.573715,0.557990,0.653460,0.568864,0.520854,0.700789,0.523312,0.518655,0.574345,0.510916,0.683855,0.513378,0.654330,0.653923,0.579583,0.647767,0.513251,0.650496,0.677720,0.708824,0.705929,0.518132,0.511800,0.514952,0.680077,0.519149,0.566049,0.508376,0.707898,0.652954,0.564348,0.520594,0.514117,0.567784,0.513169,0.510256,0.651734,0.503397,0.574680,0.699151,0.515293,0.693332,0.569482,0.653517,0.519441,0.513059,0.538036,0.510557,0.651238,0.713305,0.500602,0.508416,0.545878,0.503097,0.649730,0.515368,0.651912,0.671446,0.715602,0.518610,0.680221,0.520918,0.708896,0.717396,0.516964,0.688163,0.569729,0.653880,0.655632,0.695192,0.688044,0.703624,0.714419,0.654125,0.706202,0.707524,0.512114,0.516625,0.574043,0.684085,0.681120,0.712694,0.650225,0.704170,0.698899,0.649067,0.516601,0.646641,0.645982,0.704806,0.572897,0.680677,0.515983,0.690671,0.686228,0.719286,0.650950,0.688164,0.512786,0.525002,0.651899,0.677703,0.698972,0.507371,0.715313,0.514602,0.523583,0.502375,0.509951,0.596583,0.719778,0.519451,0.692553,0.570689,0.692880,0.518420,0.502922,0.652336,0.561941,0.509271,0.520126,0.510356,0.710843,0.510975,0.683896,0.567892,0.683882,0.678660,0.516907,0.708571,0.710930,0.709524,0.705790,0.508239,0.504470,0.509405,0.571334,0.513434,0.574088,0.570302,0.512943,0.523881,0.515448,0.689936,0.676670,0.686793,0.656307,0.523339,0.507347,0.520895,0.651719,0.710644,0.505389,0.653801,0.516144,0.514814,0.523351,0.570681,0.649455,0.655672,0.650753,0.517681,0.649695,0.499920,0.653303,0.502974,0.514198,0.516057,0.501829,0.716803,0.687947,0.651475,0.655870,0.653976,0.507149,0.510691,0.522166,0.509190,0.695222,0.524861,0.653531,0.654644,0.696413,0.691453,0.681781,0.652196,0.521652,0.517536,0.510571,0.577704,0.703988,0.706829,0.647486,0.516295,0.656518,0.563425,0.706619,0.652648,0.548992,0.689965,0.687242,0.687396,0.509994,0.510763,0.503676,0.514066,0.565994,0.707176,0.679742,0.504268,0.519501,0.676191,0.713752,0.518074,0.674550,0.653833,0.550721,0.711204,0.710661,0.686793,0.654067,0.562084,0.678784,0.704565,0.703572,0.593077,0.693299,0.518294,0.567687,0.594932,0.514885,0.518958,0.652786,0.498365,0.517693,0.500120,0.654665
AL-03,0.740507,0.747610,0.517943,1.000000,0.761972,0.743247,0.768324,0.521519,0.764198,0.766312,0.758726,0.761759,0.512846,0.516568,0.516154,0.531989,0.730502,0.746722,0.750224,0.748504,0.765889,0.728454,0.533780,0.543250,0.766935,0.761658,0.592841,0.529175,0.538399,0.539123,0.514876,0.725607,0.593857,0.536542,0.531640,0.732409,0.536661,0.767081,0.754897,0.540917,0.542938,0.729117,0.516419,0.535515,0.514131,0.548299,0.580363,0.542130,0.593240,0.545604,0.731713,0.530198,0.531132,0.518090,0.541085,0.522768,0.514996,0.575378,0.512690,0.731591,0.534064,0.543059,0.531759,0.537189,0.724709,0.533131,0.750797,0.757405,0.741308,0.537764,0.526457,0.747651,0.726154,0.540665,0.534637,0.571322,0.533855,0.503756,0.522137,0.731613,0.759311,0.588415,0.763164,0.731923,0.729674,0.750434,0.537411,0.733596,0.756478,0.768424,0.533562,0.760692,0.733777,0.764977,0.758135,0.734587,0.540544,0.767559,0.730993,0.540212,0.726925,0.530060,0.764424,0.760842,0.571234,0.731148,0.534438,0.575797,0.537120,0.535032,0.533772,0.763271,0.763734,0.758929,0.734072,0.732517,0.764553,0.760408,0.516251,0.530182,0.524813,0.580660,0.732589,0.753577,0.730849,0.575395,0.763562,0.521456,0.727865,0.524466,0.749003,0.588202,0.574061,0.750911,0.730072,0.747939,0.541974,0.540851,0.769176,0.524489,0.539159,0.759349,0.763042,0.521769,0.530254,0.752796,0.751888,0.765668,0.755620,0.528558,0.535585,0.750460,0.759023,0.756306,0.742769,0.533804,0.760626,0.769903,0.759609,0.523784,0.732153,0.759257,0.731182,0.769232,0.514501,0.766384,0.757535,0.727737,0.729961,0.516955,0.527021,0.526629,0.513414,0.518792,0.729513,0.515963,0.523721,0.543523,0.767990,0.517916,0.513165,0.565129,0.749038,0.517616,0.577601,0.564611,0.558704,0.728718,0.566356,0.765805,0.532738,0.767460,0.767318,0.570997,0.755668,0.520244,0.757757,0.729517,0.731559,0.567526,0.726040,0.755948,0.731058,0.510058,0.536256,0.537781,0.766770,0.762087,0.760688,0.504503,0.769748,0.571244,0.755246,0.531479,0.733668,0.571066,0.762723,0.761774,0.560990,0.762239,0.749712,0.731028,0.742136,0.575269,0.529342,0.752672,0.525154,0.577116,0.730036,0.772643,0.751702,0.545046,0.755661,0.730104,0.542403,0.744776,0.749018,0.541924,0.753116,0.727790,0.761651,0.733192,0.501949,0.541017,0.760935,0.512471,0.764771,0.539771,0.543203,0.760026,0.524243,0.557347,0.727530,0.727933,0.522225,0.518498,0.530547,0.536725,0.732804,0.526733,0.537064,0.753058,0.753504,0.576093,0.520048,0.509964,0.530400,0.726309,0.530262,0.530548,0.727757,0.758208,0.723725,0.725591,0.533681,0.572819,0.505332,0.759375,0.523578,0.520363,0.544445,0.729555,0.519017,0.754644,0.769195,0.729132,0.514019,0.535451,0.749732,0.544358,0.764154,0.775336,0.746789,0.751394,0.599701,0.552018,0.766724,0.531563,0.571871,0.527479,0.771442,0.752679,0.732109,0.570730,0.760499,0.761793,0.758310,0.543890,0.758258,0.517441,0.568759,0.511335,0.517512,0.762383,0.534699,0.536661,0.536957,0.539319,0.750933,0.751582,0.759163,0.572361,0.766652,0.570403,0.571579,0.759416,0.769775,0.765620,0.524184,0.515806,0.519541,0.729078,0.769906,0.745455,0.759898,0.731972,0.535728,0.755543,0.730721,0.764279,0.759919,0.772081,0.571910,0.732982,0.729470,0.733683,0.766633,0.732971,0.743675,0.732194,0.749784,0.761710,0.764881,0.745072,0.541420,0.518701,0.728875,0.730228,0.733949,0.751829,0.754707,0.769272,0.746377,0.529797,0.771580,0.726950,0.729559,0.528189,0.527261,0.517248,0.732333,0.760747,0.762147,0.750643,0.573204,0.536518,0.538776,0.727629,0.764151,0.729301,0.566344,0.535493,0.732121,0.554878,0.526813,0.518387,0.524817,0.760549,0.747341,0.747463,0.770104,0.575236,0.536786,0.514176,0.743095,0.758995,0.510279,0.538943,0.767491,0.509146,0.727090,0.551020,0.538285,0.540398,0.521693,0.731448,0.564539,0.512358,0.531862,0.535721,0.593334,0.518988,0.763246,0.578284,0.591046,0.761118,0.765872,0.733996,0.741217,0.762974,0.742391,0.731138

In [11]:
post.shape

(422, 20000)

In [12]:
def get_tipping_point(sim):
    """
    :param sim: Series representing one posterior draw or "simulation"
    :type sim: pd.Series
    """
    seats_won_dem = np.sum(sim > 0)
    if seats_won_dem >= 218 - dem_uncont.shape[0]: # Democrats win House in this draw
        sim = sim.sort_values(ascending=True)
        won_seats = sim[sim > 0]
        seat_margin = seats_won_dem - (218 - dem_uncont.shape[0])
    else: # Republicans win House in this draw
        sim = sim.sort_values(ascending=False)
        won_seats = sim[sim < 0]
        seat_margin = (435 - seats_won_dem) - (218 - rep_uncont.shape[0])
    return won_seats.iloc[seat_margin - 1], won_seats.index[seat_margin - 1]

In [13]:
tipping_points = np.array([]) # tipping point for *each sim*

for i in tqdm(range(post.shape[1])):
    sim = post.iloc[:, i]
    _, tp_seat = get_tipping_point(sim)
    tipping_points = np.append(tipping_points, tp_seat)

tipping_points

100%|███████████████████████████████████████████████████████████████████████████| 20000/20000 [00:28<00:00, 704.57it/s]

array(['NY-01', 'VA-01', 'MI-04', ..., 'IA-01', 'WI-03', 'OH-15'],
      shape=(20000,), dtype='<U32')

In [14]:
data = pd.read_csv('../../model_output/house_predictions.csv')
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,...,baseline,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",...,-6.691602,-18.764506,-1,-37.529012,45.279167,3.612067,9.41,1,38.198416,52.305608
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",...,-28.655280,-38.923019,0,-77.846039,35.785512,3.594815,0.02,2,28.752683,42.864268
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",...,-6.824413,-19.716169,1,-39.432338,47.964466,3.519277,27.91,3,40.988201,54.975968
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",...,-39.423181,-45.710827,-1,-91.421653,29.371185,3.505188,0.00,4,22.505018,36.254082
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",...,-59.715277,-47.132870,-1,-94.265741,19.663436,3.553191,0.00,5,12.688429,26.659381

In [15]:
data['tipping_point_prob'] = data['cd'].map(lambda x: np.mean(tipping_points == x) * 100)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,...,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",...,-18.764506,-1,-37.529012,45.279167,3.612067,9.41,1,38.198416,52.305608,0.115
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",...,-38.923019,0,-77.846039,35.785512,3.594815,0.02,2,28.752683,42.864268,0.000
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",...,-19.716169,1,-39.432338,47.964466,3.519277,27.91,3,40.988201,54.975968,1.395
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",...,-45.710827,-1,-91.421653,29.371185,3.505188,0.00,4,22.505018,36.254082,0.000
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",...,-47.132870,-1,-94.265741,19.663436,3.553191,0.00,5,12.688429,26.659381,0.000

In [16]:
data.sort_values('tipping_point_prob', ascending=False).head(7)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,...,dem_funds_2p_pct_offset,inc_dummy,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob
233,233,NC-11,Jamie Ager,Jennifer Balkcom,False,False,NC,11,"AGER, JAMIE",no_match,...,50.000000,0,100.000000,50.539886,3.702420,56.000,234,43.253319,57.813512,3.220
197,197,MI-10,Christina Hines,Mike Bouchard,False,False,MI,10,"HINES, CHRISTINA","BOUCHARD, MICHAEL",...,-3.195838,0,-6.391676,50.269814,3.684874,52.490,198,43.098468,57.478844,2.945
37,37,CA-22,Randy Villegas,David Valadao,False,True,CA,22,"VILLEGAS, RANDY","VALADAO, DAVID",...,12.732090,-1,25.464181,50.719620,3.506972,57.950,38,43.908238,57.653340,2.800
293,293,OH-07,Brian Poindexter,Max Miller,False,True,OH,7,"POINDEXTER, BRIAN","MILLER, MAX",...,-17.767963,-1,-35.535926,50.365858,3.585064,54.355,294,43.292932,57.346047,2.655
277,277,NY-17,Cait Conley,Mike Lawler,False,True,NY,17,"CONLEY, CAIT","LAWLER, MICHAEL VINCENT",...,3.773526,-1,7.547052,50.376213,3.509991,54.400,278,43.516361,57.242094,2.655
331,331,SC-01,Nancy Lacore,Jenny Costa Honeycutt,False,False,SC,1,"LACORE, NANCY","HONEYCUTT, JENNY COSTA",...,32.983182,0,65.966363,49.154024,3.704446,41.035,332,41.872879,56.540515,2.570
191,191,MI-04,Sean McCann,Bill Huizenga,False,True,MI,4,"MCCANN, SEAN","HUIZENGA, WILLIAM P",...,7.674047,-1,15.348095,49.947175,3.493298,49.510,192,43.100430,56.820153,2.535

In [17]:
def get_rating(dem_chance):
    if dem_chance > 100:
        raise ValueError('Invalid win chance.')
    if dem_chance > 95:
        return 'Safe D'
    elif dem_chance >= 90:
        return 'Very Likely D'
    elif dem_chance >= 75:
        return 'Likely D'
    elif dem_chance >= 65:
        return 'Lean D'
    elif dem_chance >= 60:
        return 'Tilt D'
    elif dem_chance >= 40:
        return 'Tossup'
    elif dem_chance >= 35:
        return 'Tilt R'
    elif dem_chance >= 25:
        return 'Lean R'
    elif dem_chance >= 10:
        return 'Likely R'
    elif dem_chance >= 5:
        return 'Very Likely R'
    else:
        return 'Safe R'

def get_matchup(dem_cand, rep_cand):
    indie_d = ['Bill Hill']
    indie_r = ['Kevin Kiley']
    
    if dem_cand in indie_d:
        dem_lab = dem_cand + ' (I)'
        dem_color = 'purple'
    else:
        dem_lab = dem_cand + ' (D)'
        dem_color = 'blue'
    
    if rep_cand in indie_r:
        rep_lab = rep_cand + ' (I)'
        rep_color = 'purple'
    else:
        rep_lab = rep_cand + ' (R)'
        rep_color = 'red'

    return f'<p style="color:{dem_color};">' + dem_lab + f'</p> vs <p style="color:{rep_cand}">' + rep_lab + '</p>'

In [18]:
data['rating'] = data['chance'].map(lambda x: get_rating(x))
for party in ['dem', 'rep']:
    data[f'{party}_cand'] = data[f'{party}_cand'].map(lambda x: 'TBD' if x[:3] == 'TBD' else x)
data['matchup'] = data[['dem_cand', 'rep_cand']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand']), axis=1)
data.head()

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,...,funds_pct_margin,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",...,-37.529012,45.279167,3.612067,9.41,1,38.198416,52.305608,0.115,Very Likely R,"<p style=""color:purple;"">Bill Hill (I)</p> vs ..."
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",...,-77.846039,35.785512,3.594815,0.02,2,28.752683,42.864268,0.000,Safe R,"<p style=""color:blue;"">Clyde Jones Jr. (D)</p>..."
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",...,-39.432338,47.964466,3.519277,27.91,3,40.988201,54.975968,1.395,Lean R,"<p style=""color:blue;"">Shomari Figures (D)</p>..."
3,3,AL-03,Lee McInnis,Mike Rogers,False,True,AL,3,"MCINNIS, VICTOR LEE","ROGERS, MICHAEL",...,-91.421653,29.371185,3.505188,0.00,4,22.505018,36.254082,0.000,Safe R,"<p style=""color:blue;"">Lee McInnis (D)</p> vs ..."
4,4,AL-04,Amanda Pusczek,Robert Aderholt,False,True,AL,4,"PUSCZEK, AMANDA NOELLE","ADERHOLT, ROBERT B. REP.",...,-94.265741,19.663436,3.553191,0.00,5,12.688429,26.659381,0.000,Safe R,"<p style=""color:blue;"">Amanda Pusczek (D)</p> ..."

In [19]:
data['projected_winner'] = data['chance'].map(lambda x: '(D)' if x > 50 else '(R)')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,...,y_pred,y_pred_sd,chance,index,ci_low,ci_hi,tipping_point_prob,rating,matchup,projected_winner
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",...,45.279167,3.612067,9.41,1,38.198416,52.305608,0.115,Very Likely R,"<p style=""color:purple;"">Bill Hill (I)</p> vs ...",(R)
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",...,35.785512,3.594815,0.02,2,28.752683,42.864268,0.000,Safe R,"<p style=""color:blue;"">Clyde Jones Jr. (D)</p>...",(R)
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",...,47.964466,3.519277,27.91,3,40.988201,54.975968,1.395,Lean R,"<p style=""color:blue;"">Shomari Figures (D)</p>...",(R)

In [20]:
pvi_24 = pd.read_csv('../../transformed/pvi/past_pres_results_by24dist.csv')
data = pd.merge(left=data, right=pvi_24[['district', 'party']], left_on='cd', right_on='district')
data = data.rename({'party': 'curr_party'}, axis=1)
data['hold'] = data['projected_winner'] ==  data['curr_party']
data['flip'] = data['hold'].map(lambda x: not x)
data['flip_indic'] = data['flip'].map(lambda x: 'Flip' if x else '')
#data['flip'] = data['flip'].map(lambda x: 'Yes' if x else 'No')
data.head(2)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,...,ci_hi,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",...,52.305608,0.115,Very Likely R,"<p style=""color:purple;"">Bill Hill (I)</p> vs ...",(R),AK-AL,(R),True,False,
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",...,42.864268,0.000,Safe R,"<p style=""color:blue;"">Clyde Jones Jr. (D)</p>...",(R),AL-01,(R),True,False,

In [21]:
data['projected_2p_margin'] = data['y_pred'].map(lambda y_pred: f'D+{y_pred - (100-y_pred):.1f}' if y_pred > 50 else f'R+{(100-y_pred) - y_pred:.1f}')
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,...,tipping_point_prob,rating,matchup,projected_winner,district_y,curr_party,hold,flip,flip_indic,projected_2p_margin
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",...,0.115,Very Likely R,"<p style=""color:purple;"">Bill Hill (I)</p> vs ...",(R),AK-AL,(R),True,False,,R+9.4
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",...,0.000,Safe R,"<p style=""color:blue;"">Clyde Jones Jr. (D)</p>...",(R),AL-01,(R),True,False,,R+28.4
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",...,1.395,Lean R,"<p style=""color:blue;"">Shomari Figures (D)</p>...",(R),AL-02,(D),False,True,Flip,R+4.1

In [22]:
data['rep_chance'] = data['chance'].map(lambda x: 100 - x)
data['rounded_dem_chance'] = data['chance'].map(lambda x: np.round(x, 1))
data['rounded_rep_chance'] = data['rep_chance'].map(lambda x: np.round(x, 1))
data['disp_dem_chance'] = data['rounded_dem_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data['disp_rep_chance'] = data['rounded_rep_chance'].map(lambda x: '>99%' if x > 99 else ('<1%' if x < 1 else str(x) + '%'))
data.head(3)

,...1,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fec_dem_fuzzymatch,fec_rep_fuzzymatch,...,curr_party,hold,flip,flip_indic,projected_2p_margin,rep_chance,rounded_dem_chance,rounded_rep_chance,disp_dem_chance,disp_rep_chance
0,0,AK-AL,Bill Hill,Nick Begich,False,True,AK,0,"HILL, BILL","BEGICH, NICHOLAS III",...,(R),True,False,,R+9.4,90.59,9.4,90.6,9.4%,90.6%
1,1,AL-01,Clyde Jones Jr.,Jerry Carl,False,False,AL,1,"JONES, CLYDE W MR. JR","CARL, JERRY LEE, JR",...,(R),True,False,,R+28.4,99.98,0.0,100.0,<1%,>99%
2,2,AL-02,Shomari Figures,Rhett Marques,True,False,AL,2,"FIGURES, SHOMARI C.","MARQUES, RHETT",...,(D),False,True,Flip,R+4.1,72.09,27.9,72.1,27.9%,72.1%

In [23]:
data['geoid']

0       200
1       101
2       102
3       103
4       104
       ...
417    5507
418    5508
419    5401
420    5402
421    5600
Name: geoid, Length: 422, dtype: int64

In [24]:
dem_uclen = dem_uncont.shape[0]
dem_uncont['rating'] = np.full(dem_uclen, 'Safe D')
dem_uncont['chance'] = np.full(dem_uclen, 100)
dem_uncont['disp_dem_chance'] = np.full(dem_uclen, '100%')
dem_uncont['disp_rep_chance'] = np.full(dem_uclen, '0%')
dem_uncont['projected_2p_margin'] = np.full(dem_uclen, 'D+100')
dem_uncont['flip_indic'] = np.full(dem_uclen, '')
dem_uncont = dem_uncont.drop(['Unnamed: 0'], axis=1)
dem_uncont['matchup'] = dem_uncont[['dem_cand', 'rep_cand']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand']), axis=1)
dem_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-04,Mike Thompson/Eric Jones,Not Contested,True,False,CA,4,6,604,Safe D,100,100%,0%,D+100,,"<p style=""color:blue;"">Mike Thompson/Eric Jone..."
1,CA-07,Doris Matsui/Mai Vang,Not Contested,True,False,CA,7,6,607,Safe D,100,100%,0%,D+100,,"<p style=""color:blue;"">Doris Matsui/Mai Vang (..."
2,CA-11,Scott Weiner/Connie Chan,Not Contested,False,False,CA,11,6,611,Safe D,100,100%,0%,D+100,,"<p style=""color:blue;"">Scott Weiner/Connie Cha..."
3,CA-12,Lateefah Simon,Not Contested,True,False,CA,12,6,612,Safe D,100,100%,0%,D+100,,"<p style=""color:blue;"">Lateefah Simon (D)</p> ..."
4,CA-14,Aisha Wahab/Melissa Hernandez,Not Contested,False,False,CA,14,6,614,Safe D,100,100%,0%,D+100,,"<p style=""color:blue;"">Aisha Wahab/Melissa Her..."

In [25]:
rep_uclen = rep_uncont.shape[0]
rep_uncont['rating'] = np.full(rep_uclen, 'Safe R')
rep_uncont['chance'] = np.full(rep_uclen, 0)
rep_uncont['disp_dem_chance'] = np.full(rep_uclen, '0%')
rep_uncont['disp_rep_chance'] = np.full(rep_uclen, '100%')
rep_uncont['projected_2p_margin'] = np.full(rep_uclen, 'R+100')
rep_uncont['flip_indic'] = np.full(rep_uclen, '')
rep_uncont = rep_uncont.drop(['Unnamed: 0'], axis=1)
rep_uncont['matchup'] = rep_uncont[['dem_cand', 'rep_cand']].apply(lambda x: get_matchup(x['dem_cand'], x['rep_cand']), axis=1)
rep_uncont.head()

,cd,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po,district_number,fips,geoid,rating,chance,disp_dem_chance,disp_rep_chance,projected_2p_margin,flip_indic,matchup
0,CA-40,Not Contested,Young Kim/Ken Calvert,False,True,CA,40,6,640,Safe R,0,0%,100%,R+100,,"<p style=""color:blue;"">Not Contested (D)</p> v..."

In [26]:
incl_cols = ['cd', 'dem_cand', 'rep_cand', 'dem_inc_any', 'rep_inc_any', 'rating', 'chance', 'disp_dem_chance',
            'disp_rep_chance', 'projected_2p_margin', 'flip_indic', 'geoid', 'matchup']
disp_data = pd.concat([data[incl_cols], dem_uncont[incl_cols], rep_uncont[incl_cols]], axis=0)
disp_data.shape

(435, 13)

In [27]:
disp_data.to_csv('display_data/choropleth_display_data.csv')
data.to_csv('display_data/table_display_data.csv')