In [71]:
import warnings
warnings.filterwarnings('ignore')

In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from rapidfuzz import fuzz, process

In [73]:
pd.set_option('display.max_columns', 500)

In [74]:
us_state_to_abbrev = {
    "Alabama": "AL",
    "Alaska": "AK",
    "Arizona": "AZ",
    "Arkansas": "AR",
    "California": "CA",
    "Colorado": "CO",
    "Connecticut": "CT",
    "Delaware": "DE",
    "Florida": "FL",
    "Georgia": "GA",
    "Hawaii": "HI",
    "Idaho": "ID",
    "Illinois": "IL",
    "Indiana": "IN",
    "Iowa": "IA",
    "Kansas": "KS",
    "Kentucky": "KY",
    "Louisiana": "LA",
    "Maine": "ME",
    "Maryland": "MD",
    "Massachusetts": "MA",
    "Michigan": "MI",
    "Minnesota": "MN",
    "Mississippi": "MS",
    "Missouri": "MO",
    "Montana": "MT",
    "Nebraska": "NE",
    "Nevada": "NV",
    "New Hampshire": "NH",
    "New Jersey": "NJ",
    "New Mexico": "NM",
    "New York": "NY",
    "North Carolina": "NC",
    "North Dakota": "ND",
    "Ohio": "OH",
    "Oklahoma": "OK",
    "Oregon": "OR",
    "Pennsylvania": "PA",
    "Rhode Island": "RI",
    "South Carolina": "SC",
    "South Dakota": "SD",
    "Tennessee": "TN",
    "Texas": "TX",
    "Utah": "UT",
    "Vermont": "VT",
    "Virginia": "VA",
    "Washington": "WA",
    "West Virginia": "WV",
    "Wisconsin": "WI",
    "Wyoming": "WY",
    "District of Columbia": "DC",
    "American Samoa": "AS",
    "Guam": "GU",
    "Northern Mariana Islands": "MP",
    "Puerto Rico": "PR",
    "United States Minor Outlying Islands": "UM",
    "Virgin Islands, U.S.": "VI",
} 

abbrev_to_us_state = dict(map(reversed, us_state_to_abbrev.items()))
# https://gist.github.com/rogerallen/1583593

In [75]:
url = "https://www.nytimes.com/newsgraphics/polls/senate.csv"
polls = pd.read_csv(url)
polls.to_csv('../../2026_data/polls/senate.csv')
polls = polls[
    (polls['state'] != 'US') &
    (polls['stage'] == 'general')
]
polls.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,methodology,transparency_score,state,start_date,end_date,sponsor_candidate_id,sponsor_candidate,sponsor_candidate_party,question_id,sample_size,population,subpopulation,population_full,tracking,created_at,notes,url,url_article,url_topline,url_crosstab,source,internal,partisan,cycle,office_type,seat_name,seat_number,election_date,stage,party,pct,answer,candidate_name,candidate_id,race_id,ranked_choice_round,ranked_choice_reallocated,ranked_choice_final,nationwide_match,hypothetical
0,b3c26b29-cc2f-472a-b43e-e75efff555f4,9a75302d-c3be-4e86-ac7b-c6a6a2a52ac3,Trafalgar Group,NaN,NaN,Trafalgar Group,338.0,Trafalgar Group,NaN,NaN,NaN,NaN,SC,9/23/26,9/25/26,NaN,NaN,NaN,6f86a5e2-f626-4adc-bcbb-f9cc23de4137,1087.0,lv,NaN,lv,NaN,9/26/26 17:50,NaN,https://www.thetrafalgargroup.org/news/sc-sen-...,NaN,NaN,NaN,NaN,NaN,REP,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,8.5,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,15314566-c454-4722-b119-8ac87efa2e93,NaN,False,False,NaN,NaN
1,b3c26b29-cc2f-472a-b43e-e75efff555f4,9a75302d-c3be-4e86-ac7b-c6a6a2a52ac3,Trafalgar Group,NaN,NaN,Trafalgar Group,338.0,Trafalgar Group,NaN,NaN,NaN,NaN,SC,9/23/26,9/25/26,NaN,NaN,NaN,6f86a5e2-f626-4adc-bcbb-f9cc23de4137,1087.0,lv,NaN,lv,NaN,9/26/26 17:50,NaN,https://www.thetrafalgargroup.org/news/sc-sen-...,NaN,NaN,NaN,NaN,NaN,REP,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,5.9,Someone else,Someone else,d23503df-ca4b-41e0-807f-67f2629609ac,15314566-c454-4722-b119-8ac87efa2e93,NaN,False,False,NaN,NaN
2,b3c26b29-cc2f-472a-b43e-e75efff555f4,9a75302d-c3be-4e86-ac7b-c6a6a2a52ac3,Trafalgar Group,NaN,NaN,Trafalgar Group,338.0,Trafalgar Group,NaN,NaN,NaN,NaN,SC,9/23/26,9/25/26,NaN,NaN,NaN,6f86a5e2-f626-4adc-bcbb-f9cc23de4137,1087.0,lv,NaN,lv,NaN,9/26/26 17:50,NaN,https://www.thetrafalgargroup.org/news/sc-sen-...,NaN,NaN,NaN,NaN,NaN,REP,2026,U.S. Senate,NaN,NaN,2026-11-03,general,DEM,42.3,Andrews (Annie),Annie Andrews,3b708929-ecc4-4ed8-8369-cd9512a89493,15314566-c454-4722-b119-8ac87efa2e93,NaN,False,False,NaN,NaN
3,b3c26b29-cc2f-472a-b43e-e75efff555f4,9a75302d-c3be-4e86-ac7b-c6a6a2a52ac3,Trafalgar Group,NaN,NaN,Trafalgar Group,338.0,Trafalgar Group,NaN,NaN,NaN,NaN,SC,9/23/26,9/25/26,NaN,NaN,NaN,6f86a5e2-f626-4adc-bcbb-f9cc23de4137,1087.0,lv,NaN,lv,NaN,9/26/26 17:50,NaN,https://www.thetrafalgargroup.org/news/sc-sen-...,NaN,NaN,NaN,NaN,NaN,REP,2026,U.S. Senate,NaN,NaN,2026-11-03,general,REP,43.4,Graham (Darline),Darline Graham,5f8e0206-1e9e-440f-bacd-639587401823,15314566-c454-4722-b119-8ac87efa2e93,NaN,False,False,NaN,NaN
4,88eb5386-5920-4931-bf47-30dd37462322,adedfb3e-f4d9-4121-ae17-125b39b27da3,InsiderAdvantage,NaN,NaN,InsiderAdvantage,243.0,InsiderAdvantage,NaN,NaN,NaN,NaN,IA,9/22/26,9/23/26,NaN,NaN,NaN,95784b09-7945-45f9-8f07-9cef31c93714,1200.0,lv,NaN,lv,NaN,9/26/26 13:39,NaN,https://insideradvantage.com/ia-topline-tabs/,NaN,NaN,NaN,NaN,NaN,NaN,2026,U.S. Senate,NaN,NaN,2026-11-03,general,NONE,4.4,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,6504c9a1-f6af-4517-8475-b563a47234cf,NaN,False,False,NaN,NaN

In [76]:
polls = polls[~((polls['state'] == 'ME') & (pd.to_datetime(polls['start_date']) < pd.to_datetime("2026-09-08")))]
polls = polls.replace({'James Davis': 'Jamie Davis'})

In [77]:
polls_pivot = pd.pivot_table(data=polls, values='pct', index=['poll_id', 'question_id', 'state'], columns='candidate_name', aggfunc='first')
polls_pivot = polls_pivot.reset_index()
polls_pivot.head()

candidate_name,poll_id,question_id,state,Aaron Day,Abdul El-Sayed,Adam Hamilton,Alani Bankhead,Alexander Vindman,Allen Buckley,Amy McGrath,Andy Barr,Angie Craig,Angie Nixon,Ann Diener,Annie Andrews,Ashley Hinson,Ashley Moody,Barry Moore,Ben Ray Luján,Beto O’Rourke,Bill Hagerty,Bill Huizenga,Bill Redpath,Brad Raffensperger,Brian Bengs,Brian Kemp,Buddy Carter,Camencia Ford,Charles Booker,Charles D. Baker,Chris Pappas,Chris Sununu,Christine Lopez,Christopher Miklos,Cindy Burbank,Cindy Hyde-Smith,Colin Allred,Curtis Stinnett,Dan Innis,Dan J. Sullivan,Dan Osborn,Dan Sullivan,Daniel Cameron,Darline Graham,David Graham,David Roth,Derek Dooley,Don Brown,Don't know,Don't know/Someone else,Don't know/Would not vote,Douglas Marsh,Dustin Darden,Ed Markey,Edmond LaPlante,Edmond Laplante,Everett Wess,Frank Edelblut,Generic Candidate,Generic Democrat,Generic Republican,Gerald Heikes,Glenn Youngkin,Gregory Levy,Gretchen Whitmer,Haley Stevens,Hallie Shoffner,Hans Truelson,Hector Mujica,Jack Reed,Jackie Norris,James Risch,James Ryan,James Talarico,Jamie Davis,Jasmine Crockett,Jeanne Logan Morrow,Jeanne Shaheen,Jeff Wadlin,Jennifer Jenkins,Jim Priest,Joaquin Castro,Joe Tache,John Cornyn,John Deaton,John Fetterman,John King,John Sununu,John Warren,Jon Husted,Jon Ossoff,Joni Ernst,Josh Turek,Joshua Cain,Julia Letlow,Julian Beaudion,Kasie Whitener,Kelly Loeffler,Ken Paxton,Kevin Hern,Kurt Alme,Kyle Austin,Lara Trump,Larry Marker,Lindsey Graham,Lydia Christensen,Mallory McMorrow,Marisa Simonetti,Marjorie Taylor Greene,Mark Lynch,Mark Sanford,Mark Warner,Marquita Bradshaw,Mary Peltola,Matt Giovonizzi,Matt Loesby,Michael Bahry,Michael Dublin,Michael Whatley,Michele Tafoya,Mike Collins,Mike Rogers,Mike Rounds,N'Kiyla Jasmine Thomas,Nancy Mace,Natalie Fleming,Nate Morris,Nathan Sage,Neil Gillespie,Neither,Noah Taylor,None/other,Other named candidates,Pamela Evette,Patrick Schmidt,Peggy Flanagan,Pete Buttigieg,Pete Ricketts,Ralph Norman,Raymond McKay,Rebecca Whiting,Reilly Neill,Rich McCormick,Roger Marshall,Ron Meinhardt,Roy Cooper,Russell Fry,Scott Brown,Scott Colom,Seth Bodnar,Seth Moulton,Sevier White,Shannon Bray,Sherrod Brown,Sidney Hill,Someone else,Steve Daines,Susan Collins,Ted Brown,Thom Tillis,Thomas Laehn,Tim Harris,Tim Ryan,Timothy Long,Todd Achilles,Tom Cotton,Tom Jandron,Trey Gowdy,Troy Jackson,Ty Pinkins,Walter Kristy,Wesley Hunt,William J. Forbes,Would not vote,Zach Wahls
0,006eec7f-5ceb-4b68-8c21-658e35d6bb9a,8371ba4e-f777-48e0-a65b-904ffc8ff19c,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,007278d5-49cd-4aa2-9400-8c95c5fc50c5,071b6561-2fc5-4c00-98dd-4119da46c8d9,MI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,007278d5-49cd-4aa2-9400-8c95c5fc50c5,5afce063-c336-43c7-b41b-5766cd1221de,MI,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,02747cb8-c9f8-4c09-b283-67fcf0ec90b0,0b89445f-5182-43eb-9b9d-9e803fb08d93,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,056c5919-461b-4fd7-bb50-e04c47588d89,2e684b07-925d-4455-ac65-cf75899fa878,MI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
candinfo_url = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vTZTum7NEaS6hvniyNJbDTWLDY0rATtgR5yXV2EUbtt6ubRPqv1sVH3PdJM3rgAzS_ak_XSgxLtaq3-/pub?output=csv'
candinfo = pd.read_csv(candinfo_url)

In [79]:
dem_uncont = candinfo[candinfo['rep_cand'] == 'Not Contested']
rep_uncont = candinfo[candinfo['dem_cand'] == 'Not Contested']
candinfo = candinfo[(candinfo['dem_cand'] != 'Not Contested') &
    (candinfo['rep_cand'] != 'Not Contested')]
candinfo['state_po'] = candinfo['state'].astype(str).map(us_state_to_abbrev)
candinfo.head()

,state,dem_cand,rep_cand,dem_inc_any,rep_inc_any,state_po
0,Alabama,Everett Weiss,Barry Moore,False,False,AL
1,Alaska,Mary Peltola,Dan S. Sullivan,False,True,AK
2,Arkansas,Hallie Shoffner,Tom Cotton,False,True,AR
3,Colorado,John Hickenlooper,Mark Baisley,True,False,CO
4,Delaware,Chris Coons,Michael Katz,True,False,DE

In [80]:
dem_uncont.shape, rep_uncont.shape

((0, 5), (0, 5))

In [81]:
candinfo_transp = candinfo.set_index(['state_po']).T
candinfo_transp.head()

state_po,AL,AK,AR,CO,DE,FL,GA,ID,IL,IA,KS,KY,LA,ME,MA,MI,MN,MS,MT,NE,NH,NJ,NM,NC,OH,OK,OR,RI,SC,SD,TN,TX,VA,WV,WY
state,Alabama,Alaska,Arkansas,Colorado,Delaware,Florida,Georgia,Idaho,Illinois,Iowa,Kansas,Kentucky,Louisiana,Maine,Massachusetts,Michigan,Minnesota,Mississippi,Montana,Nebraska,New Hampshire,New Jersey,New Mexico,North Carolina,Ohio,Oklahoma,Oregon,Rhode Island,South Carolina,South Dakota,Tennessee,Texas,Virginia,West Virginia,Wyoming
dem_cand,Everett Weiss,Mary Peltola,Hallie Shoffner,John Hickenlooper,Chris Coons,Angie Nixon,Jon Ossoff,Todd Achilles,Juliana Stratton,Josh Turek,Adam Hamilton,Charles Booker,Jamie Davis,Troy Jackson,Ed Markey,Abdul El-Sayed,Peggy Flanagan,Scott Colom,Seth Bodnar,Dan Osborn,Chris Pappas,Cory Booker,Ben Ray Lujan,Roy Cooper,Sherrod Brown,N'Kiyla Thomas,Jeff Merkley,Jack Reed,Annie Andrews,Brian Bengs,Marquita Bradshaw,James Talarico,Mark Warner,Rachel Fetty Anderson,James W. Byrd
rep_cand,Barry Moore,Dan S. Sullivan,Tom Cotton,Mark Baisley,Michael Katz,Ashley Moody,Mike Collins,Jim Risch,Don Tracy,Ashley Hinson,Roger Marshall,Andy Barr,Julia Letlow,Susan Collins,John Deaton,Mike J. Rogers,Michele Tafoya,Cindy Hyde-Smith,Kurt Alme,Pete Ricketts,John Sununu,Justin Murphy,Larry Marker,Michael Whatley,Jon Husted,Kevin Hern,David Brock Smith,Raymond McKay,Darline Graham,Mike Rounds,Bill Hagerty,Ken Paxton,Bert Mizusawa,Shelley Moore Capito,Harriet Hageman
dem_inc_any,False,False,False,True,True,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,True,False,False,False,True,True,False,False,False,False,True,False,False
rep_inc_any,False,True,True,False,False,True,False,True,False,False,True,False,False,True,False,False,False,True,False,True,False,False,False,False,True,False,False,False,False,True,True,False,False,True,False

In [101]:
rel_pollids = []
rel_questionids = []

for st in candinfo['state_po']:
    df = polls[polls['state'] == st]
    dem_cand = candinfo_transp.loc['dem_cand', st]
    rep_cand = candinfo_transp.loc['rep_cand', st]
    dem_fuzzymatch = process.extractOne(dem_cand, np.unique(df[df['party'].isin(['DEM', 'OTH', 'IND'])]['candidate_name']), scorer=fuzz.token_sort_ratio, score_cutoff=80)
    rep_fuzzymatch = process.extractOne(rep_cand, np.unique(df[df['party'].isin(['REP', 'OTH', 'IND'])]['candidate_name']), scorer=fuzz.token_sort_ratio, score_cutoff=80)
    if dem_fuzzymatch is None or rep_fuzzymatch is None:
        if dem_cand == "N'Kiyla Thomas":
            dem_fuzzymatch = ("N'Kiyla Jasmine Thomas", 100, 0)
        else:
            continue
    if rep_fuzzymatch[0] == 'Dan J. Sullivan':
        rep_fuzzymatch = ('Dan Sullivan', 100, 0)

    df = pd.pivot_table(df, values='pct', index=['poll_id', 'question_id', 'state'], columns='candidate_name', aggfunc='first').reset_index()
    
    if dem_fuzzymatch is not None:
        df = df[~df[dem_fuzzymatch[0]].isna()]
    if rep_fuzzymatch is not None:
        df = df[~df[rep_fuzzymatch[0]].isna()]
    pollids = np.unique(df['poll_id'])
    questionids = np.unique(df['question_id'])
    rel_pollids.extend(pollids)
    rel_questionids.extend(questionids)

    ## for debugging purposes
    print(f'{dem_cand} -- {dem_fuzzymatch[0]} | {rep_cand} -- {rep_fuzzymatch[0]} | Relevant polls: {len(pollids)}')

Everett Weiss -- Everett Wess | Barry Moore -- Barry Moore | Relevant polls: 1
Mary Peltola -- Mary Peltola | Dan S. Sullivan -- Dan Sullivan | Relevant polls: 19
Hallie Shoffner -- Hallie Shoffner | Tom Cotton -- Tom Cotton | Relevant polls: 4
Angie Nixon -- Angie Nixon | Ashley Moody -- Ashley Moody | Relevant polls: 9
Jon Ossoff -- Jon Ossoff | Mike Collins -- Mike Collins | Relevant polls: 16
Todd Achilles -- Todd Achilles | Jim Risch -- James Risch | Relevant polls: 6
Josh Turek -- Josh Turek | Ashley Hinson -- Ashley Hinson | Relevant polls: 20
Adam Hamilton -- Adam Hamilton | Roger Marshall -- Roger Marshall | Relevant polls: 7
Charles Booker -- Charles Booker | Andy Barr -- Andy Barr | Relevant polls: 2
Jamie Davis -- Jamie Davis | Julia Letlow -- Julia Letlow | Relevant polls: 2
Troy Jackson -- Troy Jackson | Susan Collins -- Susan Collins | Relevant polls: 4
Ed Markey -- Ed Markey | John Deaton -- John Deaton | Relevant polls: 10
Abdul El-Sayed -- Abdul El-Sayed | Mike J. Rogers -- Mike Rogers | Relevant polls: 37
Peggy Flanagan -- Peggy Flanagan | Michele Tafoya -- Michele Tafoya | Relevant polls: 8
Scott Colom -- Scott Colom | Cindy Hyde-Smith -- Cindy Hyde-Smith | Relevant polls: 2
Seth Bodnar -- Seth Bodnar | Kurt Alme -- Kurt Alme | Relevant polls: 12
Dan Osborn -- Dan Osborn | Pete Ricketts -- Pete Ricketts | Relevant polls: 7
Chris Pappas -- Chris Pappas | John Sununu -- John Sununu | Relevant polls: 20
Ben Ray Lujan -- Ben Ray Luján | Larry Marker -- Larry Marker | Relevant polls: 1
Roy Cooper -- Roy Cooper | Michael Whatley -- Michael Whatley | Relevant polls: 36
Sherrod Brown -- Sherrod Brown | Jon Husted -- Jon Husted | Relevant polls: 22
N'Kiyla Thomas -- N'Kiyla Jasmine Thomas | Kevin Hern -- Kevin Hern | Relevant polls: 1
Jack Reed -- Jack Reed | Raymond McKay -- Raymond McKay | Relevant polls: 4
Annie Andrews -- Annie Andrews | Darline Graham -- Darline Graham | Relevant polls: 4
Brian Bengs -- Brian Bengs | Mike Rounds -- Mike Rounds | Relevant polls: 7
Marquita Bradshaw -- Marquita Bradshaw | Bill Hagerty -- Bill Hagerty | Relevant polls: 1
James Talarico -- James Talarico | Ken Paxton -- Ken Paxton | Relevant polls: 39

In [99]:
len(rel_pollids), len(rel_questionids)

(27, 27)

In [39]:
polled_cands = polls_pivot.columns.values[3:]
running_dems = np.unique(candinfo['dem_cand'].astype(str))
running_reps = np.unique(candinfo['rep_cand'].astype(str))
all_running_cands = np.concatenate([running_dems, running_reps])

In [40]:
all_running_cands

array(['Abdul El-Sayed', 'Adam Hamilton', 'Angie Nixon', 'Annie Andrews',
       'Ben Ray Lujan', 'Brian Bengs', 'Charles Booker', 'Chris Coons',
       'Chris Pappas', 'Cory Booker', 'Dan Osborn', 'Ed Markey',
       'Everett Weiss', 'Hallie Shoffner', 'Jack Reed', 'James Talarico',
       'James W. Byrd', 'Jamie Davis', 'Jeff Merkley',
       'John Hickenlooper', 'Jon Ossoff', 'Josh Turek',
       'Juliana Stratton', 'Mark Warner', 'Marquita Bradshaw',
       'Mary Peltola', "N'Kiyla Thomas", 'Peggy Flanagan',
       'Rachel Fetty Anderson', 'Roy Cooper', 'Scott Colom',
       'Seth Bodnar', 'Sherrod Brown', 'Todd Achilles', 'Troy Jackson',
       'Andy Barr', 'Ashley Hinson', 'Ashley Moody', 'Barry Moore',
       'Bert Mizusawa', 'Bill Hagerty', 'Cindy Hyde-Smith',
       'Dan S. Sullivan', 'Darline Graham', 'David Brock Smith',
       'Don Tracy', 'Harriet Hageman', 'Jim Risch', 'John Deaton',
       'John Sununu', 'Jon Husted', 'Julia Letlow', 'Justin Murphy',
       'Ken Paxton', 'Kevin Hern', 'Kurt Alme', 'Larry Marker',
       'Mark Baisley', 'Michael Katz', 'Michael Whatley',
       'Michele Tafoya', 'Mike Collins', 'Mike J. Rogers', 'Mike Rounds',
       'Pete Ricketts', 'Raymond McKay', 'Roger Marshall',
       'Shelley Moore Capito', 'Susan Collins', 'Tom Cotton'],
      dtype=object)

In [41]:
hypo_cands = []
for c in polled_cands:
    fuzzymatch = process.extractOne(c, all_running_cands, scorer=fuzz.token_sort_ratio, score_cutoff=80)
    if fuzzymatch is None:
        hypo_cands.append(c)

In [42]:
hypo_cands

['Aaron Day',
 'Alani Bankhead',
 'Alexander Vindman',
 'Allen Buckley',
 'Amy McGrath',
 'Angie Craig',
 'Ann Diener',
 'Beto O’Rourke',
 'Bill Huizenga',
 'Bill Redpath',
 'Brad Raffensperger',
 'Brian Kemp',
 'Buddy Carter',
 'Camencia Ford',
 'Chris Sununu',
 'Christine Lopez',
 'Christopher Miklos',
 'Cindy Burbank',
 'Colin Allred',
 'Curtis Stinnett',
 'Dan Innis',
 'Daniel Cameron',
 'David Graham',
 'David Roth',
 'Derek Dooley',
 'Don Brown',
 "Don't know",
 "Don't know/Someone else",
 "Don't know/Would not vote",
 'Douglas Marsh',
 'Dustin Darden',
 'Edmond LaPlante',
 'Edmond Laplante',
 'Frank Edelblut',
 'Generic Candidate',
 'Generic Democrat',
 'Generic Republican',
 'Gerald Heikes',
 'Glenn Youngkin',
 'Gregory Levy',
 'Gretchen Whitmer',
 'Haley Stevens',
 'Hans Truelson',
 'Hector Mujica',
 'Jackie Norris',
 'James Ryan',
 'Jasmine Crockett',
 'Jeanne Logan Morrow',
 'Jeanne Shaheen',
 'Jeff Wadlin',
 'Jennifer Jenkins',
 'Jim Priest',
 'Joaquin Castro',
 'Joe Tache',
 'John Cornyn',
 'John Fetterman',
 'John King',
 'John Warren',
 'Joni Ernst',
 'Joshua Cain',
 'Julian Beaudion',
 'Kasie Whitener',
 'Kelly Loeffler',
 'Kyle Austin',
 'Lara Trump',
 'Lindsey Graham',
 'Lydia Christensen',
 'Mallory McMorrow',
 'Marisa Simonetti',
 'Marjorie Taylor Greene',
 'Mark Lynch',
 'Mark Sanford',
 'Matt Giovonizzi',
 'Matt Loesby',
 'Michael Bahry',
 'Michael Dublin',
 "N'Kiyla Jasmine Thomas",
 'Nancy Mace',
 'Natalie Fleming',
 'Nate Morris',
 'Nathan Sage',
 'Neil Gillespie',
 'Neither',
 'Noah Taylor',
 'None/other',
 'Other named candidates',
 'Pamela Evette',
 'Patrick Schmidt',
 'Pete Buttigieg',
 'Ralph Norman',
 'Rebecca Whiting',
 'Reilly Neill',
 'Rich McCormick',
 'Ron Meinhardt',
 'Russell Fry',
 'Scott Brown',
 'Seth Moulton',
 'Sevier White',
 'Shannon Bray',
 'Sidney Hill',
 'Someone else',
 'Steve Daines',
 'Ted Brown',
 'Thom Tillis',
 'Thomas Laehn',
 'Tim Harris',
 'Tim Ryan',
 'Timothy Long',
 'Tom Jandron',
 'Trey Gowdy',
 'Ty Pinkins',
 'Walter Kristy',
 'Wesley Hunt',
 'William J. Forbes',
 'Would not vote',
 'Zach Wahls']

In [43]:
for h in hypo_cands:
    if h in ["N'Kiyla Jasmine Thomas",  "Don't know",
 "Don't know/Someone else",
 "Don't know/Would not vote", 'Someone else', 'Would not vote']:
        continue
    # print(h, polls_pivot["Christina Bohannan"].isna().all())
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

for h in ['Dan J. Sullivan']: # names that weren't caught in hypo_cands but should've been
    polls_pivot = polls_pivot[polls_pivot[h].isna()]
    polls_pivot = polls_pivot.drop([h], axis=1)

In [44]:
polls_pivot.columns.values

array(['poll_id', 'question_id', 'state', 'Abdul El-Sayed',
       'Adam Hamilton', 'Andy Barr', 'Angie Nixon', 'Annie Andrews',
       'Ashley Hinson', 'Ashley Moody', 'Barry Moore', 'Ben Ray Luján',
       'Bill Hagerty', 'Brian Bengs', 'Charles Booker',
       'Charles D. Baker', 'Chris Pappas', 'Cindy Hyde-Smith',
       'Dan Osborn', 'Dan Sullivan', 'Darline Graham', "Don't know",
       "Don't know/Someone else", "Don't know/Would not vote",
       'Ed Markey', 'Everett Wess', 'Hallie Shoffner', 'Jack Reed',
       'James Davis', 'James Risch', 'James Talarico', 'Jamie Davis',
       'John Deaton', 'John Sununu', 'Jon Husted', 'Jon Ossoff',
       'Josh Turek', 'Julia Letlow', 'Ken Paxton', 'Kevin Hern',
       'Kurt Alme', 'Larry Marker', 'Mark Warner', 'Marquita Bradshaw',
       'Mary Peltola', 'Michael Whatley', 'Michele Tafoya',
       'Mike Collins', 'Mike Rogers', 'Mike Rounds',
       "N'Kiyla Jasmine Thomas", 'Peggy Flanagan', 'Pete Ricketts',
       'Raymond McKay', 'Roger Marshall', 'Roy Cooper', 'Scott Colom',
       'Seth Bodnar', 'Sherrod Brown', 'Someone else', 'Susan Collins',
       'Todd Achilles', 'Tom Cotton', 'Troy Jackson', 'Would not vote'],
      dtype=object)

In [45]:
polls_pivot.shape

(242, 65)

In [46]:
rel_polls = polls[(polls['poll_id'].isin(np.unique(polls_pivot['poll_id']))) &
    (polls['question_id'].isin(np.unique(polls_pivot['question_id'])))]

In [47]:
rel_polls.shape

(823, 50)

In [48]:
np.unique(rel_polls['candidate_name'])

array(['Abdul El-Sayed', 'Adam Hamilton', 'Andy Barr', 'Angie Nixon',
       'Annie Andrews', 'Ashley Hinson', 'Ashley Moody', 'Barry Moore',
       'Ben Ray Luján', 'Brian Bengs', 'Charles Booker',
       'Charles D. Baker', 'Chris Pappas', 'Cindy Hyde-Smith',
       'Dan Osborn', 'Dan Sullivan', 'Darline Graham', "Don't know",
       "Don't know/Someone else", "Don't know/Would not vote",
       'Ed Markey', 'Everett Wess', 'Hallie Shoffner', 'Jack Reed',
       'James Davis', 'James Risch', 'James Talarico', 'Jamie Davis',
       'John Deaton', 'John Sununu', 'Jon Husted', 'Jon Ossoff',
       'Josh Turek', 'Julia Letlow', 'Ken Paxton', 'Kurt Alme',
       'Larry Marker', 'Mary Peltola', 'Michael Whatley',
       'Michele Tafoya', 'Mike Collins', 'Mike Rogers', 'Mike Rounds',
       'Peggy Flanagan', 'Pete Ricketts', 'Raymond McKay',
       'Roger Marshall', 'Roy Cooper', 'Scott Colom', 'Seth Bodnar',
       'Sherrod Brown', 'Someone else', 'Susan Collins', 'Todd Achilles',
       'Tom Cotton', 'Troy Jackson', 'Would not vote'], dtype=object)

In [55]:
pd.DataFrame(rel_polls[['candidate_name', 'party']].value_counts()).reset_index()

               candidate_name party  count
0                  Don't know  NONE    196
1                Someone else  NONE    106
2              Abdul El-Sayed   DEM     36
3                 Mike Rogers   REP     36
4              Would not vote  NONE     33
5                  Roy Cooper   DEM     31
6             Michael Whatley   REP     31
7                  Ken Paxton   REP     23
8              James Talarico   DEM     23
9                  Jon Ossoff   DEM     19
10              Sherrod Brown   DEM     19
11               Mike Collins   REP     19
12                 Jon Husted   REP     19
13               Chris Pappas   DEM     17
14                John Sununu   REP     17
15                 Josh Turek   DEM     16
16              Ashley Hinson   REP     16
17               Mary Peltola   DEM     13
18               Dan Sullivan   REP     13
19                  Ed Markey   DEM     10
20                John Deaton   REP      8
21               Ashley Moody   REP      8
22                Angie Nixon   DEM      8
23              Pete Ricketts   REP      7
24                 Dan Osborn   DEM      7
25                Mike Rounds   REP      7
26                Brian Bengs   IND      7
27                  Kurt Alme   REP      5
28                Seth Bodnar   IND      5
29  Don't know/Would not vote  NONE      4
30               Troy Jackson   DEM      4
31              Susan Collins   REP      4
32             Roger Marshall   REP      4
33             Peggy Flanagan   DEM      4
34             Michele Tafoya   REP      4
35              Annie Andrews   DEM      4
36             Darline Graham   REP      4
37              Adam Hamilton   DEM      3
38              Todd Achilles   IND      3
39                James Risch   REP      3
40            Hallie Shoffner   DEM      2
41                 Tom Cotton   REP      2
42                  Jack Reed   DEM      2
43              Raymond McKay   REP      2
44           Charles D. Baker   REP      2
45           Cindy Hyde-Smith   REP      2
46                  Andy Barr   REP      2
47               Julia Letlow   REP      2
48             Charles Booker   DEM      2
49                Jamie Davis   DEM      2
50               Larry Marker   REP      1
51                Barry Moore   REP      1
52                Scott Colom   DEM      1
53    Don't know/Someone else  NONE      1
54              Adam Hamilton   IND      1
55              Ben Ray Luján   DEM      1
56               Everett Wess   DEM      1

In [51]:
rel_polls.to_csv('transformed/relevent_senate_polls.csv')