In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from rapidfuzz import fuzz, process

In [5]:
pd.set_option('display.max_columns', 500)

In [3]:
url = "https://www.nytimes.com/newsgraphics/polls/senate.csv"
polls = pd.read_csv(url)
polls.to_csv('../../2026_data/polls/senate.csv')
polls = polls[
    (polls['state'] != 'US') &
    (polls['stage'] == 'general')
]
polls.head()

,poll_id,pollster_id,pollster,sponsor_ids,sponsors,display_name,pollster_rating_id,pollster_rating_name,numeric_grade,pollscore,...,pct,answer,candidate_name,candidate_id,race_id,ranked_choice_round,ranked_choice_reallocated,ranked_choice_final,nationwide_match,hypothetical
0,e05c43ca-5439-4bac-8148-b5a35785ebbd,312f97da-ebc5-446e-8856-cdded6ea1251,Big Data Poll,b519a86f-dbb8-46a2-8215-6abb6f6f389d,Public Polling Project,Big Data Poll,251.0,Big Data Poll,NaN,NaN,...,41.0,Rogers (Mike),Mike Rogers,7d9e51b3-0abf-43eb-8e48-5e03788745f6,8069ba7e-4ac6-449d-ae1e-f7fc5dee4a19,NaN,False,False,NaN,NaN
1,e05c43ca-5439-4bac-8148-b5a35785ebbd,312f97da-ebc5-446e-8856-cdded6ea1251,Big Data Poll,b519a86f-dbb8-46a2-8215-6abb6f6f389d,Public Polling Project,Big Data Poll,251.0,Big Data Poll,NaN,NaN,...,45.4,El-Sayed,Abdul El-Sayed,2a1df6eb-59e4-4618-bf83-69c693f46fb2,8069ba7e-4ac6-449d-ae1e-f7fc5dee4a19,NaN,False,False,NaN,NaN
2,e05c43ca-5439-4bac-8148-b5a35785ebbd,312f97da-ebc5-446e-8856-cdded6ea1251,Big Data Poll,b519a86f-dbb8-46a2-8215-6abb6f6f389d,Public Polling Project,Big Data Poll,251.0,Big Data Poll,NaN,NaN,...,42.1,Rogers (Mike),Mike Rogers,7d9e51b3-0abf-43eb-8e48-5e03788745f6,8069ba7e-4ac6-449d-ae1e-f7fc5dee4a19,NaN,False,False,NaN,NaN
3,e05c43ca-5439-4bac-8148-b5a35785ebbd,312f97da-ebc5-446e-8856-cdded6ea1251,Big Data Poll,b519a86f-dbb8-46a2-8215-6abb6f6f389d,Public Polling Project,Big Data Poll,251.0,Big Data Poll,NaN,NaN,...,46.7,El-Sayed,Abdul El-Sayed,2a1df6eb-59e4-4618-bf83-69c693f46fb2,8069ba7e-4ac6-449d-ae1e-f7fc5dee4a19,NaN,False,False,NaN,NaN
4,8f08ac98-5fe9-4052-a192-4157657541eb,7c25f6c3-cc63-4614-aec1-dfc392ef7872,Opinion Diagnostics,b8f5cd64-907b-45a3-ad37-256031be79f6,Common Cause North Carolina,Opinion Diagnostics,769.0,Opinion Diagnostics,NaN,NaN,...,2.8,Don't know,Don't know,d8390906-54c4-4050-9005-4934a65fa7b1,70395c5f-9aee-4a8f-a647-b656d0f894a3,NaN,False,False,NaN,NaN

In [7]:
polls_pivot = pd.pivot_table(data=polls, values='pct', index=['poll_id', 'question_id', 'state'], columns='candidate_name', aggfunc='first')
polls_pivot = polls_pivot.reset_index()
polls_pivot.head()

candidate_name,poll_id,question_id,state,Aaron Day,Abdul El-Sayed,Adam Hamilton,Alani Bankhead,Alexander Vindman,Allen Buckley,Amy McGrath,Andy Barr,Angie Craig,Angie Nixon,Ann Diener,Annie Andrews,Ashley Hinson,Ashley Moody,Barry Moore,Ben Ray Luján,Beto O’Rourke,Bill Hagerty,Bill Huizenga,Bill Redpath,Brad Raffensperger,Brian Bengs,Brian Kemp,Buddy Carter,Camencia Ford,Charles Booker,Charles D. Baker,Chris Pappas,Chris Sununu,Christine Lopez,Christopher Miklos,Cindy Burbank,Cindy Hyde-Smith,Colin Allred,Curtis Stinnett,Dan Innis,Dan J. Sullivan,Dan Kleban,Dan Osborn,Dan Sullivan,Daniel Cameron,Darline Graham,David Graham,David Roth,Derek Dooley,Don Brown,Don't know,Don't know/Someone else,Don't know/Would not vote,Douglas Marsh,Dustin Darden,Ed Markey,Edmond LaPlante,Edmond Laplante,Everett Wess,Frank Edelblut,Generic Candidate,Generic Democrat,Generic Republican,Gerald Heikes,Glenn Youngkin,Graham Platner,Gregory Levy,Gretchen Whitmer,Haley Stevens,Hallie Shoffner,Hans Truelson,Hector Mujica,Jack Reed,Jackie Norris,James Davis,James Risch,James Ryan,James Talarico,Jamie Davis,Janet Mills,Jasmine Crockett,Jeanne Logan Morrow,Jeanne Shaheen,Jeff Wadlin,Jennifer Jenkins,Jim Priest,Joaquin Castro,Joe Tache,John Cornyn,John Deaton,John Fetterman,John King,John Sununu,John Warren,Jon Husted,Jon Ossoff,Joni Ernst,Jordan Wood,Josh Turek,Joshua Cain,Julia Letlow,Julian Beaudion,Kasie Whitener,Kelly Loeffler,Ken Paxton,Kevin Hern,Kurt Alme,Kyle Austin,Lara Trump,Larry Marker,Lindsey Graham,Lydia Christensen,Mallory McMorrow,Marisa Simonetti,Marjorie Taylor Greene,Mark Lynch,Mark Sanford,Mark Warner,Marquita Bradshaw,Mary Peltola,Matt Giovonizzi,Matt Loesby,Michael Bahry,Michael Dublin,Michael Whatley,Michele Tafoya,Mike Collins,Mike Rogers,Mike Rounds,N'Kiyla Jasmine Thomas,Nancy Mace,Natalie Fleming,Nate Morris,Nathan Sage,Neil Gillespie,Neither,Nirav Shah,Noah Taylor,None/other,Other named candidates,Pamela Evette,Patrick Schmidt,Peggy Flanagan,Pete Buttigieg,Pete Ricketts,Ralph Norman,Raymond McKay,Rebecca Whiting,Reilly Neill,Rich McCormick,Roger Marshall,Ron Meinhardt,Roy Cooper,Russell Fry,Scott Brown,Scott Colom,Seth Bodnar,Seth Moulton,Sevier White,Shannon Bray,Shenna Bellows,Sherrod Brown,Sidney Hill,Someone else,Steve Daines,Susan Collins,Ted Brown,Thom Tillis,Thomas Laehn,Tim Harris,Tim Ryan,Timothy Long,Todd Achilles,Tom Cotton,Tom Jandron,Trey Gowdy,Troy Jackson,Ty Pinkins,Walter Kristy,Wesley Hunt,William J. Forbes,Would not vote,Zach Wahls
0,006eec7f-5ceb-4b68-8c21-658e35d6bb9a,8371ba4e-f777-48e0-a65b-904ffc8ff19c,TX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.0,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,007278d5-49cd-4aa2-9400-8c95c5fc50c5,071b6561-2fc5-4c00-98dd-4119da46c8d9,MI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,007278d5-49cd-4aa2-9400-8c95c5fc50c5,5afce063-c336-43c7-b41b-5766cd1221de,MI,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,02747cb8-c9f8-4c09-b283-67fcf0ec90b0,0b89445f-5182-43eb-9b9d-9e803fb08d93,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,056c5919-461b-4fd7-bb50-e04c47588d89,2e684b07-925d-4455-ac65-cf75899fa878,MI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,48.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN